"""
Fantasy Seed Catalog — ~500 books across 14 subgenres.
Seeding strategy: max 2 books per author, max 4 per series, prioritize subgenre coverage over author depth.
"""

FANTASY_SEED_BOOKS = {
    # ═══════════════════════════════════════════════════════════════════
    # EPIC HIGH FANTASY (~90)
    # ═══════════════════════════════════════════════════════════════════
    "Epic High Fantasy": [
        ("The Fellowship of the Ring", "J.R.R. Tolkien"),
        ("The Return of the King", "J.R.R. Tolkien"),
        ("The Eye of the World", "Robert Jordan"),
        ("The Great Hunt", "Robert Jordan"),
        ("Assassin's Apprentice", "Robin Hobb"),
        ("The Final Empire", "Brandon Sanderson"),
        ("The Way of Kings", "Brandon Sanderson"),
        ("Gardens of the Moon", "Steven Erikson"),
        ("Deadhouse Gates", "Steven Erikson"),
        ("The Name of the Wind", "Patrick Rothfuss"),
        ("A Wizard of Earthsea", "Ursula K. Le Guin"),
        ("The Tombs of Atuan", "Ursula K. Le Guin"),
        ("Magician: Apprentice", "Raymond E. Feist"),
        ("The Dragonbone Chair", "Tad Williams"),
        ("Tigana", "Guy Gavriel Kay"),
        ("The Lions of Al-Rassan", "Guy Gavriel Kay"),
        ("The Golden Compass", "Philip Pullman"),
        ("Luck in the Shadows", "Lynn Flewelling"),
        ("Dragonflight", "Anne McCaffrey"),
        ("Stardust", "Neil Gaiman"),
        ("The Deed of Paksenarrion", "Elizabeth Moon"),
        ("The Shadow of the Torturer", "Gene Wolfe"),
        ("Nine Princes in Amber", "Roger Zelazny"),
        ("Pawn of Prophecy", "David Eddings"),
        ("A Game of Thrones", "George R.R. Martin"),
        ("A Storm of Swords", "George R.R. Martin"),
        ("The Legend of Drizzt: Homeland", "R.A. Salvatore"),
        ("The Ruins of Ambrai", "Melanie Rawn"),
        ("The Curse of Chalion", "Lois McMaster Bujold"),
        ("Paladin of Souls", "Lois McMaster Bujold"),
        ("King's Dragon", "Kate Elliott"),
        ("The Winter King", "Bernard Cornwell"),
        ("The Sword in the Stone", "T.H. White"),
        ("Legend", "David Gemmell"),
        ("Waylander", "David Gemmell"),
        ("Kushiel's Dart", "Jacqueline Carey"),
        ("The Poppy War", "R.F. Kuang"),
        ("The Grace of Kings", "Ken Liu"),
        ("City of Stairs", "Robert Jackson Bennett"),
        ("The Shadow of What Was Lost", "James Islington"),
        ("The Black Prism", "Brent Weeks"),
        ("Promise of Blood", "Brian McClellan"),
        ("Nevernight", "Jay Kristoff"),
        ("The City of Brass", "Shannon Chakraborty"),
        ("The Bear and the Nightingale", "Katherine Arden"),
        ("The Last Wish", "Andrzej Sapkowski"),
        ("The Blade Itself", "Joe Abercrombie"),
        ("The Blacktongue Thief", "Christopher Buehlman"),
        ("Half a King", "Joe Abercrombie"),
        ("She Who Became the Sun", "Shelley Parker-Chan"),
        ("The Bone Shard Daughter", "Andrea Stewart"),
        ("The Jasmine Throne", "Tasha Suri"),
        ("Priory of the Orange Tree", "Samantha Shannon"),
        ("The Unbroken", "C.L. Clark"),
        ("The Sword of Kaigen", "M.L. Wang"),
        ("The Rage of Dragons", "Evan Winter"),
        ("The Library of Mount Char", "Scott Hawkins"),
        ("The Gutter Prayer", "Gareth Hanrahan"),
        ("The Ember Blade", "Chris Wooding"),
        ("The Wounded Kingdom", "R.J. Barker"),
        ("Age of Assassins", "R.J. Barker"),
        ("Battle Mage", "Peter Flannery"),
        ("Red Seas Under Red Skies", "Scott Lynch"),
        ("Legacy of the Brightwash", "Krystle Matar"),
        ("God Known Through Touch", "J.A. Ironside"),
        ("The Monster of Elendhaven", "Jennifer Giesbrecht"),
        ("The Maleficent Seven", "Cameron Johnston"),
        ("The Council of Animals", "Nick McDonell"),
        ("The Stardust Thief", "Chelsea Abdullah"),
        ("The Adventures of Amina al-Sirafi", "Shannon Chakraborty"),
        ("The Book That Wouldn't Burn", "Mark Lawrence"),
        ("The Justice of Kings", "Richard Swan"),
        ("The Pariah", "Anthony Ryan"),
        ("The Martyr", "Anthony Ryan"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # GRIMDARK (~50)
    # ═══════════════════════════════════════════════════════════════════
    "Grimdark": [
        ("Before They Are Hanged", "Joe Abercrombie"),
        ("The Heroes", "Joe Abercrombie"),
        ("Prince of Thorns", "Mark Lawrence"),
        ("The Red Queen's War", "Mark Lawrence"),
        ("The Black Company", "Glen Cook"),
        ("The Darkness That Comes Before", "R. Scott Bakker"),
        ("The Warrior-Prophet", "R. Scott Bakker"),
        ("Beyond Redemption", "Michael R. Fletcher"),
        ("Court of Broken Knives", "Anna Smith Spark"),
        ("The Steel Remains", "Richard K. Morgan"),
        ("A Crown for Cold Silver", "Alex Marshall"),
        ("The Red Knight", "Miles Cameron"),
        ("The Barrow", "Mark Smylie"),
        ("The Scar", "China Mieville"),
        ("Perdido Street Station", "China Mieville"),
        ("The Fifth Season", "N.K. Jemisin"),
        ("The Shadow of the Gods", "John Gwynne"),
        ("The Hunger of the Gods", "John Gwynne"),
        ("Aching God", "Mike Shel"),
        ("Throne of the Crescent Moon", "Saladin Ahmed"),
        ("The Vagrant", "Peter Newman"),
        ("Empire of the Vampire", "Jay Kristoff"),
        ("The Court of the Blind King", "David Guymer"),
        ("Gods of the Wyrdwood", "R.J. Barker"),
        ("The Book of the New Sun", "Gene Wolfe"),
        ("The War for the Rose Throne", "Peter McLean"),
        ("Priest of Bones", "Peter McLean"),
        ("The Tyrant Philosophers", "Adrian Tchaikovsky"),
        ("The Fall of the House of Usher", "Edgar Allan Poe"),
        ("The Dark Star", "Marlon James"),
        ("Kings of Paradise", "Richard Nell"),
        ("The Bonehunters", "Steven Erikson"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # DARK FANTASY (~45)
    # ═══════════════════════════════════════════════════════════════════
    "Dark Fantasy": [
        ("Kushiel's Chosen", "Jacqueline Carey"),
        ("The Poppy War", "R.F. Kuang"),
        ("Between Two Fires", "Christopher Buehlman"),
        ("American Gods", "Neil Gaiman"),
        ("The Library at Mount Char", "Scott Hawkins"),
        ("The Croning", "Laird Barron"),
        ("The Fisherman", "John Langan"),
        ("The Vorrh", "Brian Catling"),
        ("The Child Thief", "Brom"),
        ("The Painted Man", "Peter V. Brett"),
        ("The Warded Man", "Peter V. Brett"),
        ("The Second Apocalypse", "R. Scott Bakker"),
        ("The Coldfire Trilogy", "C.S. Friedman"),
        ("The Black Jewels", "Anne Bishop"),
        ("The God Eaters", "Ashley N. Rostek"),
        ("Empire of the Vampire", "Jay Kristoff"),
        ("The Kill Society", "Richard Kadrey"),
        ("Sandman Slim", "Richard Kadrey"),
        ("The Dark Tower: The Gunslinger", "Stephen King"),
        ("The Drawing of the Three", "Stephen King"),
        ("Elantris", "Brandon Sanderson"),
        ("The Sword of Kaigen", "M.L. Wang"),
        ("The Once and Future Witches", "Alix E. Harrow"),
        ("Circe", "Madeline Miller"),
        ("The Song of Achilles", "Madeline Miller"),
        ("The Lost Sisters", "Holly Black"),
        ("The Dark is Rising", "Susan Cooper"),
        ("The Last Unicorn", "Peter S. Beagle"),
        ("The Forgotten Beasts of Eld", "Patricia A. McKillip"),
        ("Eyes of the Hammer", "Bob Mayer"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # ROMANTASY (~90)
    # ═══════════════════════════════════════════════════════════════════
    "Romantasy": [
        ("A Court of Thorns and Roses", "Sarah J. Maas"),
        ("A Court of Mist and Fury", "Sarah J. Maas"),
        ("Throne of Glass", "Sarah J. Maas"),
        ("From Blood and Ash", "Jennifer L. Armentrout"),
        ("A Kingdom of Flesh and Fire", "Jennifer L. Armentrout"),
        ("Fourth Wing", "Rebecca Yarros"),
        ("Iron Flame", "Rebecca Yarros"),
        ("Divine Rivals", "Rebecca Ross"),
        ("Ruthless Vows", "Rebecca Ross"),
        ("The Serpent and the Wings of Night", "Carissa Broadbent"),
        ("The Ashes and the Star-Cursed King", "Carissa Broadbent"),
        ("Quicksilver", "Callie Hart"),
        ("Spark of the Everflame", "Penn Cole"),
        ("Glow of the Everflame", "Penn Cole"),
        ("Trial of the Sun Queen", "Nisha J. Tuli"),
        ("Rule of the Aurora King", "Nisha J. Tuli"),
        ("The Hurricane Wars", "Thea Guanzon"),
        ("Phantasma", "Kaylie Smith"),
        ("Neon Gods", "Katee Robert"),
        ("Electric Idol", "Katee Robert"),
        ("Kingdom of the Wicked", "Kerri Maniscalco"),
        ("Kingdom of the Cursed", "Kerri Maniscalco"),
        ("A Touch of Darkness", "Scarlett St. Clair"),
        ("A Touch of Ruin", "Scarlett St. Clair"),
        ("When the Moon Hatched", "Sarah A. Parker"),
        ("The Bridge Kingdom", "Danielle L. Jensen"),
        ("The Traitor Queen", "Danielle L. Jensen"),
        ("Gild", "Raven Kennedy"),
        ("Glint", "Raven Kennedy"),
        ("Daughter of No Worlds", "Carissa Broadbent"),
        ("The Wren in the Holly Library", "K.A. Linde"),
        ("Amid Clouds and Bones", "Ella Fields"),
        ("The Highwayman", "Kerrigan Byrne"),
        ("The Book of Azrael", "Amber V. Nicole"),
        ("The Crown of Oaths and Curses", "J. Bree"),
        ("The Harbinger", "Chloe I. Felton"),
        ("The Curse of Saints", "Kate Dramis"),
        ("Song of the Forever Rains", "E.J. Mellow"),
        ("A Dawn of Onyx", "Kate Golden"),
        ("The Ever King", "L.J. Andrews"),
        ("The Serpent and the Wolf", "Rebecca Robinson"),
        ("A Shadow in the Ember", "Jennifer L. Armentrout"),
        ("A Light in the Flame", "Jennifer L. Armentrout"),
        ("Kingdom of Ash", "Sarah J. Maas"),
        ("The Witch Collector", "Charissa Weaks"),
        ("City of Gods and Monsters", "Kayla Edwards"),
        ("Kingdom of Stars and Shadows", "Adrienne K. Young"),
        ("The Darkest Night", "Gena Showalter"),
        ("The Goddess Test", "Aimee Carter"),
        ("House of Earth and Blood", "Sarah J. Maas"),
        ("A Fate Inked in Blood", "Danielle L. Jensen"),
        ("The Stars are Dying", "Chloe Penaranda"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # COZY FANTASY (~30)
    # ═══════════════════════════════════════════════════════════════════
    "Cozy Fantasy": [
        ("The House in the Cerulean Sea", "TJ Klune"),
        ("Under the Whispering Door", "TJ Klune"),
        ("Legends & Lattes", "Travis Baldree"),
        ("Bookshops & Bonedust", "Travis Baldree"),
        ("The Very Secret Society of Irregular Witches", "Sangu Mandanna"),
        ("The Spellshop", "Sarah Beth Durst"),
        ("A Psalm for the Wild-Built", "Becky Chambers"),
        ("A Prayer for the Crown-Shy", "Becky Chambers"),
        ("Spindle's End", "Robin McKinley"),
        ("The Princess Bride", "William Goldman"),
        ("The Long Way to a Small Angry Planet", "Becky Chambers"),
        ("Howl's Moving Castle", "Diana Wynne Jones"),
        ("Chalice", "Robin McKinley"),
        ("The Girl Who Fell Beneath the Sea", "Axie Oh"),
        ("Emily Wilde's Encyclopaedia of Faeries", "Heather Fawcett"),
        ("Emily Wilde's Map of the Otherlands", "Heather Fawcett"),
        ("A Far Wilder Magic", "Allison Saft"),
        ("Half a Soul", "Olivia Atwater"),
        ("Ten Thousand Stitches", "Olivia Atwater"),
        ("The Very Secret Society of Irregular Witches", "Sangu Mandanna"),
        ("The Lights of Prague", "Nicole Jarvis"),
        ("Cerulia's Wake", "Krystle Matar"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # URBAN FANTASY (~70)
    # ═══════════════════════════════════════════════════════════════════
    "Urban Fantasy": [
        ("Storm Front", "Jim Butcher"),
        ("Changes", "Jim Butcher"),
        ("Magic Bites", "Ilona Andrews"),
        ("Burn for Me", "Ilona Andrews"),
        ("Slave to Sensation", "Nalini Singh"),
        ("Kiss of Snow", "Nalini Singh"),
        ("Dead Witch Walking", "Kim Harrison"),
        ("The Good, the Bad, and the Undead", "Kim Harrison"),
        ("Guilty Pleasures", "Laurell K. Hamilton"),
        ("The Killing Dance", "Laurell K. Hamilton"),
        ("Moon Called", "Patricia Briggs"),
        ("Iron Kissed", "Patricia Briggs"),
        ("Some Girls Bite", "Chloe Neill"),
        ("Twice Bitten", "Chloe Neill"),
        ("Rosemary and Rue", "Seanan McGuire"),
        ("An Artificial Night", "Seanan McGuire"),
        ("Unclean Spirits", "M.L.N. Hanover"),
        ("Pawn", "Aimee Carter"),
        ("Dark Lover", "J.R. Ward"),
        ("Lover Eternal", "J.R. Ward"),
        ("Halfway to the Grave", "Jeaniene Frost"),
        ("One Foot in the Grave", "Jeaniene Frost"),
        ("A Discovery of Witches", "Deborah Harkness"),
        ("Shadow of Night", "Deborah Harkness"),
        ("Hunter's Oath", "Michelle West"),
        ("City of Bones", "Cassandra Clare"),
        ("City of Ashes", "Cassandra Clare"),
        ("Wicked Lovely", "Melissa Marr"),
        ("Neverwhere", "Neil Gaiman"),
        ("The Night Circus", "Erin Morgenstern"),
        ("The Starless Sea", "Erin Morgenstern"),
        ("The Golem and the Jinni", "Helene Wecker"),
        ("The Library of the Dead", "T.L. Huchu"),
        ("Dead Things", "Stephen Blackmoore"),
        ("Dog Days", "John Levitt"),
        ("War for the Oaks", "Emma Bull"),
        ("Moonheart", "Charles de Lint"),
        ("Yarrow", "Charles de Lint"),
        ("The Rook", "Daniel O'Malley"),
        ("Stiletto", "Daniel O'Malley"),
        ("The Invisible Library", "Genevieve Cogman"),
        ("The Mortal Instruments", "Cassandra Clare"),
        ("Poison Study", "Maria V. Snyder"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # FAIRY TALE RETELLING (~35)
    # ═══════════════════════════════════════════════════════════════════
    "Fairy Tale Retelling": [
        ("Cinder", "Marissa Meyer"),
        ("Scarlet", "Marissa Meyer"),
        ("Beauty", "Robin McKinley"),
        ("Rose Daughter", "Robin McKinley"),
        ("The Bloody Chamber", "Angela Carter"),
        ("Deerskin", "Robin McKinley"),
        ("Uprooted", "Naomi Novik"),
        ("Spinning Silver", "Naomi Novik"),
        ("Enchantment", "Orson Scott Card"),
        ("The Witch's Heart", "Genevieve Gornichec"),
        ("The Sleeper and the Spindle", "Neil Gaiman"),
        ("A Curse So Dark and Lonely", "Brigid Kemmerer"),
        ("A Heart So Fierce and Broken", "Brigid Kemmerer"),
        ("Cruel Beauty", "Rosamund Hodge"),
        ("Crimson Bound", "Rosamund Hodge"),
        ("The Bear and the Nightingale", "Katherine Arden"),
        ("The Shadow Queen", "C.J. Redwine"),
        ("The Blood Spell", "C.J. Redwine"),
        ("Ella Enchanted", "Gail Carson Levine"),
        ("The Goose Girl", "Shannon Hale"),
        ("Book of a Thousand Days", "Shannon Hale"),
        ("Heartless", "Marissa Meyer"),
        ("To Kill a Kingdom", "Alexandra Christo"),
        ("The Wrath and the Dawn", "Renee Ahdieh"),
        ("The Rose and the Dagger", "Renee Ahdieh"),
        ("Fairest", "Marissa Meyer"),
        ("The Princess and the Fangirl", "Ashley Poston"),
        ("Snow Like Ashes", "Sara Raasch"),
        ("Bitter Greens", "Kate Forsyth"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # SWORD & SORCERY / PULP FANTASY (~30)
    # ═══════════════════════════════════════════════════════════════════
    "Sword & Sorcery": [
        ("The Coming of Conan the Cimmerian", "Robert E. Howard"),
        ("The Hour of the Dragon", "Robert E. Howard"),
        ("Ill Met in Lankhmar", "Fritz Leiber"),
        ("Swords Against Death", "Fritz Leiber"),
        ("Elric of Melnibone", "Michael Moorcock"),
        ("The Sailor on the Seas of Fate", "Michael Moorcock"),
        ("Legend", "David Gemmell"),
        ("Waylander", "David Gemmell"),
        ("The Dread Empire", "Glen Cook"),
        ("Kane", "Karl Edward Wagner"),
        ("The Swords of the Steppes", "Harold Lamb"),
        ("The Broken Sword", "Poul Anderson"),
        ("Three Hearts and Three Lions", "Poul Anderson"),
        ("The Worm Ouroboros", "E.R. Eddison"),
        ("The King of Elfland's Daughter", "Lord Dunsany"),
        ("The Well of the Unicorn", "Fletcher Pratt"),
        ("The Complete Compleat Enchanter", "L. Sprague de Camp"),
        ("Conan the Adventurer", "Robert E. Howard"),
        ("Swords and Deviltry", "Fritz Leiber"),
        ("Tales of the Dying Earth", "Jack Vance"),
        ("The Eyes of the Overworld", "Jack Vance"),
        ("The Simbul's Gift", "Lynn Abbey"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # GASLAMP FANTASY (~25)
    # ═══════════════════════════════════════════════════════════════════
    "Gaslamp Fantasy": [
        ("Soulless", "Gail Carriger"),
        ("Changeless", "Gail Carriger"),
        ("Jonathan Strange & Mr Norrell", "Susanna Clarke"),
        ("The Ladies of Grace Adieu", "Susanna Clarke"),
        ("Uprooted", "Naomi Novik"),
        ("Spinning Silver", "Naomi Novik"),
        ("A Darker Shade of Magic", "V.E. Schwab"),
        ("A Gathering of Shadows", "V.E. Schwab"),
        ("The Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson"),
        ("The Haunting of Hill House", "Shirley Jackson"),
        ("The White Road", "Sarah Lotz"),
        ("The Golem and the Jinni", "Helene Wecker"),
        ("The Midnight Queen", "Sylvia Izzo Hunter"),
        ("The Watchmaker of Filigree Street", "Natasha Pulley"),
        ("The Bedlam Stacks", "Natasha Pulley"),
        ("The Invisible Life of Addie LaRue", "V.E. Schwab"),
        ("Ninth House", "Leigh Bardugo"),
        ("Hell Bent", "Leigh Bardugo"),
        ("The Essex Serpent", "Sarah Perry"),
        ("The Winter Witch", "Paula Brackston"),
        ("The Silver Witch", "Paula Brackston"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # SCIENCE FANTASY (~30)
    # ═══════════════════════════════════════════════════════════════════
    "Science Fantasy": [
        ("Dune", "Frank Herbert"),
        ("Dune Messiah", "Frank Herbert"),
        ("The Shadow of the Torturer", "Gene Wolfe"),
        ("The Claw of the Conciliator", "Gene Wolfe"),
        ("Lord of Light", "Roger Zelazny"),
        ("Creatures of Light and Darkness", "Roger Zelazny"),
        ("The Fifth Season", "N.K. Jemisin"),
        ("The Obelisk Gate", "N.K. Jemisin"),
        ("The Long Way to a Small Angry Planet", "Becky Chambers"),
        ("A Memory Called Empire", "Arkady Martine"),
        ("Ancillary Justice", "Ann Leckie"),
        ("Ninefox Gambit", "Yoon Ha Lee"),
        ("The Curse of Chalion", "Lois McMaster Bujold"),
        ("Paladin of Souls", "Lois McMaster Bujold"),
        ("The Stars My Destination", "Alfred Bester"),
        ("The Demolished Man", "Alfred Bester"),
        ("Hyperion", "Dan Simmons"),
        ("The Fall of Hyperion", "Dan Simmons"),
        ("Book of the New Sun", "Gene Wolfe"),
        ("The Rediscovery of Man", "Cordwainer Smith"),
        ("Tales of the Dying Earth", "Jack Vance"),
        ("The Dragon Never Dies", "John W. Campbell"),
        ("Vagabonds", "Hao Jingfang"),
        ("The Redemption of Alastair", "Colin R. Williams"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # PROGRESSION FANTASY (~25)
    # ═══════════════════════════════════════════════════════════════════
    "Progression Fantasy": [
        ("Unsouled", "Will Wight"),
        ("Cradle", "Will Wight"),
        ("The Wandering Inn", "pirateaba"),
        ("He Who Fights With Monsters", "Shirtaloon"),
        ("Defiance of the Fall", "TheFirstDefier"),
        ("Mother of Learning", "Domagoj Kurmaic"),
        ("The Beginning After the End", "TurtleMe"),
        ("A Will Eternal", "Er Gen"),
        ("Reverend Insanity", "Gu Zhen Ren"),
        ("Arcane Ascension", "Andrew Rowe"),
        ("Sufficiently Advanced Magic", "Andrew Rowe"),
        ("The Perfect Run", "Maxime J. Durand"),
        ("The Primal Hunter", "Zogarth"),
        ("Dungeon Crawler Carl", "Matt Dinniman"),
        ("Iron Prince", "Bryce O'Connor"),
        ("Bastion", "Phil Tucker"),
        ("Mage Errant", "John Bierce"),
        ("The Path of Ascension", "C. Mantis"),
        ("Beware of Chicken", "Casfaril"),
        ("Mark of the Fool", "J.M. Clarke"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # ACADEMY FANTASY (~20)
    # ═══════════════════════════════════════════════════════════════════
    "Academy Fantasy": [
        ("The Name of the Wind", "Patrick Rothfuss"),
        ("The Wise Man's Fear", "Patrick Rothfuss"),
        ("Vita Nostra", "Sergey Dyachenko"),
        ("The Gate of the Feral Gods", "Matt Dinniman"),
        ("The Atlas Six", "Olivie Blake"),
        ("Babel", "R.F. Kuang"),
        ("The Will of the Many", "James Islington"),
        ("The Rage of Dragons", "Evan Winter"),
        ("The Rithmatist", "Brandon Sanderson"),
        ("The Magicians", "Lev Grossman"),
        ("The Magician King", "Lev Grossman"),
        ("A Deadly Education", "Naomi Novik"),
        ("The Last Graduate", "Naomi Novik"),
        ("Poison Study", "Maria V. Snyder"),
        ("Magic Study", "Maria V. Snyder"),
        ("Carry On", "Rainbow Rowell"),
        ("Wayward Son", "Rainbow Rowell"),
        ("The Scholomance", "R. Lee Smith"),
        ("The Truce of Twilight", "Rachel Neumeier"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # MILITARY FANTASY (~20)
    # ═══════════════════════════════════════════════════════════════════
    "Military Fantasy": [
        ("The Black Company", "Glen Cook"),
        ("Shadows Linger", "Glen Cook"),
        ("The Red Knight", "Miles Cameron"),
        ("The Fell Sword", "Miles Cameron"),
        ("The Thousand Names", "Django Wexler"),
        ("The Shadow Throne", "Django Wexler"),
        ("Promise of Blood", "Brian McClellan"),
        ("The Crimson Campaign", "Brian McClellan"),
        ("The Heroes", "Joe Abercrombie"),
        ("The Legion of Flame", "Anthony Ryan"),
        ("The Wolf's Call", "Anthony Ryan"),
        ("Guns of the Dawn", "Adrian Tchaikovsky"),
        ("The Tyrant Philosophers", "Adrian Tchaikovsky"),
        ("The Shadow of the Gods", "John Gwynne"),
        ("The Hunger of the Gods", "John Gwynne"),
        ("The Rage of Dragons", "Evan Winter"),
        ("The Pariah", "Anthony Ryan"),
        ("The Martyr", "Anthony Ryan"),
    ],
    # ═══════════════════════════════════════════════════════════════════
    # POLITICAL FANTASY (~25)
    # ═══════════════════════════════════════════════════════════════════
    "Political Fantasy": [
        ("A Game of Thrones", "George R.R. Martin"),
        ("A Clash of Kings", "George R.R. Martin"),
        ("The Traitor Baru Cormorant", "Seth Dickinson"),
        ("The Monster Baru Cormorant", "Seth Dickinson"),
        ("The Goblin Emperor", "Katherine Addison"),
        ("The Angel of the Crows", "Katherine Addison"),
        ("The City of Brass", "Shannon Chakraborty"),
        ("The Kingdom of Copper", "Shannon Chakraborty"),
        ("The Grace of Kings", "Ken Liu"),
        ("The Wall of Storms", "Ken Liu"),
        ("She Who Became the Sun", "Shelley Parker-Chan"),
        ("The Jasmine Throne", "Tasha Suri"),
        ("The Priory of the Orange Tree", "Samantha Shannon"),
        ("The Queen of the Tearling", "Erika Johansen"),
        ("The Invasion of the Tearling", "Erika Johansen"),
        ("The Farseer: Assassin's Apprentice", "Robin Hobb"),
        ("The Farseer: Royal Assassin", "Robin Hobb"),
        ("Tigana", "Guy Gavriel Kay"),
        ("Under Heaven", "Guy Gavriel Kay"),
        ("The Lions of Al-Rassan", "Guy Gavriel Kay"),
    ],
    # ── Dragon Riders (thin cluster expansion) ────────────────────────────
    "Dragon Riders": [
        ("Fourth Wing", "Rebecca Yarros"),
        ("Iron Flame", "Rebecca Yarros"),
        ("Eragon", "Christopher Paolini"),
        ("Eldest", "Christopher Paolini"),
        ("Dragonflight", "Anne McCaffrey"),
        ("Dragonquest", "Anne McCaffrey"),
        ("His Majesty's Dragon", "Naomi Novik"),
        ("Throne of Jade", "Naomi Novik"),
        ("Dragon Keeper", "Robin Hobb"),
        ("Dragon Haven", "Robin Hobb"),
        ("The Dragonbone Chair", "Tad Williams"),
        ("Stone of Farewell", "Tad Williams"),
        ("Joust", "Mercedes Lackey"),
        ("Alta", "Mercedes Lackey"),
        ("A Natural History of Dragons", "Marie Brennan"),
        ("The Tropic of Serpents", "Marie Brennan"),
        ("Seraphina", "Rachel Hartman"),
        ("Shadow Scale", "Rachel Hartman"),
        ("The Fire Within", "Chris d'Lacey"),
        ("Icefire", "Chris d'Lacey"),
    ],
    # ── Pirate Fantasy (thin cluster expansion) ────────────────────────────
    "Pirate Fantasy": [
        ("The Adventures of Amina al-Sirafi", "Shannon Chakraborty"),
        ("The Bone Ships", "R.J. Barker"),
        ("Call of the Bone Ships", "R.J. Barker"),
        ("On Stranger Tides", "Tim Powers"),
        ("Red Seas Under Red Skies", "Scott Lynch"),
        ("Dark Water Daughter", "H.M. Long"),
        ("The Mermaid the Witch and the Sea", "Maggie Tokuda-Hall"),
        ("The Abyss Surrounds Us", "Emily Skrutskie"),
        ("The Edge of the Abyss", "Emily Skrutskie"),
        ("Daughter of the Pirate King", "Tricia Levenseller"),
        ("Daughter of the Siren Queen", "Tricia Levenseller"),
        ("Fable", "Adrienne Young"),
        ("Namesake", "Adrienne Young"),
        ("The Girl from Everywhere", "Heidi Heilig"),
        ("The Ship Beyond Time", "Heidi Heilig"),
        ("To Kill a Kingdom", "Alexandra Christo"),
        ("Into the Drowning Deep", "Mira Grant"),
        ("Seafire", "Natalie C. Parker"),
        ("Steel Tide", "Natalie C. Parker"),
        ("Tress of the Emerald Sea", "Brandon Sanderson"),
    ],
    # ── LitRPG / Progression Fantasy (thin cluster expansion) ───────────
    "LitRPG": [
        ("Dungeon Crawler Carl", "Matt Dinniman"),
        ("Carl's Doomsday Scenario", "Matt Dinniman"),
        ("He Who Fights with Monsters", "Shirtaloon"),
        ("Defiance of the Fall", "TheFirstDefier"),
        ("The Primal Hunter", "Zogarth"),
        ("Awaken Online: Catharsis", "Travis Bagwell"),
        ("Awaken Online: Precipice", "Travis Bagwell"),
        ("The Wandering Inn", "Pirateaba"),
        ("Sufficiently Advanced Magic", "Andrew Rowe"),
        ("On the Shoulders of Titans", "Andrew Rowe"),
        ("Cradle: Unsouled", "Will Wight"),
        ("Cradle: Soulsmith", "Will Wight"),
        ("Mother of Learning", "Domagoj Kurmaic"),
        ("The Completionist Chronicles: Ritualist", "Dakota Krout"),
        ("Regicide", "Dakota Krout"),
        ("Life Reset", "Shemer Kuznits"),
        ("New Era Online", "Shemer Kuznits"),
        ("The Land: Founding", "Aleron Kong"),
        ("The Land: Raiders", "Aleron Kong"),
        ("Ascend Online", "Luke Chmilenko"),
    ],
}
