"""
Historical Fiction Microtrope Seed Catalog — ~220 books across 13 clusters.
Strategy: max 2 books per author, deep author spread within clusters.
Epic decoupled from setting — scale via Epic node, period via Ancient/Medieval World.
"""

HISTORICAL_MICROTROPE_CLUSTERS = {
    # ── Ancient World (Greco-Roman, Egyptian, Biblical) ────────────────────
    "Ancient World": [
        ("The Song of Achilles", "Madeline Miller"),
        ("Circe", "Madeline Miller"),
        ("I, Claudius", "Robert Graves"),
        ("Claudius the God", "Robert Graves"),
        ("The Persian Boy", "Mary Renault"),
        ("Fire from Heaven", "Mary Renault"),
        ("Augustus", "John Williams"),
        ("Memoirs of Hadrian", "Marguerite Yourcenar"),
        ("The Egyptian", "Mika Waltari"),
        ("The Roman", "Mika Waltari"),
        ("Julian", "Gore Vidal"),
        ("Creation", "Gore Vidal"),
        ("The Gates of Fire", "Steven Pressfield"),
        ("Tides of War", "Steven Pressfield"),
        ("Lavinia", "Ursula K. Le Guin"),
        ("The Silence of the Girls", "Pat Barker"),
        ("Spartacus", "Howard Fast"),
        ("Cleopatra's Daughter", "Michelle Moran"),
        ("Nefertiti", "Michelle Moran"),
        ("The Red Tent", "Anita Diamant"),
    ],
    # ── Medieval World (Dark Ages through Renaissance) ─────────────────────
    "Medieval World": [
        ("The Pillars of the Earth", "Ken Follett"),
        ("World Without End", "Ken Follett"),
        ("Wolf Hall", "Hilary Mantel"),
        ("Bring Up the Bodies", "Hilary Mantel"),
        ("The Name of the Rose", "Umberto Eco"),
        ("Baudolino", "Umberto Eco"),
        ("The Last Kingdom", "Bernard Cornwell"),
        ("The Winter King", "Bernard Cornwell"),
        ("Cathedral of the Sea", "Ildefonso Falcones"),
        ("The Land Beyond the Sea", "Sharon Kay Penman"),
        ("The Sunne in Splendour", "Sharon Kay Penman"),
        ("Hild", "Nicola Griffith"),
        ("Matrix", "Lauren Groff"),
        ("Hamnet", "Maggie O'Farrell"),
        ("The Marriage Portrait", "Maggie O'Farrell"),
        ("The Mercies", "Kiran Millwood Hargrave"),
        ("The Dance Tree", "Kiran Millwood Hargrave"),
        ("The Western Wind", "Samantha Harvey"),
        ("Company of Liars", "Karen Maitland"),
        ("The Owl Killers", "Karen Maitland"),
    ],
    # ── Victorian / 19th Century ───────────────────────────────────────────
    "Victorian / 19th Century": [
        ("Fingersmith", "Sarah Waters"),
        ("Tipping the Velvet", "Sarah Waters"),
        ("The Crimson Petal and the White", "Michel Faber"),
        ("The Luminaries", "Eleanor Catton"),
        ("The French Lieutenant's Woman", "John Fowles"),
        ("Possession", "A.S. Byatt"),
        ("The Children's Book", "A.S. Byatt"),
        ("Alias Grace", "Margaret Atwood"),
        ("The Essex Serpent", "Sarah Perry"),
        ("Melmoth", "Sarah Perry"),
        ("The Wonder", "Emma Donoghue"),
        ("The Pull of the Stars", "Emma Donoghue"),
        ("Burial Rites", "Hannah Kent"),
        ("The Good People", "Hannah Kent"),
        ("Year of Wonders", "Geraldine Brooks"),
        ("March", "Geraldine Brooks"),
        ("The Miniaturist", "Jessie Burton"),
        ("The Muse", "Jessie Burton"),
        ("The Observations", "Jane Harris"),
        ("Gillespie and I", "Jane Harris"),
    ],
    # ── War Fiction ────────────────────────────────────────────────────────
    "War Fiction": [
        ("All Quiet on the Western Front", "Erich Maria Remarque"),
        ("The Road Back", "Erich Maria Remarque"),
        ("A Farewell to Arms", "Ernest Hemingway"),
        ("For Whom the Bell Tolls", "Ernest Hemingway"),
        ("Birdsong", "Sebastian Faulks"),
        ("Charlotte Gray", "Sebastian Faulks"),
        ("Atonement", "Ian McEwan"),
        ("The Narrow Road to the Deep North", "Richard Flanagan"),
        ("The Nightingale", "Kristin Hannah"),
        ("The Great Alone", "Kristin Hannah"),
        ("Matterhorn", "Karl Marlantes"),
        ("The Thin Red Line", "James Jones"),
        ("From Here to Eternity", "James Jones"),
        ("Regeneration", "Pat Barker"),
        ("Life After Life", "Kate Atkinson"),
        ("A God in Ruins", "Kate Atkinson"),
        ("The Book Thief", "Markus Zusak"),
        ("All the Light We Cannot See", "Anthony Doerr"),
        ("The English Patient", "Michael Ondaatje"),
        ("Captain Corelli's Mandolin", "Louis de Bernieres"),
    ],
    # ── American Historical (Western, Civil War, 20th C) ───────────────────
    "American Historical": [
        ("Lonesome Dove", "Larry McMurtry"),
        ("Streets of Laredo", "Larry McMurtry"),
        ("True Grit", "Charles Portis"),
        ("Cold Mountain", "Charles Frazier"),
        ("Varina", "Charles Frazier"),
        ("News of the World", "Paulette Jiles"),
        ("Simon the Fiddler", "Paulette Jiles"),
        ("The Underground Railroad", "Colson Whitehead"),
        ("The Nickel Boys", "Colson Whitehead"),
        ("The Known World", "Edward P. Jones"),
        ("Ragtime", "E.L. Doctorow"),
        ("Billy Bathgate", "E.L. Doctorow"),
        ("Angle of Repose", "Wallace Stegner"),
        ("Crossing to Safety", "Wallace Stegner"),
        ("A Thousand Acres", "Jane Smiley"),
        ("Some Luck", "Jane Smiley"),
        ("The Son", "Philipp Meyer"),
        ("Doc", "Mary Doria Russell"),
        ("The Sisters Brothers", "Patrick deWitt"),
        ("In the Distance", "Hernan Diaz"),
    ],
    # ── Colonial / Postcolonial Historical ─────────────────────────────────
    "Colonial / Postcolonial": [
        ("Things Fall Apart", "Chinua Achebe"),
        ("Arrow of God", "Chinua Achebe"),
        ("The Poisonwood Bible", "Barbara Kingsolver"),
        ("The Lacuna", "Barbara Kingsolver"),
        ("Wide Sargasso Sea", "Jean Rhys"),
        ("The Siege of Krishnapur", "J.G. Farrell"),
        ("Troubles", "J.G. Farrell"),
        ("Midnight's Children", "Salman Rushdie"),
        ("Sea of Poppies", "Amitav Ghosh"),
        ("The Glass Palace", "Amitav Ghosh"),
        ("Half of a Yellow Sun", "Chimamanda Ngozi Adichie"),
        ("The Garden of Evening Mists", "Tan Twan Eng"),
        ("The Gift of Rain", "Tan Twan Eng"),
        ("The Book of Negroes", "Lawrence Hill"),
        ("Washington Black", "Esi Edugyan"),
        ("The Narrow Road to the Deep North", "Richard Flanagan"),
        ("Burmese Days", "George Orwell"),
        ("A Passage to India", "E.M. Forster"),
        ("The Piano Tuner", "Daniel Mason"),
        ("The Orphan Master's Son", "Adam Johnson"),
    ],
    # ── Biographical Fiction ───────────────────────────────────────────────
    "Biographical Fiction": [
        ("The Paris Wife", "Paula McLain"),
        ("Circling the Sun", "Paula McLain"),
        ("Loving Frank", "Nancy Horan"),
        ("The Aviator's Wife", "Melanie Benjamin"),
        ("The Swans of Fifth Avenue", "Melanie Benjamin"),
        ("The Only Woman in the Room", "Marie Benedict"),
        ("Lady Clementine", "Marie Benedict"),
        ("The Other Boleyn Girl", "Philippa Gregory"),
        ("The White Queen", "Philippa Gregory"),
        ("The Agony and the Ecstasy", "Irving Stone"),
        ("Lust for Life", "Irving Stone"),
        ("The Last Days of Night", "Graham Moore"),
        ("The Hours", "Michael Cunningham"),
        ("Z: A Novel of Zelda Fitzgerald", "Therese Anne Fowler"),
        ("A Well-Behaved Woman", "Therese Anne Fowler"),
        ("I Was Anastasia", "Ariel Lawhon"),
        ("Code Name Helene", "Ariel Lawhon"),
        ("The Alice Network", "Kate Quinn"),
        ("The Huntress", "Kate Quinn"),
        ("The Girl with a Pearl Earring", "Tracy Chevalier"),
    ],
    # ── Historical Mystery ─────────────────────────────────────────────────
    "Historical Mystery": [
        ("The Alienist", "Caleb Carr"),
        ("The Angel of Darkness", "Caleb Carr"),
        ("Maisie Dobbs", "Jacqueline Winspear"),
        ("Birds of a Feather", "Jacqueline Winspear"),
        ("A Morbid Taste for Bones", "Ellis Peters"),
        ("One Corpse Too Many", "Ellis Peters"),
        ("The Daughter of Time", "Josephine Tey"),
        ("Brat Farrar", "Josephine Tey"),
        ("The Beekeeper's Apprentice", "Laurie R. King"),
        ("A Monstrous Regiment of Women", "Laurie R. King"),
        ("The Sweetness at the Bottom of the Pie", "Alan Bradley"),
        ("The Weed That Strings the Hangman's Bag", "Alan Bradley"),
        ("The Widows of Malabar Hill", "Sujata Massey"),
        ("The Satapur Moonstone", "Sujata Massey"),
        ("A Rising Man", "Abir Mukherjee"),
        ("A Necessary Evil", "Abir Mukherjee"),
        ("The Janissary Tree", "Jason Goodwin"),
        ("The Snake Stone", "Jason Goodwin"),
        ("Mistress of the Art of Death", "Ariana Franklin"),
        ("The Serpent's Tale", "Ariana Franklin"),
    ],
    # ── Alternate History ──────────────────────────────────────────────────
    "Alternate History": [
        ("The Man in the High Castle", "Philip K. Dick"),
        ("The Plot Against America", "Philip Roth"),
        ("Fatherland", "Robert Harris"),
        ("Munich", "Robert Harris"),
        ("11/22/63", "Stephen King"),
        ("The Years of Rice and Salt", "Kim Stanley Robinson"),
        ("The Yiddish Policemen's Union", "Michael Chabon"),
        ("Underground Airlines", "Ben H. Winters"),
        ("Making History", "Stephen Fry"),
        ("The Guns of the South", "Harry Turtledove"),
        ("How Few Remain", "Harry Turtledove"),
        ("Dominion", "C.J. Sansom"),
        ("SS-GB", "Len Deighton"),
        ("Farthing", "Jo Walton"),
        ("Ha'penny", "Jo Walton"),
        ("The Eyre Affair", "Jasper Fforde"),
        ("Jonathan Strange & Mr Norrell", "Susanna Clarke"),
        ("The Power", "Naomi Alderman"),
        ("The Sewing Machine", "Natalie Fergie"),
        ("The Calculating Stars", "Mary Robinette Kowal"),
    ],
    # ── Asian Historical ───────────────────────────────────────────────────
    "Asian Historical": [
        ("Pachinko", "Min Jin Lee"),
        ("Memoirs of a Geisha", "Arthur Golden"),
        ("Shogun", "James Clavell"),
        ("Tai-Pan", "James Clavell"),
        ("The Good Earth", "Pearl S. Buck"),
        ("Sons", "Pearl S. Buck"),
        ("Snow Flower and the Secret Fan", "Lisa See"),
        ("Shanghai Girls", "Lisa See"),
        ("The Girl Who Wrote Loneliness", "Kyung-Sook Shin"),
        ("Please Look After Mom", "Kyung-Sook Shin"),
        ("Human Acts", "Han Kang"),
        ("The Sympathizer", "Viet Thanh Nguyen"),
        ("The Kitchen God's Wife", "Amy Tan"),
        ("The Bonesetter's Daughter", "Amy Tan"),
        ("The Makioka Sisters", "Junichiro Tanizaki"),
        ("Silence", "Shusaku Endo"),
        ("The Samurai", "Shusaku Endo"),
        ("When the Emperor Was Divine", "Julie Otsuka"),
        ("The Buddha in the Attic", "Julie Otsuka"),
        ("The House of the Spirits", "Isabel Allende"),
    ],
    # ── African / Middle Eastern Historical ────────────────────────────────
    "African / Middle Eastern": [
        ("Homegoing", "Yaa Gyasi"),
        ("Transcendent Kingdom", "Yaa Gyasi"),
        ("Palace Walk", "Naguib Mahfouz"),
        ("Palace of Desire", "Naguib Mahfouz"),
        ("The Map of Love", "Ahdaf Soueif"),
        ("In the Country of Men", "Hisham Matar"),
        ("Anatomy of a Disappearance", "Hisham Matar"),
        ("Season of Migration to the North", "Tayeb Salih"),
        ("The Wedding of Zein", "Tayeb Salih"),
        ("Cutting for Stone", "Abraham Verghese"),
        ("The Covenant of Water", "Abraham Verghese"),
        ("A Fine Balance", "Rohinton Mistry"),
        ("Family Matters", "Rohinton Mistry"),
        ("The Kite Runner", "Khaled Hosseini"),
        ("A Thousand Splendid Suns", "Khaled Hosseini"),
        ("The Moor's Account", "Laila Lalami"),
        ("The Other Americans", "Laila Lalami"),
        ("We Need New Names", "NoViolet Bulawayo"),
        ("The Dragonfly Sea", "Yvonne Adhiambo Owuor"),
        ("Dust", "Yvonne Adhiambo Owuor"),
    ],
    # ── Historical Adventure ───────────────────────────────────────────────
    "Historical Adventure": [
        ("The Three Musketeers", "Alexandre Dumas"),
        ("The Count of Monte Cristo", "Alexandre Dumas"),
        ("The Sea Wolf", "Jack London"),
        ("White Fang", "Jack London"),
        ("King Solomon's Mines", "H. Rider Haggard"),
        ("She", "H. Rider Haggard"),
        ("Treasure Island", "Robert Louis Stevenson"),
        ("Kidnapped", "Robert Louis Stevenson"),
        ("Captain Blood", "Rafael Sabatini"),
        ("Scaramouche", "Rafael Sabatini"),
        ("The Prisoner of Zenda", "Anthony Hope"),
        ("Beau Geste", "P.C. Wren"),
        ("The Lost City of Z", "David Grann"),
        ("The Wager", "David Grann"),
        ("River of Doubt", "Candice Millard"),
        ("Destiny of the Republic", "Candice Millard"),
        ("Endurance", "Alfred Lansing"),
        ("Into the Heart of the Sea", "Nathaniel Philbrick"),
        ("In the Kingdom of Ice", "Hampton Sides"),
        ("The Great Train Robbery", "Michael Crichton"),
    ],
    # ── Gaslamp / Historical Fantasy ───────────────────────────────────────
    "Gaslamp / Historical Fantasy": [
        ("Jonathan Strange & Mr Norrell", "Susanna Clarke"),
        ("The Golem and the Jinni", "Helene Wecker"),
        ("The Hidden Palace", "Helene Wecker"),
        ("The Bear and the Nightingale", "Katherine Arden"),
        ("The Girl in the Tower", "Katherine Arden"),
        ("Uprooted", "Naomi Novik"),
        ("Spinning Silver", "Naomi Novik"),
        ("The Once and Future Witches", "Alix E. Harrow"),
        ("The Ten Thousand Doors of January", "Alix E. Harrow"),
        ("A Discovery of Witches", "Deborah Harkness"),
        ("Shadow of Night", "Deborah Harkness"),
        ("The Invisible Life of Addie LaRue", "V.E. Schwab"),
        ("The Toymakers", "Robert Dinsdale"),
        ("The Watchmaker of Filigree Street", "Natasha Pulley"),
        ("The Bedlam Stacks", "Natasha Pulley"),
        ("The Glass Woman", "Caroline Lea"),
        ("The Metal Heart", "Caroline Lea"),
        ("The Corset", "Laura Purcell"),
        ("The Silent Companions", "Laura Purcell"),
        ("The Mermaid and Mrs Hancock", "Imogen Hermes Gowar"),
    ],
}
