"""
Horror Microtrope Seed Catalog — ~300 books across 9 clusters.
Strategy: deep author coverage per cluster, max 15-20 books per cluster.
"""

HORROR_MICROTROPE_CLUSTERS = {
    # ── Haunted House + Dread & Atmosphere + Supernatural ──────────────────
    "Haunted House + Dread": [
        ("The Haunting of Hill House", "Shirley Jackson"),
        ("We Have Always Lived in the Castle", "Shirley Jackson"),
        ("The Shining", "Stephen King"),
        ("The Woman in Black", "Susan Hill"),
        ("Hell House", "Richard Matheson"),
        ("Burnt Offerings", "Robert Marasco"),
        ("The Little Stranger", "Sarah Waters"),
        ("The Turn of the Screw", "Henry James"),
        ("The Elementals", "Michael McDowell"),
        ("The Sentinel", "Jeffrey Konvitz"),
        ("Kill Creek", "Scott Thomas"),
        ("The Good House", "Tananarive Due"),
        ("The Reformatory", "Tananarive Due"),
        ("The September House", "Carissa Orlando"),
        ("Just Like Home", "Sarah Gailey"),
        ("Gallows Hill", "Darcy Coates"),
        ("The Carrow Haunt", "Darcy Coates"),
        ("The Invited", "Jennifer McMahon"),
        ("The Winter People", "Jennifer McMahon"),
        ("The Nightingale", "Kristin Hannah"),
    ],
    # ── Gothic Horror + Historical + Dread ─────────────────────────────────
    "Gothic Horror + Historical": [
        ("Mexican Gothic", "Silvia Moreno-Garcia"),
        ("Dracula", "Bram Stoker"),
        ("Frankenstein", "Mary Shelley"),
        ("The Picture of Dorian Gray", "Oscar Wilde"),
        ("Wuthering Heights", "Emily Bronte"),
        ("Jane Eyre", "Charlotte Bronte"),
        ("Rebecca", "Daphne du Maurier"),
        ("My Cousin Rachel", "Daphne du Maurier"),
        ("Jamaica Inn", "Daphne du Maurier"),
        ("The Castle of Otranto", "Horace Walpole"),
        ("The Monk", "Matthew Lewis"),
        ("Carmilla", "Sheridan Le Fanu"),
        ("Uncle Silas", "Sheridan Le Fanu"),
        ("The Woman in White", "Wilkie Collins"),
        ("The Mysteries of Udolpho", "Ann Radcliffe"),
        ("The Italian", "Ann Radcliffe"),
        ("Melmoth the Wanderer", "Charles Maturin"),
        ("The Phantom of the Opera", "Gaston Leroux"),
        ("Sarah Canary", "Karen Joy Fowler"),
        ("The Death of Jane Lawrence", "Caitlin Starling"),
    ],
    # ── Quiet Horror + Psychological + Existential ─────────────────────────
    "Quiet Horror + Psychological": [
        ("Songs of a Dead Dreamer", "Thomas Ligotti"),
        ("Grimscribe", "Thomas Ligotti"),
        ("Teatro Grottesco", "Thomas Ligotti"),
        ("The Conspiracy Against the Human Race", "Thomas Ligotti"),
        ("My Work Is Not Yet Done", "Thomas Ligotti"),
        ("The Frolic", "Thomas Ligotti"),
        ("The Dark Descent", "David G. Hartwell"),
        ("Ghost Story", "Peter Straub"),
        ("Floating Dragon", "Peter Straub"),
        ("Shadowland", "Peter Straub"),
        ("If You Could See Me Now", "Peter Straub"),
        ("The Girl Who Loved Tom Gordon", "Stephen King"),
        ("Revival", "Stephen King"),
        ("The Fisherman", "John Langan"),
        ("The Wide Carnivorous Sky", "John Langan"),
        ("House of Windows", "John Langan"),
        ("The Ghost Sequences", "A.C. Wise"),
        ("North American Lake Monsters", "Nathan Ballingrud"),
        ("Wounds", "Nathan Ballingrud"),
        ("A Lush and Seething Hell", "John Hornor Jacobs"),
    ],
    # ── Weird Fiction + Reality Distortion + Cosmic ────────────────────────
    "Weird Fiction + Reality": [
        ("Annihilation", "Jeff VanderMeer"),
        ("Authority", "Jeff VanderMeer"),
        ("Acceptance", "Jeff VanderMeer"),
        ("Borne", "Jeff VanderMeer"),
        ("City of Saints and Madmen", "Jeff VanderMeer"),
        ("House of Leaves", "Mark Z. Danielewski"),
        ("The Raw Shark Texts", "Steven Hall"),
        ("The Cipher", "Kathe Koja"),
        ("Strange Highways", "Kathe Koja"),
        ("Skin", "Kathe Koja"),
        ("The Course of the Heart", "M. John Harrison"),
        ("Light", "M. John Harrison"),
        ("Viriconium", "M. John Harrison"),
        ("Negative Space", "B.R. Yeager"),
        ("Amygdalatropolis", "B.R. Yeager"),
        ("The Grip of It", "Jac Jemc"),
        ("Fever Dream", "Samanta Schweblin"),
        ("Little Eyes", "Samanta Schweblin"),
        ("The Houseguest", "Amparo Davila"),
        ("Tender Is the Flesh", "Agustina Bazterrica"),
    ],
    # ── Domestic Horror + Family + Psychological ───────────────────────────
    "Domestic Horror + Family": [
        ("Rosemary's Baby", "Ira Levin"),
        ("The Stepford Wives", "Ira Levin"),
        ("The Boys from Brazil", "Ira Levin"),
        ("A Kiss Before Dying", "Ira Levin"),
        ("The Push", "Ashley Audrain"),
        ("The Whispers", "Ashley Audrain"),
        ("The Perfect Nanny", "Leila Slimani"),
        ("Adele", "Leila Slimani"),
        ("The Changeling", "Victor LaValle"),
        ("The Devil in Silver", "Victor LaValle"),
        ("The Ballad of Black Tom", "Victor LaValle"),
        ("Lone Women", "Victor LaValle"),
        ("The Drowning Kind", "Jennifer McMahon"),
        ("The Children on the Hill", "Jennifer McMahon"),
        ("Baby Teeth", "Zoje Stage"),
        ("Wonderland", "Zoje Stage"),
        ("Getaway", "Zoje Stage"),
        ("The Book of Accidents", "Chuck Wendig"),
        ("Sundial", "Catriona Ward"),
        ("The Last House on Needless Street", "Catriona Ward"),
    ],
    # ── Folk Horror + Isolated + Systemic ──────────────────────────────────
    "Folk Horror + Isolated": [
        ("The Ritual", "Adam Nevill"),
        ("Last Days", "Adam Nevill"),
        ("No One Gets Out Alive", "Adam Nevill"),
        ("The Reddening", "Adam Nevill"),
        ("Cunning Folk", "Adam Nevill"),
        ("Harvest Home", "Thomas Tryon"),
        ("The Other", "Thomas Tryon"),
        ("Harvest", "Sam Mariano"),
        ("The Loney", "Andrew Michael Hurley"),
        ("Devil's Day", "Andrew Michael Hurley"),
        ("Starve Acre", "Andrew Michael Hurley"),
        ("The Twisted Ones", "T. Kingfisher"),
        ("The Hollow Places", "T. Kingfisher"),
        ("Nettle & Bone", "T. Kingfisher"),
        ("Experimental Film", "Gemma Files"),
        ("Wylding Hall", "Elizabeth Hand"),
        ("The Watchers", "A.M. Shine"),
        ("Pine", "Francine Toon"),
        ("Mongrels", "Stephen Graham Jones"),
        ("My Heart Is a Chainsaw", "Stephen Graham Jones"),
    ],
    # ── Supernatural Horror + Cosmic + Occult ──────────────────────────────
    "Supernatural + Cosmic Horror": [
        ("The Exorcist", "William Peter Blatty"),
        ("Legion", "William Peter Blatty"),
        ("The Omen", "David Seltzer"),
        ("Heart-Shaped Box", "Joe Hill"),
        ("Horns", "Joe Hill"),
        ("NOS4A2", "Joe Hill"),
        ("The Fireman", "Joe Hill"),
        ("Strange Weather", "Joe Hill"),
        ("Full Throttle", "Joe Hill"),
        ("The Strain", "Guillermo del Toro"),
        ("The Fall", "Guillermo del Toro"),
        ("The Night Eternal", "Guillermo del Toro"),
        ("The Cabin at the End of the World", "Paul Tremblay"),
        ("A Head Full of Ghosts", "Paul Tremblay"),
        ("Disappearance at Devil's Rock", "Paul Tremblay"),
        ("Growing Things", "Paul Tremblay"),
        ("The Pallbearers Club", "Paul Tremblay"),
        ("The Library at Mount Char", "Scott Hawkins"),
        ("American Elsewhere", "Robert Jackson Bennett"),
        ("The Southern Book Club's Guide to Slaying Vampires", "Grady Hendrix"),
    ],
    # ── Body Horror + Survival + Transformation ────────────────────────────
    "Body Horror + Survival": [
        ("The Troop", "Nick Cutter"),
        ("The Deep", "Nick Cutter"),
        ("Little Heaven", "Nick Cutter"),
        ("The Acolyte", "Nick Cutter"),
        ("The Breach", "Nick Cutter"),
        ("Infected", "Scott Sigler"),
        ("Contagious", "Scott Sigler"),
        ("Pandemic", "Scott Sigler"),
        ("The Ruins", "Scott Smith"),
        ("The Descent", "Jeff Long"),
        ("Deeper", "Jeff Long"),
        ("The Ritual", "Adam Nevill"),
        ("Horrorstor", "Grady Hendrix"),
        ("My Best Friend's Exorcism", "Grady Hendrix"),
        ("The Final Girl Support Group", "Grady Hendrix"),
        ("How to Sell a Haunted House", "Grady Hendrix"),
        ("We Sold Our Souls", "Grady Hendrix"),
        ("Cujo", "Stephen King"),
        ("Pet Sematary", "Stephen King"),
        ("Misery", "Stephen King"),
    ],
    # ── Slasher + Survival + Apocalyptic Horror ────────────────────────────
    "Slasher + Survival Horror": [
        ("The Silence of the Lambs", "Thomas Harris"),
        ("Red Dragon", "Thomas Harris"),
        ("I'm Thinking of Ending Things", "Iain Reid"),
        ("Foe", "Iain Reid"),
        ("The Summer I Died", "Ryan C. Thomas"),
        ("Off Season", "Jack Ketchum"),
        ("The Girl Next Door", "Jack Ketchum"),
        ("Offspring", "Jack Ketchum"),
        ("The Killing Kind", "Bryan Smith"),
        ("The Summer Is Ended", "Ryan C. Thomas"),
        ("The Cabin at the End of the World", "Paul Tremblay"),
        ("Survivor Song", "Paul Tremblay"),
        ("Suffer the Children", "Craig DiLouie"),
        ("Episode Thirteen", "Craig DiLouie"),
        ("The Loop", "Jeremy Robert Johnson"),
        ("Skullcrack City", "Jeremy Robert Johnson"),
        ("The Dead Zone", "Stephen King"),
        ("Cell", "Stephen King"),
        ("The Stand", "Stephen King"),
        ("Under the Dome", "Stephen King"),
    ],
    # ── Vampire Horror (v2) ─────────────────────────────────────────────
    "Vampire Horror": [
        ("Dracula", "Bram Stoker"),
        ("Salem's Lot", "Stephen King"),
        ("Interview with the Vampire", "Anne Rice"),
        ("The Vampire Lestat", "Anne Rice"),
        ("Queen of the Damned", "Anne Rice"),
        ("The Tale of the Body Thief", "Anne Rice"),
        ("Memnoch the Devil", "Anne Rice"),
        ("Let the Right One In", "John Ajvide Lindqvist"),
        ("Handling the Undead", "John Ajvide Lindqvist"),
        ("Little Star", "John Ajvide Lindqvist"),
        ("I Am Legend", "Richard Matheson"),
        ("The Passage", "Justin Cronin"),
        ("The Twelve", "Justin Cronin"),
        ("The City of Mirrors", "Justin Cronin"),
        ("Fevre Dream", "George R.R. Martin"),
        ("NOS4A2", "Joe Hill"),
        ("The Lesser Dead", "Christopher Buehlman"),
        ("The Suicide Motor Club", "Christopher Buehlman"),
        ("Certain Dark Things", "Silvia Moreno-Garcia"),
        ("The Southern Book Club's Guide to Slaying Vampires", "Grady Hendrix"),
    ],
    # ── Monster Horror (v2) ──────────────────────────────────────────────
    "Monster Horror": [
        ("The Terror", "Dan Simmons"),
        ("Relic", "Douglas Preston"),
        ("Reliquary", "Douglas Preston"),
        ("The Cabinet of Curiosities", "Douglas Preston"),
        ("Still Life with Crows", "Douglas Preston"),
        ("Brimstone", "Douglas Preston"),
        ("Devolution", "Max Brooks"),
        ("Those Across the River", "Christopher Buehlman"),
        ("The Necromancer's House", "Christopher Buehlman"),
        ("The Only Good Indians", "Stephen Graham Jones"),
        ("My Heart Is a Chainsaw", "Stephen Graham Jones"),
        ("Don't Fear the Reaper", "Stephen Graham Jones"),
        ("The Descent", "Jeff Long"),
        ("The Troop", "Nick Cutter"),
        ("The Deep", "Nick Cutter"),
        ("Into the Drowning Deep", "Mira Grant"),
        ("Rolling in the Deep", "Mira Grant"),
        ("Clown in a Cornfield", "Adam Cesare"),
        ("Clown in a Cornfield 2", "Adam Cesare"),
        ("Stolen Tongues", "Felix Blackwell"),
    ],
    # ── Extreme Horror / Splatterpunk (v2) ───────────────────────────────
    "Extreme Horror": [
        ("Exquisite Corpse", "Poppy Z. Brite"),
        ("Drawing Blood", "Poppy Z. Brite"),
        ("Lost Souls", "Poppy Z. Brite"),
        ("The Bighead", "Edward Lee"),
        ("Header", "Edward Lee"),
        ("Full Brutal", "Kristopher Triana"),
        ("Gone to See the River Man", "Kristopher Triana"),
        ("And the Devil Cried", "Kristopher Triana"),
        ("Brother", "Ania Ahlborn"),
        ("The Devil Crept In", "Ania Ahlborn"),
        ("The Shuddering", "Ania Ahlborn"),
        ("The Girl Next Door", "Jack Ketchum"),
        ("Off Season", "Jack Ketchum"),
        ("The Resurrectionist", "Wrath James White"),
        ("Succulent Prey", "Wrath James White"),
        ("Population Zero", "Wrath James White"),
        ("Cows", "Matthew Stokoe"),
        ("Dead Inside", "Chandler Morrison"),
        ("Woom", "Duncan Ralston"),
        ("Tampa", "Alissa Nutting"),
    ],
    # ── Religious Horror (v2) ────────────────────────────────────────────
    "Religious Horror": [
        ("The Exorcist", "William Peter Blatty"),
        ("Legion", "William Peter Blatty"),
        ("Between Two Fires", "Christopher Buehlman"),
        ("Come Closer", "Sara Gran"),
        ("Seed", "Ania Ahlborn"),
        ("The Case Against Satan", "Ray Russell"),
        ("A Head Full of Ghosts", "Paul Tremblay"),
        ("The Last Days of Jack Sparks", "Jason Arnopp"),
        ("Ararat", "Christopher Golden"),
        ("The Pandora Room", "Christopher Golden"),
        ("Red Hill", "Christopher Golden"),
        ("The Ritual", "Adam Nevill"),
        ("Last Days", "Adam Nevill"),
        ("The Omen", "David Seltzer"),
        ("Rosemary's Baby", "Ira Levin"),
        ("The Wakening", "J.G. Faherty"),
        ("The Devil Rides Out", "Dennis Wheatley"),
        ("To the Devil a Daughter", "Dennis Wheatley"),
        ("The Hellbound Heart", "Clive Barker"),
        ("The Damnation Game", "Clive Barker"),
    ],
    # ── Maritime / Ocean Horror (v2) ─────────────────────────────────────
    "Maritime Horror": [
        ("Into the Drowning Deep", "Mira Grant"),
        ("Rolling in the Deep", "Mira Grant"),
        ("Dead Sea", "Tim Curran"),
        ("Dead Sea Chronicles", "Tim Curran"),
        ("Sphere", "Michael Crichton"),
        ("Jaws", "Peter Benchley"),
        ("The Deep", "Peter Benchley"),
        ("Beast", "Peter Benchley"),
        ("The Fisherman", "John Langan"),
        ("The Terror", "Dan Simmons"),
        ("The Abominable", "Dan Simmons"),
        ("The Deep", "Nick Cutter"),
        ("The Meg", "Steve Alten"),
        ("Into the Deep", "Megan Stockton"),
        ("Below", "Ryan Lockwood"),
        ("Something in the Water", "Catherine Steadman"),
        ("Hagfish", "Brian Hodge"),
        ("The Sea of Ash", "Scott Thomas"),
        ("The Black", "Paul E. Cooley"),
        ("Sacculina", "Philip Fracassi"),
    ],
    # ── Found Footage / Media Horror (v2) ────────────────────────────────
    "Found Footage Horror": [
        ("Night Film", "Marisha Pessl"),
        ("Special Topics in Calamity Physics", "Marisha Pessl"),
        ("Universal Harvester", "John Darnielle"),
        ("Devil House", "John Darnielle"),
        ("Wolf in White Van", "John Darnielle"),
        ("Experimental Film", "Gemma Files"),
        ("We Eat Our Own", "Kea Wilson"),
        ("The Last Final Girl", "Stephen Graham Jones"),
        ("Demon Theory", "Stephen Graham Jones"),
        ("The Remaking", "Clay McLeod Chapman"),
        ("Ghost Eaters", "Clay McLeod Chapman"),
        ("What Moves the Dead", "T. Kingfisher"),
        ("Episode Thirteen", "Craig DiLouie"),
        ("The Pallbearers Club", "Paul Tremblay"),
        ("House of Leaves", "Mark Z. Danielewski"),
        ("The Raw Shark Texts", "Steven Hall"),
        ("Tales from the Gas Station", "Jack Townsend"),
        ("The Sluts", "Dennis Cooper"),
        ("Scanlines", "Todd Keisling"),
        ("Penpal", "Dathan Auerbach"),
    ],
    # ── Southern Gothic Horror (v2) ──────────────────────────────────────
    "Southern Gothic": [
        ("Blackwater", "Michael McDowell"),
        ("The Elementals", "Michael McDowell"),
        ("Cold Moon Over Babylon", "Michael McDowell"),
        ("Gilded Needles", "Michael McDowell"),
        ("The Boatman's Daughter", "Andy Davidson"),
        ("In the Valley of the Sun", "Andy Davidson"),
        ("The Hollow Kind", "Andy Davidson"),
        ("Summer Sons", "Lee Mandelo"),
        ("The Bayou", "Arden Powell"),
        ("A Choir of Ill Children", "Tom Piccirilli"),
        ("November Mourns", "Tom Piccirilli"),
        ("The Good House", "Tananarive Due"),
        ("My Soul to Keep", "Tananarive Due"),
        ("The Reformatory", "Tananarive Due"),
        ("Those Across the River", "Christopher Buehlman"),
        ("Between Two Fires", "Christopher Buehlman"),
        ("The Southern Book Club's Guide to Slaying Vampires", "Grady Hendrix"),
        ("Beloved", "Toni Morrison"),
        ("Sing Unburied Sing", "Jesmyn Ward"),
        ("Sharp Objects", "Gillian Flynn"),
    ],
    # ── Arctic / Expedition Horror (v2) ──────────────────────────────────
    "Arctic Horror": [
        ("The Terror", "Dan Simmons"),
        ("The Abominable", "Dan Simmons"),
        ("Dark Matter", "Michelle Paver"),
        ("Thin Air", "Michelle Paver"),
        ("Wakenhyrst", "Michelle Paver"),
        ("Near the Bone", "Christina Henry"),
        ("The Hunger", "Alma Katsu"),
        ("The Deep", "Alma Katsu"),
        ("The Fervor", "Alma Katsu"),
        ("At the Mountains of Madness", "H.P. Lovecraft"),
        ("Who Goes There", "John W. Campbell"),
        ("The Thing", "Alan Dean Foster"),
        ("Icebound", "Dean Koontz"),
        ("Phantoms", "Dean Koontz"),
        ("The Abominable", "Dan Simmons"),
        ("Ararat", "Christopher Golden"),
        ("The White Road", "Sarah Lotz"),
        ("Bone White", "Ronald Malfi"),
        ("The Winter People", "Jennifer McMahon"),
        ("Snowblind", "Christopher Golden"),
    ],
    # ── Zombie / Infection Horror (v2) ───────────────────────────────────
    "Zombie Horror": [
        ("World War Z", "Max Brooks"),
        ("The Girl with All the Gifts", "M.R. Carey"),
        ("The Boy on the Bridge", "M.R. Carey"),
        ("Feed", "Mira Grant"),
        ("Deadline", "Mira Grant"),
        ("Blackout", "Mira Grant"),
        ("Zone One", "Colson Whitehead"),
        ("The Passage", "Justin Cronin"),
        ("The Twelve", "Justin Cronin"),
        ("Cell", "Stephen King"),
        ("The Stand", "Stephen King"),
        ("Suffer the Children", "Craig DiLouie"),
        ("The Infection", "Craig DiLouie"),
        ("The Fireman", "Joe Hill"),
        ("I Am Legend", "Richard Matheson"),
        ("The Rising", "Brian Keene"),
        ("City of the Dead", "Brian Keene"),
        ("The Fall", "Guillermo del Toro"),
        ("Contagion", "Erin Bowman"),
        ("Patient Zero", "Jonathan Maberry"),
    ],
    # ── Academic / Dark Academia Horror (v2) ─────────────────────────────
    "Dark Academia Horror": [
        ("Bunny", "Mona Awad"),
        ("Rouge", "Mona Awad"),
        ("All's Well", "Mona Awad"),
        ("Catherine House", "Elisabeth Thomas"),
        ("The Secret History", "Donna Tartt"),
        ("If We Were Villains", "M.L. Rio"),
        ("The Maidens", "Alex Michaelides"),
        ("Ninth House", "Leigh Bardugo"),
        ("Hell Bent", "Leigh Bardugo"),
        ("These Violent Delights", "Micah Nemerever"),
        ("The Atlas Six", "Olivie Blake"),
        ("The Library at Mount Char", "Scott Hawkins"),
        ("A Deadly Education", "Naomi Novik"),
        ("Vicious", "V.E. Schwab"),
        ("Plain Bad Heroines", "Emily M. Danforth"),
        ("The Girls Are All So Nice Here", "Laurie Elizabeth Flynn"),
        ("In My Dreams I Hold a Knife", "Ashley Winstead"),
        ("The Truants", "Kate Weinberg"),
        ("Black Chalk", "Christopher J. Yates"),
        ("The Cloisters", "Katy Hays"),
    ],
}
