"""
Literary Fiction Microtrope Seed Catalog — ~260 books across 13 clusters.
Strategy: author spread + register diversity across modernist, postcolonial,
autofiction, experimental, and historical literary traditions.
"""

LITERARY_MICROTROPE_CLUSTERS = {
    # ── Literary Fiction + Existentialism + Absurdist ─────────────────────
    "Existential + Absurdist": [
        ("The Stranger", "Albert Camus"),
        ("The Plague", "Albert Camus"),
        ("The Myth of Sisyphus", "Albert Camus"),
        ("Nausea", "Jean-Paul Sartre"),
        ("The Wall", "Jean-Paul Sartre"),
        ("Waiting for Godot", "Samuel Beckett"),
        ("Molloy", "Samuel Beckett"),
        ("Malone Dies", "Samuel Beckett"),
        ("The Trial", "Franz Kafka"),
        ("The Castle", "Franz Kafka"),
        ("The Metamorphosis", "Franz Kafka"),
        ("The Fall", "Albert Camus"),
        ("Notes from Underground", "Fyodor Dostoevsky"),
        ("The Unbearable Lightness of Being", "Milan Kundera"),
        ("The Joke", "Milan Kundera"),
        ("If on a Winter's Night a Traveler", "Italo Calvino"),
        ("Invisible Cities", "Italo Calvino"),
        ("Blindness", "Jose Saramago"),
        ("The Elephant's Journey", "Jose Saramago"),
        ("The Tartar Steppe", "Dino Buzzati"),
    ],
    # ── Bildungsroman + Coming of Age ────────────────────────────────────
    "Bildungsroman + Coming of Age": [
        ("A Little Life", "Hanya Yanagihara"),
        ("The People in the Trees", "Hanya Yanagihara"),
        ("Normal People", "Sally Rooney"),
        ("Conversations with Friends", "Sally Rooney"),
        ("Beautiful World Where Are You", "Sally Rooney"),
        ("The Catcher in the Rye", "J.D. Salinger"),
        ("Franny and Zooey", "J.D. Salinger"),
        ("To Kill a Mockingbird", "Harper Lee"),
        ("Go Set a Watchman", "Harper Lee"),
        ("A Portrait of the Artist as a Young Man", "James Joyce"),
        ("Middlesex", "Jeffrey Eugenides"),
        ("The Virgin Suicides", "Jeffrey Eugenides"),
        ("The Secret History", "Donna Tartt"),
        ("The Goldfinch", "Donna Tartt"),
        ("My Year of Rest and Relaxation", "Ottessa Moshfegh"),
        ("Eileen", "Ottessa Moshfegh"),
        ("The Idiot", "Elif Batuman"),
        ("Either/Or", "Elif Batuman"),
        ("The Interestings", "Meg Wolitzer"),
        ("Freedom", "Jonathan Franzen"),
    ],
    # ── Postcolonial Literature + Immigrant ──────────────────────────────
    "Postcolonial + Immigrant": [
        ("Things Fall Apart", "Chinua Achebe"),
        ("No Longer at Ease", "Chinua Achebe"),
        ("Arrow of God", "Chinua Achebe"),
        ("White Teeth", "Zadie Smith"),
        ("On Beauty", "Zadie Smith"),
        ("NW", "Zadie Smith"),
        ("Americanah", "Chimamanda Ngozi Adichie"),
        ("Half of a Yellow Sun", "Chimamanda Ngozi Adichie"),
        ("The Kite Runner", "Khaled Hosseini"),
        ("A Thousand Splendid Suns", "Khaled Hosseini"),
        ("Midnight's Children", "Salman Rushdie"),
        ("The Satanic Verses", "Salman Rushdie"),
        ("The God of Small Things", "Arundhati Roy"),
        ("The Ministry of Utmost Happiness", "Arundhati Roy"),
        ("Interpreter of Maladies", "Jhumpa Lahiri"),
        ("The Namesake", "Jhumpa Lahiri"),
        ("The Brief Wondrous Life of Oscar Wao", "Junot Diaz"),
        ("This Is How You Lose Her", "Junot Diaz"),
        ("Breath Eyes Memory", "Edwidge Danticat"),
        ("The Dew Breaker", "Edwidge Danticat"),
    ],
    # ── Family Saga + Magical Realism ────────────────────────────────────
    "Family Saga + Magical Realism": [
        ("One Hundred Years of Solitude", "Gabriel Garcia Marquez"),
        ("Love in the Time of Cholera", "Gabriel Garcia Marquez"),
        ("Chronicle of a Death Foretold", "Gabriel Garcia Marquez"),
        ("Beloved", "Toni Morrison"),
        ("Song of Solomon", "Toni Morrison"),
        ("Sula", "Toni Morrison"),
        ("The House of the Spirits", "Isabel Allende"),
        ("Eva Luna", "Isabel Allende"),
        ("Like Water for Chocolate", "Laura Esquivel"),
        ("The Inheritance of Loss", "Kiran Desai"),
        ("The Joy Luck Club", "Amy Tan"),
        ("The Kitchen God's Wife", "Amy Tan"),
        ("Pachinko", "Min Jin Lee"),
        ("Free Food for Millionaires", "Min Jin Lee"),
        ("The Vanishing Half", "Brit Bennett"),
        ("The Mothers", "Brit Bennett"),
        ("Homegoing", "Yaa Gyasi"),
        ("Transcendent Kingdom", "Yaa Gyasi"),
        ("Commonwealth", "Ann Patchett"),
        ("The Dutch House", "Ann Patchett"),
    ],
    # ── Campus Novel + Academic ──────────────────────────────────────────
    "Campus Novel + Academic": [
        ("The Secret History", "Donna Tartt"),
        ("If We Were Villains", "M.L. Rio"),
        ("Stoner", "John Williams"),
        ("Butcher's Crossing", "John Williams"),
        ("Lucky Jim", "Kingsley Amis"),
        ("The Old Devils", "Kingsley Amis"),
        ("On Beauty", "Zadie Smith"),
        ("The Marriage Plot", "Jeffrey Eugenides"),
        ("The Rules of Attraction", "Bret Easton Ellis"),
        ("Less Than Zero", "Bret Easton Ellis"),
        ("Possession", "A.S. Byatt"),
        ("The Children's Book", "A.S. Byatt"),
        ("Straight Man", "Richard Russo"),
        ("Empire Falls", "Richard Russo"),
        ("The Art of Fielding", "Chad Harbach"),
        ("Wonder Boys", "Michael Chabon"),
        ("The Amazing Adventures of Kavalier & Clay", "Michael Chabon"),
        ("Norwegian Wood", "Haruki Murakami"),
        ("Dear Committee Members", "Julie Schumacher"),
        ("The Shakespeare Requirement", "Julie Schumacher"),
    ],
    # ── War Literature + Historical ──────────────────────────────────────
    "War Literature + Historical": [
        ("All Quiet on the Western Front", "Erich Maria Remarque"),
        ("The Road Back", "Erich Maria Remarque"),
        ("A Farewell to Arms", "Ernest Hemingway"),
        ("For Whom the Bell Tolls", "Ernest Hemingway"),
        ("The Sun Also Rises", "Ernest Hemingway"),
        ("Slaughterhouse-Five", "Kurt Vonnegut"),
        ("Catch-22", "Joseph Heller"),
        ("Something Happened", "Joseph Heller"),
        ("The Things They Carried", "Tim O'Brien"),
        ("Going After Cacciato", "Tim O'Brien"),
        ("The Naked and the Dead", "Norman Mailer"),
        ("From Here to Eternity", "James Jones"),
        ("The Thin Red Line", "James Jones"),
        ("Birdsong", "Sebastian Faulks"),
        ("Charlotte Gray", "Sebastian Faulks"),
        ("Regeneration", "Pat Barker"),
        ("The Ghost Road", "Pat Barker"),
        ("Atonement", "Ian McEwan"),
        ("The Narrow Road to the Deep North", "Richard Flanagan"),
        ("Matterhorn", "Karl Marlantes"),
    ],
    # ── Modernist + Stream of Consciousness + Experimental ────────────────
    "Modernist + Experimental": [
        ("Mrs Dalloway", "Virginia Woolf"),
        ("To the Lighthouse", "Virginia Woolf"),
        ("The Waves", "Virginia Woolf"),
        ("Ulysses", "James Joyce"),
        ("Dubliners", "James Joyce"),
        ("The Sound and the Fury", "William Faulkner"),
        ("As I Lay Dying", "William Faulkner"),
        ("Absalom Absalom", "William Faulkner"),
        ("Infinite Jest", "David Foster Wallace"),
        ("The Pale King", "David Foster Wallace"),
        ("Gravity's Rainbow", "Thomas Pynchon"),
        ("The Crying of Lot 49", "Thomas Pynchon"),
        ("House of Leaves", "Mark Z. Danielewski"),
        ("If on a Winter's Night a Traveler", "Italo Calvino"),
        ("Pale Fire", "Vladimir Nabokov"),
        ("Lolita", "Vladimir Nabokov"),
        ("Tristram Shandy", "Laurence Sterne"),
        ("Hopscotch", "Julio Cortazar"),
        ("The Autumn of the Patriarch", "Gabriel Garcia Marquez"),
        ("JR", "William Gaddis"),
    ],
    # ── Autofiction + Introspective ──────────────────────────────────────
    "Autofiction + Introspective": [
        ("Giovanni's Room", "James Baldwin"),
        ("Go Tell It on the Mountain", "James Baldwin"),
        ("Another Country", "James Baldwin"),
        ("Educated", "Tara Westover"),
        ("My Dark Vanessa", "Kate Elizabeth Russell"),
        ("I Know Why the Caged Bird Sings", "Maya Angelou"),
        ("Gather Together in My Name", "Maya Angelou"),
        ("The Year of Magical Thinking", "Joan Didion"),
        ("Blue Nights", "Joan Didion"),
        ("The White Album", "Joan Didion"),
        ("In the Dream House", "Carmen Maria Machado"),
        ("Her Body and Other Parties", "Carmen Maria Machado"),
        ("The Argonauts", "Maggie Nelson"),
        ("Bluets", "Maggie Nelson"),
        ("Just Kids", "Patti Smith"),
        ("M Train", "Patti Smith"),
        ("H Is for Hawk", "Helen Macdonald"),
        ("Vesper Flights", "Helen Macdonald"),
        ("The Liars' Club", "Mary Karr"),
        ("Cherry", "Mary Karr"),
    ],
    # ── Southern Gothic + Literary Noir ──────────────────────────────────
    "Southern Gothic + Literary Noir": [
        ("As I Lay Dying", "William Faulkner"),
        ("Light in August", "William Faulkner"),
        ("A Good Man Is Hard to Find", "Flannery O'Connor"),
        ("Wise Blood", "Flannery O'Connor"),
        ("The Violent Bear It Away", "Flannery O'Connor"),
        ("Sharp Objects", "Gillian Flynn"),
        ("Other Voices Other Rooms", "Truman Capote"),
        ("The Heart Is a Lonely Hunter", "Carson McCullers"),
        ("The Member of the Wedding", "Carson McCullers"),
        ("A Confederacy of Dunces", "John Kennedy Toole"),
        ("The Neon Bible", "John Kennedy Toole"),
        ("Salvage the Bones", "Jesmyn Ward"),
        ("Sing Unburied Sing", "Jesmyn Ward"),
        ("Bastard Out of Carolina", "Dorothy Allison"),
        ("Cavedweller", "Dorothy Allison"),
        ("Winter's Bone", "Daniel Woodrell"),
        ("Tomato Red", "Daniel Woodrell"),
        ("The Devil All the Time", "Donald Ray Pollock"),
        ("The Heavenly Table", "Donald Ray Pollock"),
        ("Child of God", "Cormac McCarthy"),
    ],
    # ── Protest Literature + Political ───────────────────────────────────
    "Protest Literature + Political": [
        ("The Grapes of Wrath", "John Steinbeck"),
        ("Of Mice and Men", "John Steinbeck"),
        ("East of Eden", "John Steinbeck"),
        ("The Handmaid's Tale", "Margaret Atwood"),
        ("Alias Grace", "Margaret Atwood"),
        ("The Bluest Eye", "Toni Morrison"),
        ("Native Son", "Richard Wright"),
        ("Black Boy", "Richard Wright"),
        ("Invisible Man", "Ralph Ellison"),
        ("Juneteenth", "Ralph Ellison"),
        ("The Jungle", "Upton Sinclair"),
        ("Oil", "Upton Sinclair"),
        ("Brave New World", "Aldous Huxley"),
        ("Animal Farm", "George Orwell"),
        ("The Dispossessed", "Ursula K. Le Guin"),
        ("Fahrenheit 451", "Ray Bradbury"),
        ("The Power", "Naomi Alderman"),
        ("Disgrace", "J.M. Coetzee"),
        ("Waiting for the Barbarians", "J.M. Coetzee"),
        ("The Reluctant Fundamentalist", "Mohsin Hamid"),
    ],
    # ── Quiet Fiction + Lyrical Prose ────────────────────────────────────
    "Quiet Fiction + Lyrical Prose": [
        ("Stoner", "John Williams"),
        ("Gilead", "Marilynne Robinson"),
        ("Home", "Marilynne Robinson"),
        ("Lila", "Marilynne Robinson"),
        ("A Month in the Country", "J.L. Carr"),
        ("The Remains of the Day", "Kazuo Ishiguro"),
        ("An Artist of the Floating World", "Kazuo Ishiguro"),
        ("The Death of Ivan Ilyich", "Leo Tolstoy"),
        ("The Kreutzer Sonata", "Leo Tolstoy"),
        ("The Uncommon Reader", "Alan Bennett"),
        ("The Clothes They Stood Up In", "Alan Bennett"),
        ("Mrs Palfrey at the Claremont", "Elizabeth Taylor"),
        ("Angel", "Elizabeth Taylor"),
        ("A Whole Life", "Robert Seethaler"),
        ("The Tobacconist", "Robert Seethaler"),
        ("The Summer Book", "Tove Jansson"),
        ("The True Deceiver", "Tove Jansson"),
        ("The Hearing Trumpet", "Leonora Carrington"),
        ("Pond", "Claire-Louise Bennett"),
        ("Checkout 19", "Claire-Louise Bennett"),
    ],
    # ── Epistolary Novel ─────────────────────────────────────────────────
    "Epistolary Novel": [
        ("The Color Purple", "Alice Walker"),
        ("Possessing the Secret of Joy", "Alice Walker"),
        ("Flowers for Algernon", "Daniel Keyes"),
        ("The Perks of Being a Wallflower", "Stephen Chbosky"),
        ("We Need to Talk About Kevin", "Lionel Shriver"),
        ("The Guernsey Literary and Potato Peel Pie Society", "Mary Ann Shaffer"),
        ("Ella Minnow Pea", "Mark Dunn"),
        ("The Woman in White", "Wilkie Collins"),
        ("The Moonstone", "Wilkie Collins"),
        ("Daddy Long Legs", "Jean Webster"),
        ("Dear Enemy", "Jean Webster"),
        ("The Martian", "Andy Weir"),
        ("World War Z", "Max Brooks"),
        ("The Historian", "Elizabeth Kostova"),
        ("Where'd You Go Bernadette", "Maria Semple"),
        ("Lovely War", "Julie Berry"),
        ("84 Charing Cross Road", "Helene Hanff"),
        ("The Duchess of Bloomsbury Street", "Helene Hanff"),
        ("Griffin and Sabine", "Nick Bantock"),
        ("Sabine's Notebook", "Nick Bantock"),
    ],
    # ── Death & Mortality + Grief ────────────────────────────────────────
    "Death & Mortality + Grief": [
        ("The Year of Magical Thinking", "Joan Didion"),
        ("Blue Nights", "Joan Didion"),
        ("Grief Is the Thing with Feathers", "Max Porter"),
        ("Lanny", "Max Porter"),
        ("A Grief Observed", "C.S. Lewis"),
        ("The Lovely Bones", "Alice Sebold"),
        ("The Almost Moon", "Alice Sebold"),
        ("When Breath Becomes Air", "Paul Kalanithi"),
        ("Being Mortal", "Atul Gawande"),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee"),
        ("Wave", "Sonali Deraniyagala"),
        ("The Bright Hour", "Nina Riggs"),
        ("H Is for Hawk", "Helen Macdonald"),
        ("Everything Happens for a Reason", "Kate Bowler"),
        ("No Cure for Being Human", "Kate Bowler"),
        ("The Fault in Our Stars", "John Green"),
        ("Turtles All the Way Down", "John Green"),
        ("Norwegian Wood", "Haruki Murakami"),
        ("Kafka on the Shore", "Haruki Murakami"),
        ("A Little Life", "Hanya Yanagihara"),
    ],
}
