"""
Memoir & Biography Microtrope Seed Catalog — ~200 books across 10 clusters.
Strategy: max 2 books per author, focused on new memoir subtypes (v11.0 nodes).
Avoids authors already in nonfiction_seed_data.py pool.
"""

MEMOIR_MICROTROPE_CLUSTERS = {
    # ── Coming of Age Memoir ───────────────────────────────────────────────
    "Coming of Age Memoir": [
        ("Brown Girl Dreaming", "Jacqueline Woodson"),
        ("Another Brooklyn", "Jacqueline Woodson"),
        ("Boyhood", "J.M. Coetzee"),
        ("Youth", "J.M. Coetzee"),
        ("This Boy's Life", "Tobias Wolff"),
        ("In Pharaoh's Army", "Tobias Wolff"),
        ("The Tender Bar", "J.R. Moehringer"),
        ("Shoe Dog", "Phil Knight"),
        ("Hillbilly Elegy", "J.D. Vance"),
        ("Heartland", "Sarah Smarsh"),
        ("Bastards", "Mary Anna King"),
        ("The Distance Between Us", "Reyna Grande"),
        ("A Dream Called Home", "Reyna Grande"),
        ("Ordinary Light", "Tracy K. Smith"),
        ("Negroland", "Margo Jefferson"),
        ("The Best We Could Do", "Thi Bui"),
        ("The Gangster We Are All Looking For", "Le Thi Diem Thuy"),
        ("Crying in H Mart", "Michelle Zauner"),
        ("Priestdaddy", "Patricia Lockwood"),
        ("No One Tells You This", "Glynnis MacNicol"),
    ],
    # ── Trauma / Recovery Memoir ───────────────────────────────────────────
    "Trauma / Recovery Memoir": [
        ("What My Bones Know", "Stephanie Foo"),
        ("The Body Papers", "Grace Talusan"),
        ("What We Carry", "Maya Shanbhag Lang"),
        ("The Fact of a Body", "Alexandria Marzano-Lesnevich"),
        ("In the Wilderness", "Kim Barnes"),
        ("Hunger", "Roxane Gay"),
        ("Bad Feminist", "Roxane Gay"),
        ("Unspeakable", "Harriet Shawcross"),
        ("After the Eclipse", "Sarah Perry"),
        ("The Bright Hour", "Nina Riggs"),
        ("Everything Happens for a Reason", "Kate Bowler"),
        ("No Cure for Being Human", "Kate Bowler"),
        ("Borrowed Time", "Paul Monette"),
        ("Darkness Visible", "William Styron"),
        ("An Unquiet Mind", "Kay Redfield Jamison"),
        ("Nothing Was the Same", "Kay Redfield Jamison"),
        ("The Noonday Demon", "Andrew Solomon"),
        ("Far from the Tree", "Andrew Solomon"),
        ("The Empathy Exams", "Leslie Jamison"),
        ("The Recovering", "Leslie Jamison"),
    ],
    # ── Political Memoir ───────────────────────────────────────────────────
    "Political Memoir": [
        ("The Audacity of Hope", "Barack Obama"),
        ("A Promised Land", "Barack Obama"),
        ("Becoming", "Michelle Obama"),
        ("The Light We Carry", "Michelle Obama"),
        ("My Life", "Bill Clinton"),
        ("Living History", "Hillary Rodham Clinton"),
        ("What Happened", "Hillary Rodham Clinton"),
        ("Decision Points", "George W. Bush"),
        ("41", "George W. Bush"),
        ("Long Walk to Freedom", "Nelson Mandela"),
        ("Dare Not Linger", "Nelson Mandela"),
        ("The Story of My Experiments with Truth", "Mahatma Gandhi"),
        ("My Beloved World", "Sonia Sotomayor"),
        ("The World As It Is", "Ben Rhodes"),
        ("A Rage for Order", "Robert F. Worth"),
        ("The Man Without a Face", "Masha Gessen"),
        ("The Future Is History", "Masha Gessen"),
        ("Persepolis 2", "Marjane Satrapi"),
        ("The Return", "Hisham Matar"),
    ],
    # ── Creative Nonfiction ────────────────────────────────────────────────
    "Creative Nonfiction": [
        ("Pilgrim at Tinker Creek", "Annie Dillard"),
        ("An American Childhood", "Annie Dillard"),
        ("The White Album", "Joan Didion"),
        ("Slouching Towards Bethlehem", "Joan Didion"),
        ("The Argonauts", "Maggie Nelson"),
        ("Bluets", "Maggie Nelson"),
        ("Ongoingness", "Sarah Manguso"),
        ("300 Arguments", "Sarah Manguso"),
        ("The Book of Delights", "Ross Gay"),
        ("Inciting Joy", "Ross Gay"),
        ("Dept. of Speculation", "Jenny Offill"),
        ("Weather", "Jenny Offill"),
        ("The Situation and the Story", "Vivian Gornick"),
        ("Fierce Attachments", "Vivian Gornick"),
        ("This Is the Story of a Happy Marriage", "Ann Patchett"),
        ("These Precious Days", "Ann Patchett"),
    ],
    # ── Celebrity Biography ────────────────────────────────────────────────
    "Celebrity Biography": [
        ("Steve Jobs", "Walter Isaacson"),
        ("Einstein", "Walter Isaacson"),
        ("Open", "Andre Agassi"),
        ("Bossypants", "Tina Fey"),
        ("Yes Please", "Amy Poehler"),
        ("Is Everyone Hanging Out Without Me?", "Mindy Kaling"),
        ("Why Not Me?", "Mindy Kaling"),
        ("Born Standing Up", "Steve Martin"),
        ("Pure Drivel", "Steve Martin"),
        ("The Princess Diarist", "Carrie Fisher"),
        ("Wishful Drinking", "Carrie Fisher"),
        ("Just Kids", "Patti Smith"),
        ("M Train", "Patti Smith"),
        ("The Storyteller", "Dave Grohl"),
        ("Scar Tissue", "Anthony Kiedis"),
        ("Life", "Keith Richards"),
        ("Chronicles", "Bob Dylan"),
        ("Cash", "Johnny Cash"),
        ("Finding Me", "Viola Davis"),
        ("Friends Lovers and the Big Terrible Thing", "Matthew Perry"),
    ],
    # ── Literary Biography ─────────────────────────────────────────────────
    "Literary Biography": [
        ("Proust", "Edmund White"),
        ("Genet", "Edmund White"),
        ("Virginia Woolf", "Hermione Lee"),
        ("Edith Wharton", "Hermione Lee"),
        ("Charles Dickens", "Claire Tomalin"),
        ("Jane Austen", "Claire Tomalin"),
        ("Sylvia Plath", "Heather Clark"),
        ("Charlotte Bronte", "Claire Harman"),
        ("The Brontes", "Juliet Barker"),
        ("Shakespeare", "Bill Bryson"),
        ("Dickens", "Peter Ackroyd"),
        ("Blake", "Peter Ackroyd"),
        ("Kafka", "Reiner Stach"),
        ("Tolstoy", "A.N. Wilson"),
        ("George Orwell", "Gordon Bowker"),
        ("Hemingway", "Kenneth S. Lynn"),
        ("F. Scott Fitzgerald", "Matthew J. Bruccoli"),
        ("The Life of Emily Dickinson", "Richard B. Sewall"),
        ("Flaubert", "Frederick Brown"),
        ("Zola", "Frederick Brown"),
    ],
    # ── Scientific Memoir ──────────────────────────────────────────────────
    "Scientific Memoir": [
        ("Lab Girl", "Hope Jahren"),
        ("The Story of More", "Hope Jahren"),
        ("Letters to a Young Scientist", "Edward O. Wilson"),
        ("Naturalist", "Edward O. Wilson"),
        ("The Double Helix", "James D. Watson"),
        ("What Mad Pursuit", "Francis Crick"),
        ("Surely You're Joking Mr. Feynman", "Richard P. Feynman"),
        ("What Do You Care What Other People Think?", "Richard P. Feynman"),
        ("The Man Who Knew Infinity", "Robert Kanigel"),
        ("A Beautiful Mind", "Sylvia Nasar"),
        ("The Disappearing Spoon", "Sam Kean"),
        ("The Violinist's Thumb", "Sam Kean"),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot"),
        ("The Soul of an Octopus", "Sy Montgomery"),
        ("How to Be a Good Creature", "Sy Montgomery"),
        ("The Hidden Life of Trees", "Peter Wohlleben"),
        ("The Inner Life of Animals", "Peter Wohlleben"),
        ("My Family and Other Animals", "Gerald Durrell"),
        ("Birds Beasts and Relatives", "Gerald Durrell"),
        ("H Is for Hawk", "Helen Macdonald"),
    ],
    # ── Food / Culinary Memoir ─────────────────────────────────────────────
    "Food / Culinary Memoir": [
        ("Kitchen Confidential", "Anthony Bourdain"),
        ("Medium Raw", "Anthony Bourdain"),
        ("Blood Bones and Butter", "Gabrielle Hamilton"),
        ("Heat", "Bill Buford"),
        ("Dirt", "Bill Buford"),
        ("The Raw and the Cooked", "Jim Harrison"),
        ("Toast", "Nigel Slater"),
        ("Eating for England", "Nigel Slater"),
        ("Tender at the Bone", "Ruth Reichl"),
        ("Comfort Me with Apples", "Ruth Reichl"),
        ("A Homemade Life", "Molly Wizenberg"),
        ("Delancey", "Molly Wizenberg"),
        ("The Cooking Gene", "Michael W. Twitty"),
        ("Animal Vegetable Miracle", "Barbara Kingsolver"),
        ("My Life in France", "Julia Child"),
        ("Julie and Julia", "Julie Powell"),
        ("Salt Sugar Fat", "Michael Moss"),
        ("The Omnivore's Dilemma", "Michael Pollan"),
        ("Cooked", "Michael Pollan"),
    ],
    # ── Illness / Medical Memoir ───────────────────────────────────────────
    "Illness / Medical Memoir": [
        ("The Diving Bell and the Butterfly", "Jean-Dominique Bauby"),
        ("Gratitude", "Oliver Sacks"),
        ("On the Move", "Oliver Sacks"),
        ("Brain on Fire", "Susannah Cahalan"),
        ("The Great Pretender", "Susannah Cahalan"),
        ("The Last Lecture", "Randy Pausch"),
        ("Mortality", "Christopher Hitchens"),
        ("Hitch-22", "Christopher Hitchens"),
        ("The Undying", "Anne Boyer"),
        ("The Cancer Journals", "Audre Lorde"),
        ("Illness as Metaphor", "Susan Sontag"),
        ("Regarding the Pain of Others", "Susan Sontag"),
        ("The Iceberg", "Marion Coutts"),
        ("In Gratitude", "Jenny Diski"),
        ("The Cost of Living", "Deborah Levy"),
        ("Things I Don't Want to Know", "Deborah Levy"),
        ("And Finally", "Henry Marsh"),
        ("Do No Harm", "Henry Marsh"),
    ],
    # ── Adventure / Survival Memoir ────────────────────────────────────────
    "Adventure / Survival Memoir": [
        ("Into the Wild", "Jon Krakauer"),
        ("Into Thin Air", "Jon Krakauer"),
        ("Endurance", "Alfred Lansing"),
        ("Touching the Void", "Joe Simpson"),
        ("The Beckoning Silence", "Joe Simpson"),
        ("Wild", "Cheryl Strayed"),
        ("A Walk in the Woods", "Bill Bryson"),
        ("The Lost Continent", "Bill Bryson"),
        ("Adrift", "Steven Callahan"),
        ("The Perfect Storm", "Sebastian Junger"),
        ("War", "Sebastian Junger"),
        ("Alive", "Piers Paul Read"),
        ("The Climb", "Anatoli Boukreev"),
        ("Between a Rock and a Hard Place", "Aron Ralston"),
        ("127 Hours", "Aron Ralston"),
        ("South", "Ernest Shackleton"),
        ("The Kon-Tiki Expedition", "Thor Heyerdahl"),
        ("Fatu-Hiva", "Thor Heyerdahl"),
        ("Barbarian Days", "William Finnegan"),
        ("Deep", "James Nestor"),
    ],
}
