"""
Mystery Fiction Microtrope Seed Catalog — ~200 books across 10 clusters.
Strategy: max 2 books per author, detective/puzzle focus (distinct from suspense/thriller).
Authors selected to avoid overlap with thriller_seed_data.py pool.
"""

MYSTERY_MICROTROPE_CLUSTERS = {
    # ── Golden Age / Classic Detective ─────────────────────────────────────
    "Classic Detective / Golden Age": [
        ("A Man Lay Dead", "Ngaio Marsh"),
        ("Enter a Murderer", "Ngaio Marsh"),
        ("The Crime at Black Dudley", "Margery Allingham"),
        ("Mystery Mile", "Margery Allingham"),
        ("The Roman Hat Mystery", "Ellery Queen"),
        ("The French Powder Mystery", "Ellery Queen"),
        ("Fer-de-Lance", "Rex Stout"),
        ("The League of Frightened Men", "Rex Stout"),
        ("The Man Who Was Thursday", "G.K. Chesterton"),
        ("The Innocence of Father Brown", "G.K. Chesterton"),
        ("The Circular Staircase", "Mary Roberts Rinehart"),
        ("The Bat", "Mary Roberts Rinehart"),
        ("Whose Body?", "Dorothy L. Sayers"),
        ("Clouds of Witness", "Dorothy L. Sayers"),
        ("The Haunted Bookshop", "Christopher Morley"),
        ("Trent's Last Case", "E.C. Bentley"),
        ("The Cask", "Freeman Wills Crofts"),
        ("The Poisoned Chocolates Case", "Anthony Berkeley"),
    ],
    # ── Hardboiled / Noir Detective ────────────────────────────────────────
    "Hardboiled / Noir Detective": [
        ("The Maltese Falcon", "Dashiell Hammett"),
        ("The Thin Man", "Dashiell Hammett"),
        ("The Big Sleep", "Raymond Chandler"),
        ("Farewell My Lovely", "Raymond Chandler"),
        ("The Postman Always Rings Twice", "James M. Cain"),
        ("Double Indemnity", "James M. Cain"),
        ("I, the Jury", "Mickey Spillane"),
        ("My Gun Is Quick", "Mickey Spillane"),
        ("Red Harvest", "Dashiell Hammett"),
        ("The Moving Target", "Ross Macdonald"),
        ("The Drowning Pool", "Ross Macdonald"),
        ("Devil in a Blue Dress", "Walter Mosley"),
        ("A Red Death", "Walter Mosley"),
        ("A Rage in Harlem", "Chester Himes"),
        ("Cotton Comes to Harlem", "Chester Himes"),
        ("The Grifters", "Jim Thompson"),
        ("The Killer Inside Me", "Jim Thompson"),
        ("L.A. Confidential", "James Ellroy"),
        ("The Black Dahlia", "James Ellroy"),
    ],
    # ── Amateur Sleuth Cozies ──────────────────────────────────────────────
    "Amateur Sleuth / Cozy": [
        ("The Sweetness at the Bottom of the Pie", "Alan Bradley"),
        ("The Weed That Strings the Hangman's Bag", "Alan Bradley"),
        ("Aunt Dimity's Death", "Nancy Atherton"),
        ("Aunt Dimity and the Duke", "Nancy Atherton"),
        ("Catering to Nobody", "Diane Mott Davidson"),
        ("Dying for Chocolate", "Diane Mott Davidson"),
        ("Grime and Punishment", "Jill Churchill"),
        ("Farewell to Yarns", "Jill Churchill"),
        ("Dead Until Dark", "Charlaine Harris"),
        ("Living Dead in Dallas", "Charlaine Harris"),
        ("One for the Money", "Janet Evanovich"),
        ("Two for the Dough", "Janet Evanovich"),
        ("Death of a Gossip", "M.C. Beaton"),
        ("Death of a Cad", "M.C. Beaton"),
        ("The No. 1 Ladies' Detective Agency", "Alexander McCall Smith"),
        ("Tears of the Giraffe", "Alexander McCall Smith"),
        ("A is for Alibi", "Sue Grafton"),
        ("B is for Burglar", "Sue Grafton"),
        ("The Unexpected Mrs. Pollifax", "Dorothy Gilman"),
        ("The Amazing Mrs. Pollifax", "Dorothy Gilman"),
    ],
    # ── Small Town / Domestic Cozy ─────────────────────────────────────────
    "Small Town / Domestic Cozy": [
        ("Still Life", "Louise Penny"),
        ("A Fatal Grace", "Louise Penny"),
        ("The Thursday Murder Club", "Richard Osman"),
        ("The Man Who Died Twice", "Richard Osman"),
        ("Murder with Peacocks", "Donna Andrews"),
        ("Murder with Puffins", "Donna Andrews"),
        ("Death on Demand", "Carolyn Hart"),
        ("Design for Murder", "Carolyn Hart"),
        ("The Thin Woman", "Dorothy Cannell"),
        ("The Widows Club", "Dorothy Cannell"),
        ("A Share in Death", "Deborah Crombie"),
        ("All Shall Be Well", "Deborah Crombie"),
        ("The Body in the Transept", "Jeanne M. Dams"),
        ("The Trouble with the Church", "Jeanne M. Dams"),
        ("The Witch of Blackbird Pond", "Elizabeth George Speare"),
        ("The Secret of the Old Clock", "Carolyn Keene"),
        ("The Hidden Staircase", "Carolyn Keene"),
        ("A Morbid Taste for Bones", "Ellis Peters"),
        ("Chocolate Chip Cookie Murder", "Joanne Fluke"),
        ("Strawberry Shortcake Murder", "Joanne Fluke"),
    ],
    # ── Nordic Noir / Scandinavian Crime ───────────────────────────────────
    "Nordic Noir": [
        ("Faceless Killers", "Henning Mankell"),
        ("The Dogs of Riga", "Henning Mankell"),
        ("Jar City", "Arnaldur Indridason"),
        ("Silence of the Grave", "Arnaldur Indridason"),
        ("The Keeper of Lost Causes", "Jussi Adler-Olsen"),
        ("The Absent One", "Jussi Adler-Olsen"),
        ("The Ice Princess", "Camilla Lackberg"),
        ("The Preacher", "Camilla Lackberg"),
        ("The Snowman", "Jo Nesbo"),
        ("The Leopard", "Jo Nesbo"),
        ("The Hypnotist", "Lars Kepler"),
        ("The Nightmare", "Lars Kepler"),
        ("The Crow Girl", "Erik Axl Sund"),
        ("Sun Storm", "Asa Larsson"),
        ("The Blood Spilt", "Asa Larsson"),
        ("Midwinter Blood", "Mons Kallentoft"),
        ("The Boy in the Suitcase", "Lene Kaaberbol"),
        ("Invisible Murder", "Lene Kaaberbol"),
        ("I'm Traveling Alone", "Samuel Bjork"),
        ("The Owl Always Hunts at Night", "Samuel Bjork"),
    ],
    # ── Police Procedural ──────────────────────────────────────────────────
    "Police Procedural": [
        ("The Blackhouse", "Peter May"),
        ("The Lewis Man", "Peter May"),
        ("Knots and Crosses", "Ian Rankin"),
        ("Hide and Seek", "Ian Rankin"),
        ("A Great Deliverance", "Elizabeth George"),
        ("Well-Schooled in Murder", "Elizabeth George"),
        ("Blindsighted", "Karin Slaughter"),
        ("Kisscut", "Karin Slaughter"),
        ("The Mermaids Singing", "Val McDermid"),
        ("The Wire in the Blood", "Val McDermid"),
        ("Dead Simple", "Peter James"),
        ("Looking Good Dead", "Peter James"),
        ("Case Histories", "Kate Atkinson"),
        ("One Good Turn", "Kate Atkinson"),
        ("Gallows View", "Peter Robinson"),
        ("A Dedicated Man", "Peter Robinson"),
        ("The Black Echo", "Michael Connelly"),
        ("The Black Ice", "Michael Connelly"),
        ("The Crossing Places", "Elly Griffiths"),
        ("The Janus Stone", "Elly Griffiths"),
    ],
    # ── Psychological Mystery ──────────────────────────────────────────────
    "Psychological Mystery": [
        ("The Talented Mr. Ripley", "Patricia Highsmith"),
        ("Strangers on a Train", "Patricia Highsmith"),
        ("Rebecca", "Daphne du Maurier"),
        ("My Cousin Rachel", "Daphne du Maurier"),
        ("The Turn of the Screw", "Henry James"),
        ("The Woman in White", "Wilkie Collins"),
        ("The Moonstone", "Wilkie Collins"),
        ("Dark Places", "Gillian Flynn"),
        ("Sharp Objects", "Gillian Flynn"),
        ("Before I Go to Sleep", "S.J. Watson"),
        ("Second Life", "S.J. Watson"),
        ("The Woman in the Window", "A.J. Finn"),
        ("What Lies Between Us", "John Marrs"),
        ("The One", "John Marrs"),
        ("The Girl on the Train", "Paula Hawkins"),
        ("Into the Water", "Paula Hawkins"),
        ("Magpie Murders", "Anthony Horowitz"),
        ("Moonflower Murders", "Anthony Horowitz"),
        ("The 7 1/2 Deaths of Evelyn Hardcastle", "Stuart Turton"),
        ("The Devil and the Dark Water", "Stuart Turton"),
    ],
    # ── Legal / Courtroom Mystery ──────────────────────────────────────────
    "Legal / Courtroom Mystery": [
        ("The Firm", "John Grisham"),
        ("A Time to Kill", "John Grisham"),
        ("Presumed Innocent", "Scott Turow"),
        ("The Burden of Proof", "Scott Turow"),
        ("Compelling Evidence", "Steve Martini"),
        ("Prime Witness", "Steve Martini"),
        ("Defending Jacob", "William Landay"),
        ("Anatomy of a Murder", "Robert Traver"),
        ("To Kill a Mockingbird", "Harper Lee"),
        ("The Caine Mutiny", "Herman Wouk"),
        ("Mistaken Identity", "Lisa Scottoline"),
        ("Everywhere That Mary Went", "Lisa Scottoline"),
        ("Error of Judgment", "Roy Lewis"),
        ("A Certain Justice", "P.D. James"),
        ("The Children Act", "Ian McEwan"),
        ("The Rule of Law", "John Lescroart"),
        ("The Local", "Joey Hartstone"),
        ("The Holdout", "Graham Moore"),
    ],
    # ── Techno / Forensic Mystery ──────────────────────────────────────────
    "Techno / Forensic Mystery": [
        ("Postmortem", "Patricia Cornwell"),
        ("Body of Evidence", "Patricia Cornwell"),
        ("Deja Dead", "Kathy Reichs"),
        ("Death du Jour", "Kathy Reichs"),
        ("The Bone Collector", "Jeffery Deaver"),
        ("The Coffin Dancer", "Jeffery Deaver"),
        ("Carved in Bone", "Jefferson Bass"),
        ("Flesh and Bone", "Jefferson Bass"),
        ("The Chemistry of Death", "Simon Beckett"),
        ("Written in Bone", "Simon Beckett"),
        ("The Surgeon", "Tess Gerritsen"),
        ("The Apprentice", "Tess Gerritsen"),
        ("Trace Evidence", "Elizabeth Becka"),
        ("Unknown Means", "Elizabeth Becka"),
        ("The Poison Artist", "Jonathan Moore"),
        ("The Dark Room", "Jonathan Moore"),
        ("The Alienist", "Caleb Carr"),
        ("The Angel of Darkness", "Caleb Carr"),
    ],
    # ── Locked Room / Puzzle Mystery ───────────────────────────────────────
    "Locked Room / Puzzle Mystery": [
        ("The Three Coffins", "John Dickson Carr"),
        ("The Crooked Hinge", "John Dickson Carr"),
        ("The Mystery of the Yellow Room", "Gaston Leroux"),
        ("The Phantom of the Opera", "Gaston Leroux"),
        ("The Tokyo Zodiac Murders", "Soji Shimada"),
        ("Murder in the Crooked House", "Soji Shimada"),
        ("Death from a Top Hat", "Clayton Rawson"),
        ("The Footprints on the Ceiling", "Clayton Rawson"),
        ("The Decagon House Murders", "Yukito Ayatsuji"),
        ("The Mill House Murders", "Yukito Ayatsuji"),
        ("And Then There Were None", "Agatha Christie"),
        ("Murder on the Orient Express", "Agatha Christie"),
        ("The Murders in the Rue Morgue", "Edgar Allan Poe"),
        ("The Mystery of Marie Roget", "Edgar Allan Poe"),
        ("Rim of the Pit", "Hake Talbot"),
        ("The Hangman's Handyman", "Hake Talbot"),
        ("Nine Times Nine", "Anthony Boucher"),
        ("The Case of the Seven of Calvary", "Anthony Boucher"),
        ("The Red Right Hand", "Joel Townsley Rogers"),
        ("The White Cockatoo", "Mignon G. Eberhart"),
    ],
}
