"""
Non-Fiction Microtrope Seed Catalog — ~150 books across 12 clusters.
"""

NONFICTION_MICROTROPE_CLUSTERS = {
    "Memoir + Autobiography": [
        ("Educated", "Tara Westover"),
        ("The Glass Castle", "Jeannette Walls"),
        ("Wild", "Cheryl Strayed"),
        ("When Breath Becomes Air", "Paul Kalanithi"),
        ("Just Kids", "Patti Smith"),
        ("The Liars' Club", "Mary Karr"),
        ("Lit", "Mary Karr"),
        ("Running with Scissors", "Augusten Burroughs"),
        ("Angela's Ashes", "Frank McCourt"),
        ("I Know Why the Caged Bird Sings", "Maya Angelou"),
        ("The Diary of a Young Girl", "Anne Frank"),
        ("Born a Crime", "Trevor Noah"),
        ("Heavy", "Kiese Laymon"),
        ("Know My Name", "Chanel Miller"),
        ("Men We Reaped", "Jesmyn Ward"),
        ("H Is for Hawk", "Helen Macdonald"),
        ("Persepolis", "Marjane Satrapi"),
        ("Fun Home", "Alison Bechdel"),
        ("The Complete Persepolis", "Marjane Satrapi"),
        ("The Wolf of the Steppes", "Harold Lamb"),
    ],
    "True Crime + Investigative": [
        ("In Cold Blood", "Truman Capote"),
        ("Helter Skelter", "Vincent Bugliosi"),
        ("The Stranger Beside Me", "Ann Rule"),
        ("I'll Be Gone in the Dark", "Michelle McNamara"),
        ("Mindhunter", "John E. Douglas"),
        ("The Devil in the White City", "Erik Larson"),
        ("Dead Wake", "Erik Larson"),
        ("In the Garden of Beasts", "Erik Larson"),
        ("People Who Eat Darkness", "Richard Lloyd Parry"),
        ("The Journalist and the Murderer", "Janet Malcolm"),
        ("Lost Girls", "Robert Kolker"),
        ("American Kingpin", "Nick Bilton"),
        ("Bad Blood", "John Carreyrou"),
        ("The Spider Network", "David Enrich"),
        ("Killers of the Flower Moon", "David Grann"),
        ("The Lost City of Z", "David Grann"),
        ("The Wager", "David Grann"),
        ("Dark Money", "Jane Mayer"),
        ("Going Clear", "Lawrence Wright"),
        ("The Looming Tower", "Lawrence Wright"),
    ],
    "Travel + Nature Writing": [
        ("A Walk in the Woods", "Bill Bryson"),
        ("The Lost Continent", "Bill Bryson"),
        ("Into the Wild", "Jon Krakauer"),
        ("Into Thin Air", "Jon Krakauer"),
        ("The Snow Leopard", "Peter Matthiessen"),
        ("Travels with Charley", "John Steinbeck"),
        ("The Song of the Dodo", "David Quammen"),
        ("The Invention of Nature", "Andrea Wulf"),
        ("Walden", "Henry David Thoreau"),
        ("Pilgrim at Tinker Creek", "Annie Dillard"),
        ("Desert Solitaire", "Edward Abbey"),
        ("Braiding Sweetgrass", "Robin Wall Kimmerer"),
        ("The Hidden Life of Trees", "Peter Wohlleben"),
        ("The Peregrine", "J.A. Baker"),
        ("Arctic Dreams", "Barry Lopez"),
        ("The Old Ways", "Robert Macfarlane"),
        ("The Lost Words", "Robert Macfarlane"),
        ("The Outrun", "Amy Liptrot"),
        ("Fever Trees", "Timothy Winegard"),
        ("The Forest Unseen", "David George Haskell"),
    ],
    "War Memoir + History": [
        ("The Things They Carried", "Tim O'Brien"),
        ("If I Die in a Combat Zone", "Tim O'Brien"),
        ("A Rumor of War", "Philip Caputo"),
        ("Band of Brothers", "Stephen E. Ambrose"),
        ("Citizen Soldiers", "Stephen E. Ambrose"),
        ("The Guns of August", "Barbara Tuchman"),
        ("Stalingrad", "Antony Beevor"),
        ("Berlin: The Downfall", "Antony Beevor"),
        ("Homage to Catalonia", "George Orwell"),
        ("The Wretched of the Earth", "Frantz Fanon"),
        ("The Warmth of Other Suns", "Isabel Wilkerson"),
        ("Caste", "Isabel Wilkerson"),
        ("King Leopold's Ghost", "Adam Hochschild"),
        ("The First World War", "John Keegan"),
        ("The Second World War", "John Keegan"),
        ("The Rise and Fall of the Third Reich", "William L. Shirer"),
        ("The Man Who Stayed Behind", "Sidney Rittenberg"),
        ("Nothing to Envy", "Barbara Demick"),
        ("Silk Roads", "Peter Frankopan"),
        ("SPQR", "Mary Beard"),
    ],
    "Philosophy + Psychology": [
        ("Meditations", "Marcus Aurelius"),
        ("Republic", "Plato"),
        ("Thus Spoke Zarathustra", "Friedrich Nietzsche"),
        ("Beyond Good and Evil", "Friedrich Nietzsche"),
        ("Man's Search for Meaning", "Viktor Frankl"),
        ("The Will to Change", "bell hooks"),
        ("All About Love", "bell hooks"),
        ("Thinking Fast and Slow", "Daniel Kahneman"),
        ("The Power of Habit", "Charles Duhigg"),
        ("Atomic Habits", "James Clear"),
        ("The Gifts of Imperfection", "Brené Brown"),
        ("Daring Greatly", "Brené Brown"),
        ("The Body Keeps the Score", "Bessel van der Kolk"),
        ("Stumbling on Happiness", "Daniel Gilbert"),
        ("Flow", "Mihaly Csikszentmihalyi"),
        ("Gödel Escher Bach", "Douglas Hofstadter"),
        ("The Righteous Mind", "Jonathan Haidt"),
        ("The Happiness Hypothesis", "Jonathan Haidt"),
        ("21 Lessons for the 21st Century", "Yuval Noah Harari"),
        ("Sapiens", "Yuval Noah Harari"),
    ],
    "Popular Science + History": [
        ("The Selfish Gene", "Richard Dawkins"),
        ("The God Delusion", "Richard Dawkins"),
        ("A Brief History of Time", "Stephen Hawking"),
        ("Cosmos", "Carl Sagan"),
        ("The Demon-Haunted World", "Carl Sagan"),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot"),
        ("The Gene", "Siddhartha Mukherjee"),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee"),
        ("Astrophysics for People in a Hurry", "Neil deGrasse Tyson"),
        ("The Sixth Extinction", "Elizabeth Kolbert"),
        ("Under a White Sky", "Elizabeth Kolbert"),
        ("The Structure of Scientific Revolutions", "Thomas Kuhn"),
        ("Chaos", "James Gleick"),
        ("The Information", "James Gleick"),
        ("The Man Who Mistook His Wife for a Hat", "Oliver Sacks"),
        ("Musicophilia", "Oliver Sacks"),
        ("Freakonomics", "Steven Levitt"),
        ("Outliers", "Malcolm Gladwell"),
        ("Blink", "Malcolm Gladwell"),
        ("Collapse", "Jared Diamond"),
    ],
    "Essays + Literary Journalism": [
        ("The White Album", "Joan Didion"),
        ("Slouching Towards Bethlehem", "Joan Didion"),
        ("The Right Stuff", "Tom Wolfe"),
        ("The Electric Kool-Aid Acid Test", "Tom Wolfe"),
        ("Consider the Lobster", "David Foster Wallace"),
        ("A Supposedly Fun Thing I'll Never Do Again", "David Foster Wallace"),
        ("We Tell Ourselves Stories in Order to Live", "Joan Didion"),
        ("The Art of the Personal Essay", "Phillip Lopate"),
        ("Upstream", "Mary Oliver"),
        ("The Boys of My Youth", "Jo Ann Beard"),
        ("Me Talk Pretty One Day", "David Sedaris"),
        ("When You Are Engulfed in Flames", "David Sedaris"),
        ("Giving Up the Ghost", "Hilary Mantel"),
        ("Essayism", "Brian Dillon"),
        ("How to Slowly Kill Yourself and Others in America", "Kiese Laymon"),
        ("How to Be Alone", "Jonathan Franzen"),
        ("The End of the End of the Earth", "Jonathan Franzen"),
        ("Notes on Grief", "Chimamanda Ngozi Adichie"),
        ("Zami: A New Spelling of My Name", "Audre Lorde"),
        ("Sister Outsider", "Audre Lorde"),
    ],
    "Sociology + Economics + Political Theory": [
        ("Freakonomics", "Steven Levitt"),
        ("The Wealth of Nations", "Adam Smith"),
        ("The Communist Manifesto", "Karl Marx"),
        ("Das Kapital", "Karl Marx"),
        ("The Social Contract", "Jean-Jacques Rousseau"),
        ("Leviathan", "Thomas Hobbes"),
        ("The Second Sex", "Simone de Beauvoir"),
        ("Orientalism", "Edward Said"),
        ("The New Jim Crow", "Michelle Alexander"),
        ("The Color of Law", "Richard Rothstein"),
        ("Evicted", "Matthew Desmond"),
        ("Nickel and Dimed", "Barbara Ehrenreich"),
        ("The Shock Doctrine", "Naomi Klein"),
        ("No Logo", "Naomi Klein"),
        ("This Changes Everything", "Naomi Klein"),
        ("Capital in the Twenty-First Century", "Thomas Piketty"),
        ("The Age of Surveillance Capitalism", "Shoshana Zuboff"),
        ("Who We Are and How We Got Here", "David Reich"),
        ("Behave", "Robert Sapolsky"),
        ("Determined", "Robert Sapolsky"),
    ],
}
