"""
Romance Seed Data — ~400 popular romance books organized by subgenre.
Each entry is a (title, author) tuple.

Subgenres covered:
  - Dark Romance (50)
  - Contemporary Romance (50)
  - Romantasy (50)
  - Historical Romance (50)
  - Paranormal Romance (50)
  - MM Romance (40)
  - FF Romance (20)
  - Sports Romance (30)
  - Small Town Romance (20)
  - Dark Bully / Stalker Romance (30)
  - Billionaire / Workplace / Office Romance (20)

TOTAL: ~410 books
"""

# ═══════════════════════════════════════════════════════════════════════════════
# DARK ROMANCE (50)
# ═══════════════════════════════════════════════════════════════════════════════
DARK_ROMANCE = [
    ("Haunting Adeline", "H. D. Carlton"),
    ("Hunting Adeline", "H. D. Carlton"),
    ("Den of Vipers", "K. A. Knight"),
    ("Credence", "Penelope Douglas"),
    ("Corrupt", "Penelope Douglas"),
    ("The Ritual", "Shantel Tessier"),
    ("Twisted Love", "Ana Huang"),
    ("Twisted Games", "Ana Huang"),
    ("Twisted Hate", "Ana Huang"),
    ("Twisted Lies", "Ana Huang"),
    ("Ruthless People", "J.J. McAvoy"),
    ("Nero", "S.J. Tilly"),
    ("King", "S.J. Tilly"),
    ("Dom", "S.J. Tilly"),
    ("Monster in His Eyes", "J.M. Darhower"),
    ("God of Malice", "Rina Kent"),
    ("God of Wrath", "Rina Kent"),
    ("That Sik Luv", "Jescie Hall"),
    ("Does It Hurt?", "H. D. Carlton"),
    ("The Sinner", "Shantel Tessier"),
    ("Little Stranger", "Leigh Rivers"),
    ("Still Beating", "Jennifer Hartmann"),
    ("Butcher & Blackbird", "Brynne Weaver"),
    ("Leather & Lark", "Brynne Weaver"),
    ("Hooked", "Emily McIntire"),
    ("Scarred", "Emily McIntire"),
    ("Wretched", "Emily McIntire"),
    ("Skeleton King", "Charity Ferrell"),
    ("The Never King", "Nikki St. Crowe"),
    ("Scream for Us", "Molly Doyle"),
    ("Bloodshed", "Molly Doyle"),
    ("Green Light", "Jescie Hall"),
    ("The Pucking Wrong Number", "C. R. Jane"),
    ("Graves", "Katelyn Taylor"),
    ("Sicko", "Amo Jones"),
    ("The Darkest Temptation", "Danielle Lori"),
    ("The Sweetest Oblivion", "Danielle Lori"),
    ("The Maddest Obsession", "Danielle Lori"),
    ("Promises and Pomegranates", "Sav R. Miller"),
    ("Souls Unfractured", "Tillie Cole"),
    ("God of Pain", "Rina Kent"),
    ("God of Fury", "Rina Kent"),
    ("Cold Hearted", "Heather Guerre"),
    ("Lords of Wrath", "Angel Lawson & Samantha Rue"),
    ("Fear Me", "B. B. Reid"),
    ("Obsession", "Harley Wylde"),
    ("The Bad Guy", "Celina Grace"),
    ("Descent", "Sam Mariano"),
    ("Untouchable", "Sam Mariano"),
    ("Even if It Hurts", "Sam Mariano"),
    ("Contempt", "Sam Mariano"),
    ("Sinners Anonymous", "Somme Sketcher"),
    ("Sinners Condemned", "Somme Sketcher"),
    ("The Predator", "Runyx"),
    ("The Emperor", "Runyx"),
    ("Carnage", "Shantel Tessier"),
    ("Sabotage", "Shantel Tessier"),
    ("His Pretty Little Burden", "Nicci Harris"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# CONTEMPORARY ROMANCE (50)
# ═══════════════════════════════════════════════════════════════════════════════
CONTEMPORARY_ROMANCE = [
    ("It Ends With Us", "Colleen Hoover"),
    ("It Starts With Us", "Colleen Hoover"),
    ("The Love Hypothesis", "Ali Hazelwood"),
    ("Beach Read", "Emily Henry"),
    ("People We Meet on Vacation", "Emily Henry"),
    ("Book Lovers", "Emily Henry"),
    ("Happy Place", "Emily Henry"),
    ("The Deal", "Elle Kennedy"),
    ("Icebreaker", "Hannah Grace"),
    ("Things We Never Got Over", "Lucy Score"),
    ("Things We Hide from the Light", "Lucy Score"),
    ("Love and Other Words", "Christina Lauren"),
    ("The Unhoneymooners", "Christina Lauren"),
    ("Yours Truly", "Abby Jimenez"),
    ("Part of Your World", "Abby Jimenez"),
    ("Just for the Summer", "Abby Jimenez"),
    ("Ugly Love", "Colleen Hoover"),
    ("November 9", "Colleen Hoover"),
    ("Verity", "Colleen Hoover"),
    ("Reminders of Him", "Colleen Hoover"),
    ("Twisted Games", "Ana Huang"),
    ("Twisted Hate", "Ana Huang"),
    ("Twisted Lies", "Ana Huang"),
    ("King of Wrath", "Ana Huang"),
    ("King of Pride", "Ana Huang"),
    ("King of Greed", "Ana Huang"),
    ("Flawless", "Elsie Silver"),
    ("Heartless", "Elsie Silver"),
    ("Powerless", "Elsie Silver"),
    ("Reckless", "Elsie Silver"),
    ("Hopeless", "Elsie Silver"),
    ("Magnolia Parks", "Jessa Hastings"),
    ("Daisy Haites", "Jessa Hastings"),
    ("The Cheat Sheet", "Sarah Adams"),
    ("The Soulmate Equation", "Christina Lauren"),
    ("The Friend Zone", "Abby Jimenez"),
    ("The Happy Ever After Playlist", "Abby Jimenez"),
    ("The Spanish Love Deception", "Elena Armas"),
    ("The American Roommate Experiment", "Elena Armas"),
    ("The Kiss Quotient", "Helen Hoang"),
    ("The Bride Test", "Helen Hoang"),
    ("The Heart Principle", "Helen Hoang"),
    ("Every Summer After", "Carley Fortune"),
    ("Meet Me at the Lake", "Carley Fortune"),
    ("The Flatshare", "Beth O'Leary"),
    ("The No-Show", "Beth O'Leary"),
    ("Well Met", "Jen DeLuca"),
    ("Get a Life, Chloe Brown", "Talia Hibbert"),
    ("Take a Hint, Dani Brown", "Talia Hibbert"),
    ("Act Your Age, Eve Brown", "Talia Hibbert"),
    ("The Worst Best Man", "Mia Sosa"),
    ("You Deserve Each Other", "Sarah Hogle"),
    ("Twice Shy", "Sarah Hogle"),
    ("The Hating Game", "Sally Thorne"),
    ("Josh and Hazel's Guide to Not Dating", "Christina Lauren"),
    ("Dating You / Hating You", "Christina Lauren"),
    ("The Roommate", "Rosie Danan"),
    ("The Intimacy Experiment", "Rosie Danan"),
    ("In a Holidaze", "Christina Lauren"),
    ("The Wedding Date", "Jasmine Guillory"),
    ("The Proposal", "Jasmine Guillory"),
    ("The Wedding Party", "Jasmine Guillory"),
    ("Red, White & Royal Blue", "Casey McQuiston"),
    ("One Last Stop", "Casey McQuiston"),
    ("Funny Story", "Emily Henry"),
    ("This Summer Will Be Different", "Carley Fortune"),
    ("Just Last Night", "Mhairi McFarlane"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# ROMANTASY (50)
# ═══════════════════════════════════════════════════════════════════════════════
ROMANTASY = [
    ("A Court of Thorns and Roses", "Sarah J. Maas"),
    ("A Court of Mist and Fury", "Sarah J. Maas"),
    ("A Court of Wings and Ruin", "Sarah J. Maas"),
    ("A Court of Silver Flames", "Sarah J. Maas"),
    ("From Blood and Ash", "Jennifer L. Armentrout"),
    ("A Kingdom of Flesh and Fire", "Jennifer L. Armentrout"),
    ("The Crown of Gilded Bones", "Jennifer L. Armentrout"),
    ("Fourth Wing", "Rebecca Yarros"),
    ("Iron Flame", "Rebecca Yarros"),
    ("Divine Rivals", "Rebecca Ross"),
    ("Ruthless Vows", "Rebecca Ross"),
    ("The Serpent and the Wings of Night", "Carissa Broadbent"),
    ("The Ashes and the Star-Cursed King", "Carissa Broadbent"),
    ("Throne of Glass", "Sarah J. Maas"),
    ("Crown of Midnight", "Sarah J. Maas"),
    ("Heir of Fire", "Sarah J. Maas"),
    ("Queen of Shadows", "Sarah J. Maas"),
    ("Empire of Storms", "Sarah J. Maas"),
    ("Tower of Dawn", "Sarah J. Maas"),
    ("Kingdom of Ash", "Sarah J. Maas"),
    ("House of Earth and Blood", "Sarah J. Maas"),
    ("House of Sky and Breath", "Sarah J. Maas"),
    ("House of Flame and Shadow", "Sarah J. Maas"),
    ("Gild", "Raven Kennedy"),
    ("Glint", "Raven Kennedy"),
    ("Gleam", "Raven Kennedy"),
    ("Glow", "Raven Kennedy"),
    ("Gold", "Raven Kennedy"),
    ("Radiance", "Grace Draven"),
    ("Daughter of No Worlds", "Carissa Broadbent"),
    ("The Bridge Kingdom", "Danielle L. Jensen"),
    ("The Traitor Queen", "Danielle L. Jensen"),
    ("A Fate Inked in Blood", "Danielle L. Jensen"),
    ("Quicksilver", "Callie Hart"),
    ("Spark of the Everflame", "Penn Cole"),
    ("Trial of the Sun Queen", "Nisha J. Tuli"),
    ("Rule of the Aurora King", "Nisha J. Tuli"),
    ("The Hurricane Wars", "Thea Guanzon"),
    ("Phantasma", "Kaylie Smith"),
    ("A Dawn of Onyx", "Kate Golden"),
    ("The Ever King", "L. J. Andrews"),
    ("The Ever Queen", "L. J. Andrews"),
    ("When the Moon Hatched", "Sarah A. Parker"),
    ("One Dark Window", "Rachel Gillig"),
    ("Two Twisted Crowns", "Rachel Gillig"),
    ("A Dawn of Gods and Fury", "K. A. Tucker"),
    ("The Foxglove King", "Hannah Whitten"),
    ("A Broken Blade", "Melissa Blair"),
    ("The North Wind", "Alexandria Warwick"),
    ("The Jasad Heir", "Sara Hashem"),
    ("Assistant to the Villain", "Hannah Nicole Maehrer"),
    ("Iron Widow", "Xiran Jay Zhao"),
    ("The Wren in the Holly Library", "K. A. Linde"),
    ("The Book of Azrael", "Amber V. Nicole"),
    ("Throne of the Fallen", "Kerri Maniscalco"),
    ("A Touch of Darkness", "Scarlett St. Clair"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# HISTORICAL ROMANCE (50)
# ═══════════════════════════════════════════════════════════════════════════════
HISTORICAL_ROMANCE = [
    ("The Duke and I", "Julia Quinn"),
    ("The Viscount Who Loved Me", "Julia Quinn"),
    ("An Offer from a Gentleman", "Julia Quinn"),
    ("Romancing Mister Bridgerton", "Julia Quinn"),
    ("To Sir Phillip, With Love", "Julia Quinn"),
    ("When He Was Wicked", "Julia Quinn"),
    ("It's in His Kiss", "Julia Quinn"),
    ("On the Way to the Wedding", "Julia Quinn"),
    ("Outlander", "Diana Gabaldon"),
    ("Dragonfly in Amber", "Diana Gabaldon"),
    ("Voyager", "Diana Gabaldon"),
    ("The Wallflower Wager", "Tessa Dare"),
    ("The Duchess Deal", "Tessa Dare"),
    ("The Governess Game", "Tessa Dare"),
    ("Devil in Winter", "Lisa Kleypas"),
    ("Secrets of a Summer Night", "Lisa Kleypas"),
    ("It Happened One Autumn", "Lisa Kleypas"),
    ("Scandal in Spring", "Lisa Kleypas"),
    ("A Week to Be Wicked", "Tessa Dare"),
    ("Any Duchess Will Do", "Tessa Dare"),
    ("Dreaming of You", "Lisa Kleypas"),
    ("Marrying Winterborne", "Lisa Kleypas"),
    ("Devil's Daughter", "Lisa Kleypas"),
    ("The Highwayman", "Kerrigan Byrne"),
    ("The Hunter", "Kerrigan Byrne"),
    ("The Highlander", "Kerrigan Byrne"),
    ("Bringing Down the Duke", "Evie Dunmore"),
    ("A Rogue of One's Own", "Evie Dunmore"),
    ("Portrait of a Scotsman", "Evie Dunmore"),
    ("The Madness of Lord Ian Mackenzie", "Jennifer Ashley"),
    ("Nine Rules to Break When Romancing a Rake", "Sarah MacLean"),
    ("A Rogue by Any Other Name", "Sarah MacLean"),
    ("One Good Earl Deserves a Lover", "Sarah MacLean"),
    ("Lord of Scoundrels", "Loretta Chase"),
    ("A Lady's Guide to Fortune-Hunting", "Sophie Irwin"),
    ("My Darling Duke", "Stacy Reid"),
    ("Slightly Dangerous", "Mary Balogh"),
    ("Slightly Married", "Mary Balogh"),
    ("Flowers from the Storm", "Laura Kinsale"),
    ("The Bride", "Julie Garwood"),
    ("The Secret", "Julie Garwood"),
    ("Ransom", "Julie Garwood"),
    ("A Knight in Shining Armor", "Jude Deveraux"),
    ("Whitney, My Love", "Judith McNaught"),
    ("Something Wonderful", "Judith McNaught"),
    ("Indigo", "Beverly Jenkins"),
    ("Rebel", "Beverly Jenkins"),
    ("To Catch a Raven", "Beverly Jenkins"),
    ("The Raven Prince", "Elizabeth Hoyt"),
    ("Wicked Intentions", "Elizabeth Hoyt"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# PARANORMAL ROMANCE (50)
# ═══════════════════════════════════════════════════════════════════════════════
PARANORMAL_ROMANCE = [
    ("Twilight", "Stephenie Meyer"),
    ("New Moon", "Stephenie Meyer"),
    ("Eclipse", "Stephenie Meyer"),
    ("Breaking Dawn", "Stephenie Meyer"),
    ("Dark Lover", "J. R. Ward"),
    ("Lover Eternal", "J. R. Ward"),
    ("Lover Awakened", "J. R. Ward"),
    ("Lover Revealed", "J. R. Ward"),
    ("A Discovery of Witches", "Deborah Harkness"),
    ("Shadow of Night", "Deborah Harkness"),
    ("The Book of Life", "Deborah Harkness"),
    ("Bitten", "Kelley Armstrong"),
    ("Stolen", "Kelley Armstrong"),
    ("Dime Store Magic", "Kelley Armstrong"),
    ("Halfway to the Grave", "Jeaniene Frost"),
    ("One Foot in the Grave", "Jeaniene Frost"),
    ("At Grave's End", "Jeaniene Frost"),
    ("Dead Until Dark", "Charlaine Harris"),
    ("Living Dead in Dallas", "Charlaine Harris"),
    ("Club Dead", "Charlaine Harris"),
    ("Angels' Blood", "Nalini Singh"),
    ("Archangel's Kiss", "Nalini Singh"),
    ("Slave to Sensation", "Nalini Singh"),
    ("Visions of Heat", "Nalini Singh"),
    ("Kiss of Midnight", "Lara Adrian"),
    ("Darkfever", "Karen Marie Moning"),
    ("Bloodfever", "Karen Marie Moning"),
    ("Faefever", "Karen Marie Moning"),
    ("Dreamfever", "Karen Marie Moning"),
    ("Shadowfever", "Karen Marie Moning"),
    ("Pleasure Unbound", "Larissa Ione"),
    ("Demon Angel", "Meljean Brook"),
    ("Dragon Bound", "Thea Harrison"),
    ("Storm's Heart", "Thea Harrison"),
    ("A Hunger Like No Other", "Kresley Cole"),
    ("No Rest for the Wicked", "Kresley Cole"),
    ("The Warlord Wants Forever", "Kresley Cole"),
    ("Dark Prince", "Christine Feehan"),
    ("Dark Desire", "Christine Feehan"),
    ("Dark Magic", "Christine Feehan"),
    ("Night Pleasures", "Sherrilyn Kenyon"),
    ("Night Embrace", "Sherrilyn Kenyon"),
    ("Fantasy Lover", "Sherrilyn Kenyon"),
    ("Guilty Pleasures", "Laurell K. Hamilton"),
    ("The Laughing Corpse", "Laurell K. Hamilton"),
    ("The Vampire's Mail Order Bride", "Kristen Painter"),
    ("Hot Blooded", "Heather Guerre"),
    ("Pack of Lies", "Charlie Adhara"),
    ("Wolf Gone Wild", "Juliette Cross"),
    ("Feral Sins", "Suzanne Wright"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# MM ROMANCE (40)
# ═══════════════════════════════════════════════════════════════════════════════
MM_ROMANCE = [
    ("Red, White & Royal Blue", "Casey McQuiston"),
    ("Him", "Sarina Bowen & Elle Kennedy"),
    ("Us", "Sarina Bowen & Elle Kennedy"),
    ("Heated Rivalry", "Rachel Reid"),
    ("The Long Game", "Rachel Reid"),
    ("Boyfriend Material", "Alexis Hall"),
    ("Husband Material", "Alexis Hall"),
    ("Captive Prince", "C. S. Pacat"),
    ("Prince's Gambit", "C. S. Pacat"),
    ("Kings Rising", "C. S. Pacat"),
    ("The Charm Offensive", "Alison Cochrun"),
    ("We Could Be So Good", "Cat Sebastian"),
    ("You & Me", "Tal Bauer"),
    ("Gravity", "Tal Bauer"),
    ("The House in the Cerulean Sea", "T. J. Klune"),
    ("Wolfsong", "T. J. Klune"),
    ("Ravensong", "T. J. Klune"),
    ("Heartsong", "T. J. Klune"),
    ("Brothersong", "T. J. Klune"),
    ("Top Secret", "Sarina Bowen & Elle Kennedy"),
    ("Wanted, A Gentleman", "K. J. Charles"),
    ("The Magpie Lord", "K. J. Charles"),
    ("A Seditious Affair", "K. J. Charles"),
    ("Slippery Creatures", "K. J. Charles"),
    ("Glitterland", "Alexis Hall"),
    ("For Real", "Alexis Hall"),
    ("A Marvellous Light", "Freya Marske"),
    ("A Restless Truth", "Freya Marske"),
    ("The Lightning-Struck Heart", "T. J. Klune"),
    ("Blindsided", "Eden Finley"),
    ("Fake Out", "Eden Finley"),
    ("Try", "Ella Frank"),
    ("Take", "Ella Frank"),
    ("Fool Hearts", "Emmy Sanders"),
    ("Malum Discordiae", "Ashlyn Drewek"),
    ("Just a Bit Wrecked", "Alessandra Hazard"),
    ("Just a Bit Twisted", "Alessandra Hazard"),
    ("Garron Park", "Nordika Night"),
    ("Lot 62", "Nordika Night"),
    ("Crossroads", "Riley Hart"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# FF ROMANCE (20)
# ═══════════════════════════════════════════════════════════════════════════════
FF_ROMANCE = [
    ("The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid"),
    ("Delilah Green Doesn't Care", "Ashley Herring Blake"),
    ("Astrid Parker Doesn't Fail", "Ashley Herring Blake"),
    ("Iris Kelly Doesn't Date", "Ashley Herring Blake"),
    ("One Last Stop", "Casey McQuiston"),
    ("Written in the Stars", "Alexandria Bellefleur"),
    ("Count Your Lucky Stars", "Alexandria Bellefleur"),
    ("Hang the Moon", "Alexandria Bellefleur"),
    ("The Fiancée Farce", "Alexandria Bellefleur"),
    ("Something to Talk About", "Meryl Wilsner"),
    ("Mistakes Were Made", "Meryl Wilsner"),
    ("Kiss Her Once for Me", "Alison Cochrun"),
    ("D'Vaughn and Kris Plan a Wedding", "Chencia C. Higgins"),
    ("The Bright Falls Series", "Lana Harper"),
    ("Payback's a Witch", "Lana Harper"),
    ("She Gets the Girl", "Rachael Lippincott & Alyson Derrick"),
    ("Milk Fed", "Melissa Broder"),
    ("The Priory of the Orange Tree", "Samantha Shannon"),
    ("A Day of Fallen Night", "Samantha Shannon"),
    ("When You Least Expect It", "Haley Cass"),
    ("Those Who Wait", "Haley Cass"),
    ("The Lady's Guide to Celestial Mechanics", "Olivia Waite"),
    ("The Care and Feeding of Waspish Widows", "Olivia Waite"),
    ("The Henna Wars", "Adiba Jaigirdar"),
    ("Hani and Ishu's Guide to Fake Dating", "Adiba Jaigirdar"),
    ("This Is How You Lose the Time War", "Amal El-Mohtar & Max Gladstone"),
    ("Last Night at the Telegraph Club", "Malinda Lo"),
    ("A Scatter of Light", "Malinda Lo"),
    ("The Love Curse of Melody McIntyre", "Robin Talley"),
    ("Music from Another World", "Robin Talley"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# SPORTS ROMANCE (30)
# ═══════════════════════════════════════════════════════════════════════════════
SPORTS_ROMANCE = [
    ("Mile High", "Liz Tomforde"),
    ("The Right Move", "Liz Tomforde"),
    ("Caught Up", "Liz Tomforde"),
    ("Play With Me", "Liz Tomforde"),
    ("Kulti", "Mariana Zapata"),
    ("The Wall of Winnipeg and Me", "Mariana Zapata"),
    ("From Lukov with Love", "Mariana Zapata"),
    ("The Deal", "Elle Kennedy"),
    ("The Mistake", "Elle Kennedy"),
    ("The Score", "Elle Kennedy"),
    ("The Goal", "Elle Kennedy"),
    ("Pucking Around", "Emily Rath"),
    ("Pucking Wild", "Emily Rath"),
    ("Behind the Net", "Stephanie Archer"),
    ("The Fake Out", "Stephanie Archer"),
    ("Binding 13", "Chloe Walsh"),
    ("Keeping 13", "Chloe Walsh"),
    ("Icebreaker", "Hannah Grace"),
    ("Wildfire", "Hannah Grace"),
    ("Daydream", "Hannah Grace"),
    ("Blind Side", "Kandi Steiner"),
    ("Fair Catch", "Kandi Steiner"),
    ("Collide", "Bal Khabra"),
    ("The Long Game", "Elena Armas"),
    ("Consider Me", "Becka Mack"),
    ("Play With Me", "Becka Mack"),
    ("Unravel Me", "Becka Mack"),
    ("Body Check", "Teagan Hunter"),
    ("One-Timer", "Teagan Hunter"),
    ("Hothead", "Stella Rhys"),
    ("Dirty Deeds", "Stella Rhys"),
    ("The End Zone", "L. J. Shen"),
    ("Sin Bin", "Teagan Hunter"),
    ("Puck Me Secretly", "Odette Stone"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# SMALL TOWN ROMANCE (20)
# ═══════════════════════════════════════════════════════════════════════════════
SMALL_TOWN_ROMANCE = [
    ("It Happened One Summer", "Tessa Bailey"),
    ("Hook, Line, and Sinker", "Tessa Bailey"),
    ("Part of Your World", "Abby Jimenez"),
    ("Yours Truly", "Abby Jimenez"),
    ("Things We Never Got Over", "Lucy Score"),
    ("Things We Hide from the Light", "Lucy Score"),
    ("Things We Left Behind", "Lucy Score"),
    ("Well Met", "Jen DeLuca"),
    ("Well Played", "Jen DeLuca"),
    ("Well Matched", "Jen DeLuca"),
    ("The Simple Wild", "K. A. Tucker"),
    ("Wild at Heart", "K. A. Tucker"),
    ("Archer's Voice", "Mia Sheridan"),
    ("In the Weeds", "B. K. Borison"),
    ("Lovelight Farms", "B. K. Borison"),
    ("Welcome to Temptation", "Jennifer Crusie"),
    ("All Rhodes Lead Here", "Mariana Zapata"),
    ("Wait for It", "Mariana Zapata"),
    ("Practice Makes Perfect", "Sarah Adams"),
    ("When in Rome", "Sarah Adams"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# DARK BULLY / STALKER ROMANCE (30)
# ═══════════════════════════════════════════════════════════════════════════════
DARK_BULLY_STALKER_ROMANCE = [
    ("Lords of Pain", "Angel Lawson & Samantha Rue"),
    ("Lords of Wrath", "Angel Lawson & Samantha Rue"),
    ("Lords of Mercy", "Angel Lawson & Samantha Rue"),
    ("Lords of Chaos", "Angel Lawson & Samantha Rue"),
    ("Punk 57", "Penelope Douglas"),
    ("Bully", "Penelope Douglas"),
    ("Rival", "Penelope Douglas"),
    ("Until You", "Penelope Douglas"),
    ("Vicious", "L. J. Shen"),
    ("Ruckus", "L. J. Shen"),
    ("Scandalous", "L. J. Shen"),
    ("Bane", "L. J. Shen"),
    ("Corrupt", "Penelope Douglas"),
    ("Hideaway", "Penelope Douglas"),
    ("Kill Switch", "Penelope Douglas"),
    ("Fear Me", "B. B. Reid"),
    ("Break Me", "B. B. Reid"),
    ("Cruel Prince", "Ashley Jade"),
    ("The Peer and the Puppet", "B. B. Reid"),
    ("Merciless Knave", "E. M. Moore"),
    ("Break Her", "B. G. Harlen"),
    ("Creep", "Marie Ann"),
    ("The Boy on the Bridge", "Sam Mariano"),
    ("Even If It Hurts", "Sam Mariano"),
    ("Descent", "Sam Mariano"),
    ("Stolen Touches", "Neva Altaj"),
    ("Hidden Truths", "Neva Altaj"),
    ("Fractured Souls", "Neva Altaj"),
    ("Psycho Academy", "Jasmine Mas"),
    ("Angry God", "L. J. Shen"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# BILLIONAIRE / WORKPLACE / OFFICE ROMANCE (20)
# ═══════════════════════════════════════════════════════════════════════════════
BILLIONAIRE_WORKPLACE_ROMANCE = [
    ("Beautiful Bastard", "Christina Lauren"),
    ("Beautiful Stranger", "Christina Lauren"),
    ("Throttled", "Lauren Asher"),
    ("Collided", "Lauren Asher"),
    ("Wrecked", "Lauren Asher"),
    ("Redeemed", "Lauren Asher"),
    ("The Stopover", "T.L. Swan"),
    ("The Takeover", "T. L. Swan"),
    ("The Casanova", "T. L. Swan"),
    ("The Do-Over", "T. L. Swan"),
    ("By a Thread", "Lucy Score"),
    ("The Christmas Fix", "Lucy Score"),
    ("Managed", "Kristen Callihan"),
    ("Idol", "Kristen Callihan"),
    ("Fall", "Kristen Callihan"),
    ("The Fine Print", "Lauren Asher"),
    ("Terms and Conditions", "Lauren Asher"),
    ("Final Offer", "Lauren Asher"),
    ("A Not So Meet Cute", "Meghan Quinn"),
    ("So Not Meant to Be", "Meghan Quinn"),
    ("The Favor", "Suzanne Wright"),
    ("Reckless", "Stella Rhys"),
    ("Brooklynaire", "Sarina Bowen"),
]

# ═══════════════════════════════════════════════════════════════════════════════
# MASTER LIST — all subgenres flattened into one list with subgenre labels
# ═══════════════════════════════════════════════════════════════════════════════

# ── Dark Reverse Harem (thin cluster expansion) ─────────────────────────
DARK_REVERSE_HAREM = [
    ("Den of Vipers", "K.A. Knight"),
    ("Lords of Pain", "Angel Lawson & Samantha Rue"),
    ("Lords of Wrath", "Angel Lawson & Samantha Rue"),
    ("Hannaford Prep", "J. Bree"),
    ("Broken Bonds", "J. Bree"),
    ("Savage Vandal", "Heather Long"),
    ("Kings of Quarantine", "Caroline Peckham & Susanne Valenti"),
    ("The Death Club", "Caroline Peckham & Susanne Valenti"),
    ("Faking with Benefits", "Lily Gold"),
    ("Three Swedish Mountain Men", "Lily Gold"),
    ("Pacific Heat", "Dakota Cassidy"),
    ("Beautiful Fiend", "Lola King"),
    ("Corrupt", "Penelope Douglas"),
    ("Bully", "Penelope Douglas"),
    ("Filthy Rich Boys", "C.M. Stunich"),
    ("Mad Girl", "C.M. Stunich"),
    ("The Never King", "Nikki St. Crowe"),
    ("The Dark One", "Nikki St. Crowe"),
    ("Sinners of Saint", "L.J. Shen"),
    ("Vicious", "L.J. Shen"),
    ("The Ritual", "Shantel Tessier"),
]

# ── Bodyguard Romance (thin cluster expansion) ──────────────────────────
BODYGUARD_ROMANCE = [
    ("Twisted Games", "Ana Huang"),
    ("The Protector", "Elise Faber"),
    ("Girl Gone Viral", "Alisha Rai"),
    ("The Bodyguard", "Katherine Center"),
    ("Protecting Piper", "Cynthia Eden"),
    ("Close Protection", "Cordelia Blanc"),
    ("The Hitman's Guide to Making Friends", "Alice Winters"),
    ("The Professional", "Kresley Cole"),
    ("The Master", "Kresley Cole"),
    ("Royally Endowed", "Emma Chase"),
    ("Guarding Temptation", "Talia Hibbert"),
    ("Protecting What's His", "Tessa Bailey"),
    ("Officer Off Limits", "Tessa Bailey"),
    ("Broken Vows", "Stella Gray"),
    ("The Enforcer", "Avery Keelan"),
    ("Defending Morgan", "A.K. Evans"),
    ("Guarding Gwen", "A.K. Evans"),
    ("Protected by the Possessive Bodyguard", "Jade King"),
]

# ── Surprise Pregnancy (thin cluster expansion) ─────────────────────────
SURPRISE_PREGNANCY = [
    ("The Goal", "Elle Kennedy"),
    ("One Moment Please", "Amy Daws"),
    ("Wait for It", "Mariana Zapata"),
    ("Luna and the Lie", "Mariana Zapata"),
    ("Bountiful", "Sarina Bowen"),
    ("Tru Blue", "Melissa Foster"),
    ("Forever My Girl", "Heidi McLaughlin"),
    ("When Ashes Fall", "Marni Mann"),
    ("Outmatched", "Kristen Callihan & Samantha Young"),
    ("Getting Played", "Emma Chase"),
    ("The Baby Clause", "Melanie Moreland"),
    ("Mr. Masters", "T.L. Swan"),
    ("Baby Mine", "Kennedy Fox"),
    ("The Bombshell Effect", "Karla Sorensen"),
    ("Unraveled", "Helen Hardt"),
    ("More Than a Memory", "Marie James"),
    ("Accidental Pregnancy", "Lilian Monroe"),
    ("Unplanned", "Lilian Monroe"),
    ("Baby Daddy", "Nadia Lee"),
    ("Dr. Stanton", "T.L. Swan"),
]

# ── One Bed (thin cluster expansion) ────────────────────────────────────
ONE_BED = [
    ("Managed", "Kristen Callihan"),
    ("The Unhoneymooners", "Christina Lauren"),
    ("Roommates", "Christina Lauren"),
    ("The Flatshare", "Beth O'Leary"),
    ("The Road Trip", "Beth O'Leary"),
    ("Josh and Hazel's Guide to Not Dating", "Christina Lauren"),
    ("The Hating Game", "Sally Thorne"),
    ("The Kiss Quotient", "Helen Hoang"),
    ("The Bride Test", "Helen Hoang"),
    ("People We Meet on Vacation", "Emily Henry"),
    ("Book Lovers", "Emily Henry"),
    ("You Deserve Each Other", "Sarah Hogle"),
    ("Twice Shy", "Sarah Hogle"),
    ("The Spanish Love Deception", "Elena Armas"),
    ("The American Roommate Experiment", "Elena Armas"),
    ("Mr. Wrong Number", "Lynn Painter"),
    ("The Love Hypothesis", "Ali Hazelwood"),
    ("Love on the Brain", "Ali Hazelwood"),
    ("The Soulmate Equation", "Christina Lauren"),
    ("The Unwanted Wife", "Natasha Anders"),
    ("Beach Read", "Emily Henry"),
    ("Happy Place", "Emily Henry"),
    ("It Happened One Summer", "Tessa Bailey"),
    ("Hook Line and Sinker", "Tessa Bailey"),
    ("Fix Her Up", "Tessa Bailey"),
    ("The Kiss Thief", "L.J. Shen"),
    ("Sparrow", "L.J. Shen"),
    ("Beautiful Bastard", "Christina Lauren"),
    ("Beautiful Stranger", "Christina Lauren"),
    ("Waking Olivia", "Elizabeth O'Roark"),
]

# ── Roommate Romance (thin cluster expansion) ───────────────────────────
ROOMMATE_ROMANCE = [
    ("Roommate", "Sarina Bowen"),
    ("The Roommate Risk", "Talia Hibbert"),
    ("Get a Life Chloe Brown", "Talia Hibbert"),
    ("The Roommate", "Rosie Danan"),
    ("The Intimacy Experiment", "Rosie Danan"),
    ("Wallbanger", "Alice Clayton"),
    ("Neanderthal Seeks Human", "Penny Reid"),
    ("Neanderthal Marries Human", "Penny Reid"),
    ("Roomies", "Christina Lauren"),
    ("My Favorite Half-Night Stand", "Christina Lauren"),
    ("The Pact", "Karina Halle"),
    ("The Roommate Arrangement", "Kristen Echols"),
    ("The Virgin Romance Novelist", "Meghan Quinn"),
    ("Co-Wrecker", "Meghan Quinn"),
    ("Shared", "Lily Harlem"),
    ("Three Simple Rules", "Nikki Sloane"),
    ("Three Hard Lessons", "Nikki Sloane"),
    ("Blindsided", "Amy Daws"),
    ("Challenge", "Amy Daws"),
    ("Undecided", "Julianna Keyes"),
    ("Undeniably You", "Jewel E. Ann"),
    ("Flat-Out Love", "Jessica Park"),
    ("Flat-Out Celeste", "Jessica Park"),
    ("Housemates", "Emma Hart"),
    ("The Off-Campus Setup", "Lacey Black"),
]

# ── Cozy Romance (thin cluster expansion) ───────────────────────────────
COZY_ROMANCE = [
    ("The Bookshop on the Corner", "Jenny Colgan"),
    ("The Little Beach Street Bakery", "Jenny Colgan"),
    ("The Switch", "Beth O'Leary"),
    ("The Lost for Words Bookshop", "Stephanie Butland"),
    ("The Hygge Holiday", "Rosie Blake"),
    ("The Little Village of Happiness", "Holly Martin"),
    ("Sunrise over Sapphire Bay", "Holly Martin"),
    ("The Little Wedding Shop by the Sea", "Jane Linfoot"),
    ("The Cosy Cottage in Ireland", "Julie Caplin"),
    ("The Little Paris Bookshop", "Nina George"),
    ("The Readers of Broken Wheel Recommend", "Katarina Bivald"),
    ("The Storied Life of A.J. Fikry", "Gabrielle Zevin"),
    ("Tomorrow and Tomorrow and Tomorrow", "Gabrielle Zevin"),
    ("The Lost Apothecary", "Sarah Penner"),
    ("The Book Charmer", "Karen Hawkins"),
    ("A Cup of Silver Linings", "Karen Hawkins"),
    ("The Library of Lost and Found", "Phaedra Patrick"),
    ("The Curious Charms of Arthur Pepper", "Phaedra Patrick"),
    ("The Bookshop on the Shore", "Jenny Colgan"),
    ("500 Miles from You", "Jenny Colgan"),
    ("Aria's Travelling Book Shop", "Rebecca Raisin"),
    ("The Little Perfume Shop off the Champs-Elysees", "Rebecca Raisin"),
    ("The Little Theatre by the Sea", "Rosanna Ley"),
    ("The Lemon Tree Cafe", "Cathy Bramley"),
    ("Ivy Lane", "Cathy Bramley"),
    ("Mamma Mia! It's Only the Beginning", "Anna Premoli"),
    ("The Twenty-One-Year Contract", "Emma Davies"),
    ("One Summer in Santorini", "Sandy Barker"),
    ("Summer at the Little French Guesthouse", "Helen Pollard"),
    ("The Bookshop of Second Chances", "Jackie Fraser"),
]

# ── Rivals to Lovers (thin cluster expansion) ───────────────────────────
RIVALS_TO_LOVERS = [
    ("The Hating Game", "Sally Thorne"),
    ("Red, White & Royal Blue", "Casey McQuiston"),
    ("The Unhoneymooners", "Christina Lauren"),
    ("Dating You Hating You", "Christina Lauren"),
    ("The Spanish Love Deception", "Elena Armas"),
    ("The Love Hypothesis", "Ali Hazelwood"),
    ("Love Theoretically", "Ali Hazelwood"),
    ("Beach Read", "Emily Henry"),
    ("Book Lovers", "Emily Henry"),
    ("You Deserve Each Other", "Sarah Hogle"),
    ("Enemies with Benefits", "Roxie Noir"),
    ("The Rivals", "Vi Keeland"),
    ("The Stopover", "T.L. Swan"),
    ("Dirty Headlines", "L.J. Shen"),
    ("The Wall of Winnipeg and Me", "Mariana Zapata"),
    ("Kulti", "Mariana Zapata"),
    ("Anything You Can Do", "R.S. Grey"),
    ("Arrogant Devil", "R.S. Grey"),
    ("The Rivalry", "Nikki Sloane"),
    ("The Best Man", "Kristan Higgins"),
    ("Practice Makes Perfect", "Sarah Adams"),
    ("The Cheat Sheet", "Sarah Adams"),
    ("Shipped", "Angie Hockman"),
    ("Meet You in the Middle", "Devon Daniels"),
    ("A Not So Meet Cute", "Meghan Quinn"),
    ("So Not Meant to Be", "Meghan Quinn"),
    ("The Enemy", "Sarah Adams"),
    ("The Worst Guy", "Kate Canterbary"),
    ("Before Girl", "Kate Canterbary"),
    ("Against a Wall", "Cate C. Wells"),
    ("Hitting the Wall", "Cate C. Wells"),
    ("Enemies Abroad", "R.S. Grey"),
    ("Fight or Flight", "Samantha Young"),
    ("Much Ado About You", "Samantha Young"),
    ("The Simple Wild", "K.A. Tucker"),
    ("Wild at Heart", "K.A. Tucker"),
    ("Shortcake", "Lucy Watson"),
    ("By a Thread", "Lucy Score"),
    ("Things We Never Got Over", "Lucy Score"),
]

ROMANCE_SEED_BOOKS = {
    "Dark Romance": DARK_ROMANCE,
    "Contemporary Romance": CONTEMPORARY_ROMANCE,
    "Romantasy": ROMANTASY,
    "Historical Romance": HISTORICAL_ROMANCE,
    "Paranormal Romance": PARANORMAL_ROMANCE,
    "MM Romance": MM_ROMANCE,
    "FF Romance": FF_ROMANCE,
    "Sports Romance": SPORTS_ROMANCE,
    "Small Town Romance": SMALL_TOWN_ROMANCE,
    "Dark Bully / Stalker Romance": DARK_BULLY_STALKER_ROMANCE,
    "Billionaire / Workplace / Office Romance": BILLIONAIRE_WORKPLACE_ROMANCE,
    # ── Thin cluster expansions ───────────────────────────────────────────
    "Dark Reverse Harem": DARK_REVERSE_HAREM,
    "Bodyguard Romance": BODYGUARD_ROMANCE,
    "Surprise Pregnancy": SURPRISE_PREGNANCY,
    "One Bed": ONE_BED,
    "Roommate Romance": ROOMMATE_ROMANCE,
    "Cozy Romance": COZY_ROMANCE,
    "Rivals to Lovers": RIVALS_TO_LOVERS,
}

# Verify counts at import time
if __name__ == "__main__":
    total = 0
    for genre, books in ROMANCE_SEED_BOOKS.items():
        count = len(books)
        total += count
        print(f"{genre}: {count}")
    print(f"TOTAL: {total}")
