"""
Sci-Fi Microtrope Seed Catalog — ~300 books across 14 clusters.
Strategy: deep author coverage per cluster, max 2 books per author total.
"""

SCIFI_MICROTROPE_CLUSTERS = {
    # ── First Contact + Hard Sci-Fi ───────────────────────────────────────
    "First Contact + Hard Sci-Fi": [
        ("Rendezvous with Rama", "Arthur C. Clarke"),
        ("Contact", "Carl Sagan"),
        ("The Three-Body Problem", "Cixin Liu"),
        ("The Dark Forest", "Cixin Liu"),
        ("Blindsight", "Peter Watts"),
        ("Echopraxia", "Peter Watts"),
        ("Story of Your Life and Others", "Ted Chiang"),
        ("Exhalation", "Ted Chiang"),
        ("The Mote in God's Eye", "Larry Niven"),
        ("Footfall", "Larry Niven"),
        ("Childhood's End", "Arthur C. Clarke"),
        ("Solaris", "Stanislaw Lem"),
        ("His Master's Voice", "Stanislaw Lem"),
        ("The Sparrow", "Mary Doria Russell"),
        ("Children of God", "Mary Doria Russell"),
        ("Gateway", "Frederik Pohl"),
        ("A Fire Upon the Deep", "Vernor Vinge"),
        ("A Deepness in the Sky", "Vernor Vinge"),
        ("Arrival", "Ted Chiang"),
        ("The Forge of God", "Greg Bear"),
    ],
    # ── AI & Consciousness + Speculative Philosophical ────────────────────
    "AI & Consciousness": [
        ("Klara and the Sun", "Kazuo Ishiguro"),
        ("Never Let Me Go", "Kazuo Ishiguro"),
        ("Ancillary Justice", "Ann Leckie"),
        ("Ancillary Sword", "Ann Leckie"),
        ("All Systems Red", "Martha Wells"),
        ("Artificial Condition", "Martha Wells"),
        ("Do Androids Dream of Electric Sheep", "Philip K. Dick"),
        ("Ubik", "Philip K. Dick"),
        ("I Robot", "Isaac Asimov"),
        ("Foundation", "Isaac Asimov"),
        ("Neuromancer", "William Gibson"),
        ("Count Zero", "William Gibson"),
        ("A Closed and Common Orbit", "Becky Chambers"),
        ("Record of a Spaceborn Few", "Becky Chambers"),
        ("Autonomous", "Annalee Newitz"),
        ("The Terraformers", "Annalee Newitz"),
        ("Machinehood", "S.B. Divya"),
        ("The Prefect", "Alastair Reynolds"),
        ("Chasm City", "Alastair Reynolds"),
        ("Walkaway", "Cory Doctorow"),
    ],
    # ── Post-Apocalyptic + Survival ───────────────────────────────────────
    "Post-Apocalyptic + Survival": [
        ("The Road", "Cormac McCarthy"),
        ("Station Eleven", "Emily St. John Mandel"),
        ("Sea of Tranquility", "Emily St. John Mandel"),
        ("Oryx and Crake", "Margaret Atwood"),
        ("The Year of the Flood", "Margaret Atwood"),
        ("A Canticle for Leibowitz", "Walter M. Miller Jr."),
        ("The Postman", "David Brin"),
        ("The Stand", "Stephen King"),
        ("The Dog Stars", "Peter Heller"),
        ("The Last", "Hanna Jameson"),
        ("Severance", "Ling Ma"),
        ("Good Morning Midnight", "Lily Brooks-Dalton"),
        ("The Book of the Unnamed Midwife", "Meg Elison"),
        ("Alas Babylon", "Pat Frank"),
        ("On the Beach", "Nevil Shute"),
        ("Earth Abides", "George R. Stewart"),
        ("The Death of Grass", "John Christopher"),
        ("Parable of the Sower", "Octavia Butler"),
        ("Parable of the Talents", "Octavia Butler"),
        ("The Girl with All the Gifts", "M.R. Carey"),
    ],
    # ── Space Opera + Action-Driven ───────────────────────────────────────
    "Space Opera + Action": [
        ("Leviathan Wakes", "James S.A. Corey"),
        ("Caliban's War", "James S.A. Corey"),
        ("Dune", "Frank Herbert"),
        ("Endymion", "Dan Simmons"),
        ("Revelation Space", "Alastair Reynolds"),
        ("Children of Time", "Adrian Tchaikovsky"),
        ("Children of Ruin", "Adrian Tchaikovsky"),
        ("A Memory Called Empire", "Arkady Martine"),
        ("A Desolation Called Peace", "Arkady Martine"),
        ("The Collapsing Empire", "John Scalzi"),
        ("Old Man's War", "John Scalzi"),
        ("Consider Phlebas", "Iain M. Banks"),
        ("The Player of Games", "Iain M. Banks"),
        ("House of Suns", "Alastair Reynolds"),
        ("Pandora's Star", "Peter F. Hamilton"),
        ("Judas Unchained", "Peter F. Hamilton"),
        ("The Forever War", "Joe Haldeman"),
        ("Old Man's War", "John Scalzi"),
        ("Ancillary Mercy", "Ann Leckie"),
        ("The Long Way to a Small Angry Planet", "Becky Chambers"),
    ],
    # ── Time Travel + Hard Sci-Fi ─────────────────────────────────────────
    "Time Travel + Hard Sci-Fi": [
        ("The Time Machine", "H.G. Wells"),
        ("Kindred", "Octavia Butler"),
        ("Recursion", "Blake Crouch"),
        ("Dark Matter", "Blake Crouch"),
        ("11/22/63", "Stephen King"),
        ("The First Fifteen Lives of Harry August", "Claire North"),
        ("Replay", "Ken Grimwood"),
        ("All You Need Is Kill", "Hiroshi Sakurazaka"),
        ("The Man Who Folded Himself", "David Gerrold"),
        ("How to Live Safely in a Science Fictional Universe", "Charles Yu"),
        ("Interior Chinatown", "Charles Yu"),
        ("Doomsday Book", "Connie Willis"),
        ("To Say Nothing of the Dog", "Connie Willis"),
        ("The Gone World", "Tom Sweterlitsch"),
        ("Tomorrow and Tomorrow", "Tom Sweterlitsch"),
        ("The Shining Girls", "Lauren Beukes"),
        ("Broken Monsters", "Lauren Beukes"),
        ("Version Control", "Dexter Palmer"),
        ("The Anubis Gates", "Tim Powers"),
        ("Slaughterhouse-Five", "Kurt Vonnegut"),
    ],
    # ── Alien Civilization + Space Opera ──────────────────────────────────
    "Alien Civilization + Space Opera": [
        ("The Left Hand of Darkness", "Ursula K. Le Guin"),
        ("The Dispossessed", "Ursula K. Le Guin"),
        ("A Memory Called Empire", "Arkady Martine"),
        ("Embassytown", "China Mieville"),
        ("The City We Became", "China Mieville"),
        ("Ancillary Justice", "Ann Leckie"),
        ("Lilith's Brood", "Octavia Butler"),
        ("Fledgling", "Octavia Butler"),
        ("Foreigner", "C.J. Cherryh"),
        ("Downbelow Station", "C.J. Cherryh"),
        ("Speaker for the Dead", "Orson Scott Card"),
        ("Ender's Game", "Orson Scott Card"),
        ("Babel-17", "Samuel R. Delany"),
        ("Stars in My Pocket Like Grains of Sand", "Samuel R. Delany"),
        ("Grass", "Sheri S. Tepper"),
        ("The Fresco", "Sheri S. Tepper"),
        ("A Desolation Called Peace", "Arkady Martine"),
        ("A Memory Called Empire", "Arkady Martine"),
        ("The Sparrow", "Mary Doria Russell"),
        ("Dawn", "Octavia Butler"),
    ],
    # ── Cyberpunk + Corporate Dystopia ────────────────────────────────────
    "Cyberpunk + Corporate Dystopia": [
        ("Neuromancer", "William Gibson"),
        ("Snow Crash", "Neal Stephenson"),
        ("Diamond Age", "Neal Stephenson"),
        ("Altered Carbon", "Richard K. Morgan"),
        ("Broken Angels", "Richard K. Morgan"),
        ("Do Androids Dream of Electric Sheep", "Philip K. Dick"),
        ("A Scanner Darkly", "Philip K. Dick"),
        ("The Windup Girl", "Paolo Bacigalupi"),
        ("The Water Knife", "Paolo Bacigalupi"),
        ("Hardwired", "Walter Jon Williams"),
        ("Voice of the Whirlwind", "Walter Jon Williams"),
        ("Jennifer Government", "Max Barry"),
        ("Company", "Max Barry"),
        ("Rainbows End", "Vernor Vinge"),
        ("Daemon", "Daniel Suarez"),
        ("Freedom", "Daniel Suarez"),
        ("Infinite Detail", "Tim Maughan"),
        ("The Fortunate Fall", "Raphael Carter"),
        ("Islands in the Net", "Bruce Sterling"),
        ("Schismatrix", "Bruce Sterling"),
    ],
    # ── Biotech + Cli-Fi ──────────────────────────────────────────────────
    "Biotech + Cli-Fi": [
        ("The Windup Girl", "Paolo Bacigalupi"),
        ("Oryx and Crake", "Margaret Atwood"),
        ("The Year of the Flood", "Margaret Atwood"),
        ("Annihilation", "Jeff VanderMeer"),
        ("Borne", "Jeff VanderMeer"),
        ("The Ministry for the Future", "Kim Stanley Robinson"),
        ("New York 2140", "Kim Stanley Robinson"),
        ("The Drowned World", "J.G. Ballard"),
        ("The Crystal World", "J.G. Ballard"),
        ("Flood", "Stephen Baxter"),
        ("Ark", "Stephen Baxter"),
        ("The Sheep Look Up", "John Brunner"),
        ("Stand on Zanzibar", "John Brunner"),
        ("Blood Music", "Greg Bear"),
        ("Darwin's Radio", "Greg Bear"),
        ("The Rift", "Walter Jon Williams"),
        ("The Last Ship", "William Brinkley"),
        ("Gold Fame Citrus", "Claire Vaye Watkins"),
        ("Migrations", "Charlotte McConaghy"),
        ("Once There Were Wolves", "Charlotte McConaghy"),
    ],
    # ── Military Sci-Fi + Hard Sci-Fi ─────────────────────────────────────
    "Military Sci-Fi + Hard": [
        ("The Forever War", "Joe Haldeman"),
        ("Starship Troopers", "Robert A. Heinlein"),
        ("The Moon Is a Harsh Mistress", "Robert A. Heinlein"),
        ("Old Man's War", "John Scalzi"),
        ("The Ghost Brigades", "John Scalzi"),
        ("Armor", "John Steakley"),
        ("Ender's Game", "Orson Scott Card"),
        ("Ender's Shadow", "Orson Scott Card"),
        ("Frontlines", "Marko Kloos"),
        ("Terms of Enlistment", "Marko Kloos"),
        ("The Last Watch", "J.S. Dewes"),
        ("The Exiled Fleet", "J.S. Dewes"),
        ("The Human Division", "John Scalzi"),
        ("Redshirts", "John Scalzi"),
        ("Hammer's Slammers", "David Drake"),
        ("The Warrior's Apprentice", "Lois McMaster Bujold"),
        ("Shards of Honor", "Lois McMaster Bujold"),
        ("Valor's Choice", "Tanya Huff"),
        ("The Better Part of Valor", "Tanya Huff"),
        ("The Light Brigade", "Kameron Hurley"),
    ],
    # ── Near-Future + Solarpunk ───────────────────────────────────────────
    "Near-Future + Solarpunk": [
        ("The Ministry for the Future", "Kim Stanley Robinson"),
        ("2312", "Kim Stanley Robinson"),
        ("A Psalm for the Wild-Built", "Becky Chambers"),
        ("A Prayer for the Crown-Shy", "Becky Chambers"),
        ("Walkaway", "Cory Doctorow"),
        ("Little Brother", "Cory Doctorow"),
        ("To Be Taught If Fortunate", "Becky Chambers"),
        ("The Future", "Naomi Alderman"),
        ("The Power", "Naomi Alderman"),
        ("Autonomous", "Annalee Newitz"),
        ("The Terraformers", "Annalee Newitz"),
        ("Gamechanger", "L.X. Beckett"),
        ("Dealbreaker", "L.X. Beckett"),
        ("The Resisters", "Gish Jen"),
        ("Waste Tide", "Chen Qiufan"),
        ("Zodiac", "Neal Stephenson"),
        ("Termination Shock", "Neal Stephenson"),
        ("The Warehouse", "Rob Hart"),
        ("Qualityland", "Marc-Uwe Kling"),
        ("Void Star", "Zachary Mason"),
    ],
    # ── Space Exploration + Hard Sci-Fi ───────────────────────────────────
    "Space Exploration + Hard": [
        ("The Martian", "Andy Weir"),
        ("Project Hail Mary", "Andy Weir"),
        ("Rendezvous with Rama", "Arthur C. Clarke"),
        ("2001 A Space Odyssey", "Arthur C. Clarke"),
        ("Red Mars", "Kim Stanley Robinson"),
        ("Blue Mars", "Kim Stanley Robinson"),
        ("Aurora", "Kim Stanley Robinson"),
        ("Seveneves", "Neal Stephenson"),
        ("Anathem", "Neal Stephenson"),
        ("The Fountains of Paradise", "Arthur C. Clarke"),
        ("Distress", "Greg Egan"),
        ("Permutation City", "Greg Egan"),
        ("Delta-V", "Daniel Suarez"),
        ("Critical Mass", "Daniel Suarez"),
        ("Tau Zero", "Poul Anderson"),
        ("The High Crusade", "Poul Anderson"),
        ("Artemis", "Andy Weir"),
        ("The Calculating Stars", "Mary Robinette Kowal"),
        ("The Fated Sky", "Mary Robinette Kowal"),
        ("To Sleep in a Sea of Stars", "Christopher Paolini"),
    ],
    # ── Generation Ship + Colony ──────────────────────────────────────────
    "Generation Ship + Colony": [
        ("Aurora", "Kim Stanley Robinson"),
        ("Record of a Spaceborn Few", "Becky Chambers"),
        ("Children of Time", "Adrian Tchaikovsky"),
        ("The Book of the Long Sun", "Gene Wolfe"),
        ("Noumenon", "Marina J. Lostetter"),
        ("Noumenon Ultra", "Marina J. Lostetter"),
        ("The Stars Are Legion", "Kameron Hurley"),
        ("The Light Brigade", "Kameron Hurley"),
        ("Hull Zero Three", "Greg Bear"),
        ("Eon", "Greg Bear"),
        ("Ship of Fools", "Richard Paul Russo"),
        ("The Death of Sleep", "Anne McCaffrey"),
        ("Braking Day", "Adam Oyebanji"),
        ("The Voyage of the Space Beagle", "A.E. van Vogt"),
        ("Orphans of the Sky", "Robert A. Heinlein"),
        ("Captive Universe", "Harry Harrison"),
        ("The Dream of Perpetual Motion", "Dexter Palmer"),
        ("Semiosis", "Sue Burke"),
        ("Interference", "Sue Burke"),
        ("The Outside", "Ada Hoffmann"),
    ],
    # ── Parallel Universe + Speculative ───────────────────────────────────
    "Parallel Universe + Speculative": [
        ("Dark Matter", "Blake Crouch"),
        ("The Long Earth", "Terry Pratchett"),
        ("The Long War", "Terry Pratchett"),
        ("The Space Between Worlds", "Micaiah Johnson"),
        ("The Doors of Eden", "Adrian Tchaikovsky"),
        ("The City and the Stars", "Arthur C. Clarke"),
        ("The Gods Themselves", "Isaac Asimov"),
        ("Slaughterhouse-Five", "Kurt Vonnegut"),
        ("The Sirens of Titan", "Kurt Vonnegut"),
        ("Transition", "Iain M. Banks"),
        ("The Algebraist", "Iain M. Banks"),
        ("The Freeze-Frame Revolution", "Peter Watts"),
        ("The Rift", "Nina Allan"),
        ("The Race", "Nina Allan"),
        ("The Man in the High Castle", "Philip K. Dick"),
        ("Flow My Tears the Policeman Said", "Philip K. Dick"),
        ("Neverwhere", "Neil Gaiman"),
        ("The Ocean at the End of the Lane", "Neil Gaiman"),
        ("The First Fifteen Lives of Harry August", "Claire North"),
        ("The Sudden Appearance of Hope", "Claire North"),
    ],
    # ── Hard Science Thriller ─────────────────────────────────────────────
    "Hard Science Thriller": [
        ("Project Hail Mary", "Andy Weir"),
        ("The Andromeda Strain", "Michael Crichton"),
        ("Jurassic Park", "Michael Crichton"),
        ("Sphere", "Michael Crichton"),
        ("Prey", "Michael Crichton"),
        ("Dark Matter", "Blake Crouch"),
        ("Recursion", "Blake Crouch"),
        ("The Apollo Murders", "Chris Hadfield"),
        ("The Defector", "Chris Hadfield"),
        ("Cold Storage", "David Koepp"),
        ("Aurora", "David Koepp"),
        ("Influx", "Daniel Suarez"),
        ("Daemon", "Daniel Suarez"),
        ("The Fold", "Peter Clines"),
        ("14", "Peter Clines"),
        ("Extinction Game", "Gary Gibson"),
        ("The Last Day", "Andrew Hunter Murray"),
        ("The Sanctuary", "Andrew Hunter Murray"),
        ("The Apollo Killer", "Chris Hadfield"),
        ("Eruption", "Michael Crichton"),
    ],
    # ── Solarpunk (thin cluster expansion) ────────────────────────────────
    "Solarpunk": [
        ("A Psalm for the Wild-Built", "Becky Chambers"),
        ("A Prayer for the Crown-Shy", "Becky Chambers"),
        ("The Terraformers", "Annalee Newitz"),
        ("Walkaway", "Cory Doctorow"),
        ("Sunvault", "Various"),
        ("Glass and Gardens", "Sarena Ulibarri"),
        ("Ecotopia", "Ernest Callenbach"),
        ("The Word for World Is Forest", "Ursula K. Le Guin"),
        ("The Dispossessed", "Ursula K. Le Guin"),
        ("New York 2140", "Kim Stanley Robinson"),
        ("The Ministry for the Future", "Kim Stanley Robinson"),
        ("The Fifth Sacred Thing", "Starhawk"),
        ("Infomocracy", "Malka Older"),
        ("Null States", "Malka Older"),
        ("The Summer Prince", "Alaya Dawn Johnson"),
        ("Wings of Renewal", "Various"),
        ("The City in the Middle of the Night", "Charlie Jane Anders"),
        ("Gamechanger", "L.X. Beckett"),
        ("Dealbreaker", "L.X. Beckett"),
    ],
    # ── Biopunk (thin cluster expansion) ──────────────────────────────────
    "Biopunk": [
        ("Oryx and Crake", "Margaret Atwood"),
        ("The Year of the Flood", "Margaret Atwood"),
        ("The Windup Girl", "Paolo Bacigalupi"),
        ("Ribofunk", "Paul Di Filippo"),
        ("Blood Music", "Greg Bear"),
        ("Beggars in Spain", "Nancy Kress"),
        ("Prey", "Michael Crichton"),
        ("Bios", "Robert Charles Wilson"),
        ("Darwin's Radio", "Greg Bear"),
        ("The Book of Joan", "Lidia Yuknavitch"),
        ("The Small Backs of Children", "Lidia Yuknavitch"),
        ("Schismatrix", "Bruce Sterling"),
        ("Holy Fire", "Bruce Sterling"),
        ("The Troop", "Nick Cutter"),
        ("The Deep", "Nick Cutter"),
        ("Annihilation", "Jeff VanderMeer"),
        ("The Water Knife", "Paolo Bacigalupi"),
        ("Nexus", "Ramez Naam"),
        ("Crux", "Ramez Naam"),
        ("The Bees", "Laline Paull"),
    ],
    # ── Quantum Sci-Fi (thin cluster expansion) ───────────────────────────
    "Quantum Sci-Fi": [
        ("Dark Matter", "Blake Crouch"),
        ("Recursion", "Blake Crouch"),
        ("The Gone World", "Tom Sweterlitsch"),
        ("Anathem", "Neal Stephenson"),
        ("Quarantine", "Greg Egan"),
        ("Permutation City", "Greg Egan"),
        ("Timeline", "Michael Crichton"),
        ("The Fold", "Peter Clines"),
        ("Paradox Bound", "Peter Clines"),
        ("The Space Between Worlds", "Micaiah Johnson"),
        ("Spin", "Robert Charles Wilson"),
        ("Axis", "Robert Charles Wilson"),
        ("Flashforward", "Robert J. Sawyer"),
        ("Calculating God", "Robert J. Sawyer"),
        ("The Quantum Thief", "Hannu Rajaniemi"),
        ("The Fractal Prince", "Hannu Rajaniemi"),
        ("Version Control", "Dexter Palmer"),
        ("The Shining Girls", "Lauren Beukes"),
        ("The First Fifteen Lives of Harry August", "Claire North"),
        ("Touch", "Claire North"),
    ],
}
