"""
Thriller Microtrope Seed Catalog — tight clusters of 15-20 books sharing dominant tropes.
Strategy: seed clusters that create dense Qdrant neighborhoods for specific query patterns.
"""

THRILLER_MICROTROPE_CLUSTERS = {
    # ── Psychological Thriller + Amnesia + Unreliable Narrator ──────────────
    "Amnesia + Unreliable Narrator": [
        ("Before I Go to Sleep", "S.J. Watson"),
        ("The Girl on the Train", "Paula Hawkins"),
        ("Into the Water", "Paula Hawkins"),
        ("The Woman in the Window", "A.J. Finn"),
        ("Sometimes I Lie", "Alice Feeney"),
        ("His & Hers", "Alice Feeney"),
        ("Rock Paper Scissors", "Alice Feeney"),
        ("The Silent Patient", "Alex Michaelides"),
        ("The Maidens", "Alex Michaelides"),
        ("The Wife Between Us", "Greer Hendricks"),
        ("An Anonymous Girl", "Greer Hendricks"),
        ("The Last Mrs. Parrish", "Liv Constantine"),
        ("The Last Time I Lied", "Riley Sager"),
        ("Lock Every Door", "Riley Sager"),
        ("Home Before Dark", "Riley Sager"),
        ("Survive the Night", "Riley Sager"),
        ("The House Across the Lake", "Riley Sager"),
        ("The Only One Left", "Riley Sager"),
        ("I'm Thinking of Ending Things", "Iain Reid"),
        ("We Spread", "Iain Reid"),
    ],
    # ── Domestic Thriller + Gaslighting + Cover-Up ──────────────────────────
    "Gaslighting + Domestic Thriller": [
        ("Gone Girl", "Gillian Flynn"),
        ("Sharp Objects", "Gillian Flynn"),
        ("Dark Places", "Gillian Flynn"),
        ("Behind Closed Doors", "B.A. Paris"),
        ("The Breakdown", "B.A. Paris"),
        ("Bring Me Back", "B.A. Paris"),
        ("The Dilemma", "B.A. Paris"),
        ("The Prisoner", "B.A. Paris"),
        ("The Guest List", "Lucy Foley"),
        ("The Hunting Party", "Lucy Foley"),
        ("The Paris Apartment", "Lucy Foley"),
        ("Verity", "Colleen Hoover"),
        ("The Housemaid", "Freida McFadden"),
        ("The Housemaid's Secret", "Freida McFadden"),
        ("The Housemaid Is Watching", "Freida McFadden"),
        ("The Inmate", "Freida McFadden"),
        ("Never Lie", "Freida McFadden"),
        ("The Perfect Son", "Freida McFadden"),
        ("One by One", "Ruth Ware"),
        ("The Death of Mrs. Westaway", "Ruth Ware"),
    ],
    # ── Serial Killer Thriller + Cat and Mouse + Killer POV ─────────────────
    "Serial Killer + Cat and Mouse": [
        ("The Silence of the Lambs", "Thomas Harris"),
        ("Red Dragon", "Thomas Harris"),
        ("Hannibal", "Thomas Harris"),
        ("Hannibal Rising", "Thomas Harris"),
        ("The Snowman", "Jo Nesbo"),
        ("The Leopard", "Jo Nesbo"),
        ("Phantom", "Jo Nesbo"),
        ("The Bat", "Jo Nesbo"),
        ("Cockroaches", "Jo Nesbo"),
        ("The Chestnut Man", "Soren Sveistrup"),
        ("Pretty Girls", "Karin Slaughter"),
        ("The Good Daughter", "Karin Slaughter"),
        ("Pieces of Her", "Karin Slaughter"),
        ("False Witness", "Karin Slaughter"),
        ("The Whisper Man", "Alex North"),
        ("The Shadows", "Alex North"),
        ("The Angel Maker", "Alex North"),
        ("The Nothing Man", "Catherine Ryan Howard"),
        ("56 Days", "Catherine Ryan Howard"),
        ("The Killer Inside Me", "Jim Thompson"),
    ],
    # ── Psychological Thriller + Stalking + Obsession ───────────────────────
    "Stalking + Obsession + Psychological": [
        ("You", "Caroline Kepnes"),
        ("Hidden Bodies", "Caroline Kepnes"),
        ("You Love Me", "Caroline Kepnes"),
        ("For You and Only You", "Caroline Kepnes"),
        ("The Collector", "John Fowles"),
        ("Misery", "Stephen King"),
        ("Gerald's Game", "Stephen King"),
        ("The Perfect Nanny", "Leila Slimani"),
        ("Social Creature", "Tara Isabella Burton"),
        ("The Photographer", "Mary Dixie Carter"),
        ("Looker", "Laura Sims"),
        ("The Last House on Needless Street", "Catriona Ward"),
        ("Sundial", "Catriona Ward"),
        ("Little Eve", "Catriona Ward"),
        ("The Other Black Girl", "Zakiya Dalila Harris"),
        ("The Push", "Ashley Audrain"),
        ("The Whispers", "Ashley Audrain"),
        ("The Drowning Kind", "Jennifer McMahon"),
        ("The Children on the Hill", "Jennifer McMahon"),
        ("A Flicker in the Dark", "Stacy Willingham"),
    ],
    # ── Psychological Thriller + Twist Ending + Everyone Is a Suspect ───────
    "Twist Ending + Everyone Is a Suspect": [
        ("The Girl with the Dragon Tattoo", "Stieg Larsson"),
        ("The Girl Who Played with Fire", "Stieg Larsson"),
        ("The Girl Who Kicked the Hornet's Nest", "Stieg Larsson"),
        ("Shutter Island", "Dennis Lehane"),
        ("Mystic River", "Dennis Lehane"),
        ("Gone Baby Gone", "Dennis Lehane"),
        ("Darkness Take My Hand", "Dennis Lehane"),
        ("The Kind Worth Killing", "Peter Swanson"),
        ("Her Every Fear", "Peter Swanson"),
        ("Before She Knew Him", "Peter Swanson"),
        ("Eight Perfect Murders", "Peter Swanson"),
        ("Every Last Fear", "Peter Swanson"),
        ("The Couple Next Door", "Shari Lapena"),
        ("A Stranger in the House", "Shari Lapena"),
        ("An Unwanted Guest", "Shari Lapena"),
        ("Someone We Know", "Shari Lapena"),
        ("The End of Her", "Shari Lapena"),
        ("Not a Happy Family", "Shari Lapena"),
        ("The Familiar Dark", "Amy Engel"),
        ("The Butterfly Garden", "Dot Hutchison"),
    ],
    # ── Missing Person + Cold Case + Cover-Up ───────────────────────────────
    "Missing Person + Cold Case": [
        ("The Lovely Bones", "Alice Sebold"),
        ("Then She Was Gone", "Lisa Jewell"),
        ("The Family Upstairs", "Lisa Jewell"),
        ("Watching You", "Lisa Jewell"),
        ("Invisible Girl", "Lisa Jewell"),
        ("The Night She Disappeared", "Lisa Jewell"),
        ("None of This Is True", "Lisa Jewell"),
        ("The Vanishing Half", "Brit Bennett"),
        ("Local Woman Missing", "Mary Kubica"),
        ("The Good Girl", "Mary Kubica"),
        ("Don't You Cry", "Mary Kubica"),
        ("When the Lights Go Out", "Mary Kubica"),
        ("The Other Mrs.", "Mary Kubica"),
        ("Where the Crawdads Sing", "Delia Owens"),
        ("The Dry", "Jane Harper"),
        ("Force of Nature", "Jane Harper"),
        ("The Lost Man", "Jane Harper"),
        ("The Survivors", "Jane Harper"),
        ("Exiles", "Jane Harper"),
        ("The Last Thing He Told Me", "Laura Dave"),
    ],
    # ── Police Procedural + Serial Killer + Race Against Time ───────────────
    "Police Procedural + Race Against Time": [
        ("The Poet", "Michael Connelly"),
        ("The Narrows", "Michael Connelly"),
        ("The Scarecrow", "Michael Connelly"),
        ("Fair Warning", "Michael Connelly"),
        ("The Black Echo", "Michael Connelly"),
        ("The Black Ice", "Michael Connelly"),
        ("The Concrete Blonde", "Michael Connelly"),
        ("The Last Coyote", "Michael Connelly"),
        ("Along Came a Spider", "James Patterson"),
        ("Kiss the Girls", "James Patterson"),
        ("Jack & Jill", "James Patterson"),
        ("Cat & Mouse", "James Patterson"),
        ("Pop Goes the Weasel", "James Patterson"),
        ("In the Woods", "Tana French"),
        ("The Likeness", "Tana French"),
        ("Faithful Place", "Tana French"),
        ("Broken Harbor", "Tana French"),
        ("The Secret Place", "Tana French"),
        ("The Trespasser", "Tana French"),
        ("The Searcher", "Tana French"),
    ],
    # ── Wrongfully Accused + Vigilante Justice + Conspiracy ─────────────────
    "Wrongfully Accused + Conspiracy": [
        ("The Firm", "John Grisham"),
        ("The Pelican Brief", "John Grisham"),
        ("The Client", "John Grisham"),
        ("The Runaway Jury", "John Grisham"),
        ("A Time to Kill", "John Grisham"),
        ("The Partner", "John Grisham"),
        ("Presumed Innocent", "Scott Turow"),
        ("The Burden of Proof", "Scott Turow"),
        ("Pleading Guilty", "Scott Turow"),
        ("The Lincoln Lawyer", "Michael Connelly"),
        ("The Brass Verdict", "Michael Connelly"),
        ("The Reversal", "Michael Connelly"),
        ("The Gods of Guilt", "Michael Connelly"),
        ("Defending Jacob", "William Landay"),
        ("The Stranger", "Harlan Coben"),
        ("Tell No One", "Harlan Coben"),
        ("Gone for Good", "Harlan Coben"),
        ("The Woods", "Harlan Coben"),
        ("Hold Tight", "Harlan Coben"),
        ("Caught", "Harlan Coben"),
    ],
    # ── Cozy Mystery + Whodunit + Locked Room Mystery ───────────────────────
    "Cozy Mystery + Whodunit": [
        ("And Then There Were None", "Agatha Christie"),
        ("Murder on the Orient Express", "Agatha Christie"),
        ("The Murder of Roger Ackroyd", "Agatha Christie"),
        ("Death on the Nile", "Agatha Christie"),
        ("The ABC Murders", "Agatha Christie"),
        ("A Murder Is Announced", "Agatha Christie"),
        ("The Body in the Library", "Agatha Christie"),
        ("The Moving Finger", "Agatha Christie"),
        ("The Thursday Murder Club", "Richard Osman"),
        ("The Man Who Died Twice", "Richard Osman"),
        ("The Bullet That Missed", "Richard Osman"),
        ("The Last Devil to Die", "Richard Osman"),
        ("The Marlow Murder Club", "Robert Thorogood"),
        ("Death in the English Countryside", "Sara Rosett"),
        ("The Unexpected Mrs. Pollifax", "Dorothy Gilman"),
        ("A Man Lay Dead", "Ngaio Marsh"),
        ("Still Life", "Louise Penny"),
        ("A Fatal Grace", "Louise Penny"),
        ("The Cruelest Month", "Louise Penny"),
        ("A Rule Against Murder", "Louise Penny"),
    ],
    # ── Noir + Anti-Hero + Corruption of Power ──────────────────────────────
    "Noir + Corruption": [
        ("The Big Sleep", "Raymond Chandler"),
        ("Farewell My Lovely", "Raymond Chandler"),
        ("The Long Goodbye", "Raymond Chandler"),
        ("The Lady in the Lake", "Raymond Chandler"),
        ("The Maltese Falcon", "Dashiell Hammett"),
        ("The Thin Man", "Dashiell Hammett"),
        ("Red Harvest", "Dashiell Hammett"),
        ("The Glass Key", "Dashiell Hammett"),
        ("Double Indemnity", "James M. Cain"),
        ("The Postman Always Rings Twice", "James M. Cain"),
        ("Mildred Pierce", "James M. Cain"),
        ("L.A. Confidential", "James Ellroy"),
        ("The Black Dahlia", "James Ellroy"),
        ("American Tabloid", "James Ellroy"),
        ("The Big Nowhere", "James Ellroy"),
        ("Devil in a Blue Dress", "Walter Mosley"),
        ("A Red Death", "Walter Mosley"),
        ("White Butterfly", "Walter Mosley"),
        ("Black Betty", "Walter Mosley"),
        ("A Little Yellow Dog", "Walter Mosley"),
    ],
    # ── Spy Thriller + Conspiracy + Race Against Time ───────────────────────
    "Spy Thriller + Conspiracy": [
        ("Tinker Tailor Soldier Spy", "John le Carre"),
        ("The Spy Who Came in from the Cold", "John le Carre"),
        ("Smiley's People", "John le Carre"),
        ("The Honourable Schoolboy", "John le Carre"),
        ("The Night Manager", "John le Carre"),
        ("A Perfect Spy", "John le Carre"),
        ("The Constant Gardener", "John le Carre"),
        ("Our Kind of Traitor", "John le Carre"),
        ("Slow Horses", "Mick Herron"),
        ("Dead Lions", "Mick Herron"),
        ("Real Tigers", "Mick Herron"),
        ("Spook Street", "Mick Herron"),
        ("London Rules", "Mick Herron"),
        ("Joe Country", "Mick Herron"),
        ("The Bourne Identity", "Robert Ludlum"),
        ("The Bourne Supremacy", "Robert Ludlum"),
        ("The Bourne Ultimatum", "Robert Ludlum"),
        ("The Day of the Jackal", "Frederick Forsyth"),
        ("The Odessa File", "Frederick Forsyth"),
        ("The Dogs of War", "Frederick Forsyth"),
    ],
    # ── Psychological Horror + Isolation + Survival ─────────────────────────
    "Isolation + Psychological Horror": [
        ("The Haunting of Hill House", "Shirley Jackson"),
        ("We Have Always Lived in the Castle", "Shirley Jackson"),
        ("The Shining", "Stephen King"),
        ("Pet Sematary", "Stephen King"),
        ("Rosemary's Baby", "Ira Levin"),
        ("The Stepford Wives", "Ira Levin"),
        ("The Silence of the Lambs", "Thomas Harris"),
        ("Bird Box", "Josh Malerman"),
        ("Malorie", "Josh Malerman"),
        ("A Head Full of Ghosts", "Paul Tremblay"),
        ("The Cabin at the End of the World", "Paul Tremblay"),
        ("Disappearance at Devil's Rock", "Paul Tremblay"),
        ("Survivor Song", "Paul Tremblay"),
        ("The Troop", "Nick Cutter"),
        ("The Deep", "Nick Cutter"),
        ("Little Heaven", "Nick Cutter"),
        ("The Ruins", "Scott Smith"),
        ("House of Leaves", "Mark Z. Danielewski"),
        ("Mexican Gothic", "Silvia Moreno-Garcia"),
        ("The Only Good Indians", "Stephen Graham Jones"),
    ],
    # ── Dual Timeline + Reverse Timeline + Memory Gaps ──────── (v5.1 axes)
    "Dual Timeline + Reverse Timeline": [
        ("The Thirteenth Tale", "Diane Setterfield"),
        ("The Secret Keeper", "Kate Morton"),
        ("The House at Riverton", "Kate Morton"),
        ("The Forgotten Garden", "Kate Morton"),
        ("The Lake House", "Kate Morton"),
        ("The Distant Hours", "Kate Morton"),
        ("The Clockmaker's Daughter", "Kate Morton"),
        ("The Shadow of the Wind", "Carlos Ruiz Zafon"),
        ("The Angel's Game", "Carlos Ruiz Zafon"),
        ("The Prisoner of Heaven", "Carlos Ruiz Zafon"),
        ("The Labyrinth of the Spirits", "Carlos Ruiz Zafon"),
        ("The Historian", "Elizabeth Kostova"),
        ("The Swan Thieves", "Elizabeth Kostova"),
        ("The Shadow Land", "Elizabeth Kostova"),
        ("The Keep", "Jennifer Egan"),
        ("The Weight of Ink", "Rachel Kadish"),
        ("Possession", "A.S. Byatt"),
        ("Fingersmith", "Sarah Waters"),
        ("The Little Stranger", "Sarah Waters"),
        ("The Paying Guests", "Sarah Waters"),
    ],
    # ── Multi-POV Structure + Paranoia + Conspiracy ────────────── (v5.1 axes)
    "Multi-POV + Paranoia": [
        ("The Passage", "Justin Cronin"),
        ("The Twelve", "Justin Cronin"),
        ("The City of Mirrors", "Justin Cronin"),
        ("Station Eleven", "Emily St. John Mandel"),
        ("The Glass Hotel", "Emily St. John Mandel"),
        ("Sea of Tranquility", "Emily St. John Mandel"),
        ("The Stand", "Stephen King"),
        ("Under the Dome", "Stephen King"),
        ("11/22/63", "Stephen King"),
        ("The Terror", "Dan Simmons"),
        ("Drood", "Dan Simmons"),
        ("The Abominable", "Dan Simmons"),
        ("World War Z", "Max Brooks"),
        ("Devolution", "Max Brooks"),
        ("The Three-Body Problem", "Cixin Liu"),
        ("Dark Matter", "Blake Crouch"),
        ("Recursion", "Blake Crouch"),
        ("Upgrade", "Blake Crouch"),
        ("The Gone World", "Tom Sweterlitsch"),
        ("Tomorrow and Tomorrow", "Tom Sweterlitsch"),
    ],
    # ── Epistolary + Cold/Clinical + Investigation ──────────────── (v5.1 axes)
    "Epistolary + Cold Clinical": [
        ("Dracula", "Bram Stoker"),
        ("Frankenstein", "Mary Shelley"),
        ("The Woman in White", "Wilkie Collins"),
        ("The Moonstone", "Wilkie Collins"),
        ("The Turn of the Screw", "Henry James"),
        ("We Need to Talk About Kevin", "Lionel Shriver"),
        ("The Color Purple", "Alice Walker"),
        ("Flowers for Algernon", "Daniel Keyes"),
        ("Where'd You Go Bernadette", "Maria Semple"),
        ("Today Will Be Different", "Maria Semple"),
        ("The Guernsey Literary and Potato Peel Pie Society", "Mary Ann Shaffer"),
        ("84 Charing Cross Road", "Helene Hanff"),
        ("Dangerous Liaisons", "Pierre Choderlos de Laclos"),
        ("The Sorrows of Young Werther", "Johann Wolfgang von Goethe"),
        ("Devil in the White City", "Erik Larson"),
        ("In Cold Blood", "Truman Capote"),
        ("The Executioner's Song", "Norman Mailer"),
        ("Helter Skelter", "Vincent Bugliosi"),
        ("I'll Be Gone in the Dark", "Michelle McNamara"),
        ("The Stranger Beside Me", "Ann Rule"),
    ],
    # ── Single POV + Guilt + Internal Conflict ────────────────── (v5.1 axes)
    "Single POV + Guilt": [
        ("Crime and Punishment", "Fyodor Dostoevsky"),
        ("Notes from Underground", "Fyodor Dostoevsky"),
        ("The Stranger", "Albert Camus"),
        ("The Fall", "Albert Camus"),
        ("Native Son", "Richard Wright"),
        ("An American Tragedy", "Theodore Dreiser"),
        ("The Picture of Dorian Gray", "Oscar Wilde"),
        ("The Talented Mr. Ripley", "Patricia Highsmith"),
        ("Ripley Under Ground", "Patricia Highsmith"),
        ("Ripley's Game", "Patricia Highsmith"),
        ("The Boy Who Followed Ripley", "Patricia Highsmith"),
        ("Ripley Under Water", "Patricia Highsmith"),
        ("Zombie", "Joyce Carol Oates"),
        ("American Psycho", "Bret Easton Ellis"),
        ("The Secret History", "Donna Tartt"),
        ("The Goldfinch", "Donna Tartt"),
        ("A Little Life", "Hanya Yanagihara"),
        ("The People in the Trees", "Hanya Yanagihara"),
        ("My Dark Vanessa", "Kate Elizabeth Russell"),
        ("Tampa", "Alissa Nutting"),
    ],
    # ── Mind-Bending + Dark Tone + Reality Distortion ───────────── (v5.1 axes)
    "Mind-Bending + Dark": [
        ("House of Leaves", "Mark Z. Danielewski"),
        ("The Raw Shark Texts", "Steven Hall"),
        ("S.", "J.J. Abrams"),
        ("The Night Film", "Marisha Pessl"),
        ("Special Topics in Calamity Physics", "Marisha Pessl"),
        ("Bunny", "Mona Awad"),
        ("Rouge", "Mona Awad"),
        ("All's Well", "Mona Awad"),
        ("Fever Dream", "Samanta Schweblin"),
        ("Little Eyes", "Samanta Schweblin"),
        ("Annihilation", "Jeff VanderMeer"),
        ("Authority", "Jeff VanderMeer"),
        ("Acceptance", "Jeff VanderMeer"),
        ("Borne", "Jeff VanderMeer"),
        ("Piranesi", "Susanna Clarke"),
        ("The Library at Mount Char", "Scott Hawkins"),
        ("The Cipher", "Kathe Koja"),
        ("Negative Space", "B.R. Yeager"),
        ("Earthlings", "Sayaka Murata"),
        ("Convenience Store Woman", "Sayaka Murata"),
    ],
    # ── Fear of Exposure + Moral Ambiguity + Secret Past ────────── (v5.1 axes)
    "Fear of Exposure + Moral Ambiguity": [
        ("Big Little Lies", "Liane Moriarty"),
        ("The Husband's Secret", "Liane Moriarty"),
        ("What Alice Forgot", "Liane Moriarty"),
        ("Nine Perfect Strangers", "Liane Moriarty"),
        ("Apples Never Fall", "Liane Moriarty"),
        ("Truly Madly Guilty", "Liane Moriarty"),
        ("The Nightingale", "Kristin Hannah"),
        ("The Great Alone", "Kristin Hannah"),
        ("The Four Winds", "Kristin Hannah"),
        ("The Woman in Cabin 10", "Ruth Ware"),
        ("The Turn of the Key", "Ruth Ware"),
        ("The Lying Game", "Ruth Ware"),
        ("In a Dark Dark Wood", "Ruth Ware"),
        ("The It Girl", "Ruth Ware"),
        ("Zero Days", "Ruth Ware"),
        ("Luckiest Girl Alive", "Jessica Knoll"),
        ("The Favorite Sister", "Jessica Knoll"),
        ("Bright Young Women", "Jessica Knoll"),
        ("The Secrets She Keeps", "Michael Robotham"),
        ("Good Girl Bad Blood", "Holly Jackson"),
    ],
}
